### ISSUE TITLE
Allow build on non-linux architectures

### ISSUE THREAD

**Issue by miramikes** [thestk/rtaudio#110]
Hi,

following patch allow rtaudio to be build on non-linux archs as hurd-i386 kfreebsd-amd64 kfreebsd-i386.
You might be interested to apply it upstream.

mira
[0001-kfreebsd-hurd.txt](https://github.com/thestk/rtaudio/files/1424301/0001-kfreebsd-hurd.txt)

**Comment by radarsat1** [comment]
This should now be resolved as of adefaebdbcc1c3137b1c9ce8d995ef25564c7fc8
