### ISSUE TITLE
Invalid pointer passed to jack_set_xrun_callback and invalid pointer cast in jackXrun

### ISSUE THREAD

**Issue by bontric** [thestk/rtaudio#113]
After discovering stack smashing errors when using RtAudio with jack, I discovered two problems with the RtAudio Jack implementation: 

#### In ` RtApiJack :: probeDeviceOpen` : 
``` cpp
2147  JackHandle *handle = (JackHandle *) stream_.apiHandle;
```

`handle` is a local variable, but it's address is passed to `jack_set_xrun_callback` (which leads to the stack smashing error, since the address is invalid after the function returns):

``` cpp
2337  jack_set_xrun_callback( handle->client, jackXrun, (void *) &handle ); 
```

I suggest this should be:

``` cpp
2337  jack_set_xrun_callback( handle->client, jackXrun,  (void *) &stream_.apiHandle )); 
```

Note that `&stream_.apiHandle ` and `&handle` are _double pointers_ (`JackHandle**`)

Which leads us to the second issue:

#### In `jackXrun`

```cpp
2131 static int jackXrun( void *infoPointer )
2132 {
2133   JackHandle *handle = (JackHandle *) infoPointer;
2134 
2135   if ( handle->ports[0] ) handle->xrun[0] = true;
2136   if ( handle->ports[1] ) handle->xrun[1] = true;
2137 
2138   return 0;
2139 }
```
Note that `infoPointer` is of type `JackHandle**` but only cast to `JackHandle*`. 

This should be:

```cpp
2133   JackHandle *handle = *((JackHandle **) infoPointer);
```

**Comment by radarsat1** [comment]
Cool!  Nice find.  Did it fix the problem for you?
I'm curious if,

    jack_set_xrun_callback( handle->client, jackXrun, (void *) stream_.apiHandle );

would fix both problems at once?  (Dropping the & operator..)

**Comment by bontric** [comment]
> Cool! Nice find. Did it fix the problem for you?

Yeah, can't seem to reproduce any related issues after fixing those lines :) 



It depends on the rest of the implementation and I haven't looked into it too much. I honestly just used what it was before and went with the parameter passed to the other jack callbacks:
```cpp
    stream_.mode = mode;
    jack_set_process_callback( handle->client, jackCallbackHandler, (void *) &stream_.callbackInfo );
    jack_set_xrun_callback( handle->client, jackXrun, (void *) &handle );
    jack_on_shutdown( handle->client, jackShutdown, (void *) &stream_.callbackInfo );
``` 

From my understanding, using a double pointer would make sense here if the struct is reallocated/reassigned later on. I only see the JackHandle allocated/deallocated once for every stream created so it might not be necessary to pass a double pointer here, but I haven't had the time to test this properly yet.

**Comment by radarsat1** [comment]
Well, sounds good, i'll take it. Definitely a bug, thanks!

**Comment by bontric** [comment]
Thanks for the quick response and fix!
