### ISSUE TITLE
Configure script does not generate .dll file on Mingw64

### ISSUE THREAD

**Issue by AndrewBelt** [thestk/rtaudio#114]
This yields no `librtaudio.dll` file.

	./autogen.sh --no-configure
	./configure --prefix=$PWD/local --exec-prefix=$PWD/local --with-asio --with-wasapi --with-ds
	make && make install

The CMake script does though.

	mkdir cmakebuild && cd cmakebuild 
	cmake -G 'Unix Makefiles' -DCMAKE_INSTALL_PREFIX=$PWD/../local -DAUDIO_WINDOWS_DS=ON -DAUDIO_WINDOWS_WASAPI=ON -DAUDIO_WINDOWS_ASIO=ON ..
	make && make install

**Comment by radarsat1** [comment]
Can you debug it?  And what environment are you using?

**Comment by AndrewBelt** [comment]
Unfortunately I cannot, since I never learned how to produce configure scripts.
The only mention of the string "dll" is in configure.ac

    LT_INIT([win32-dll])

but I don't know what that means.

I am using MSYS2's Mingw64 shell.

**Comment by radarsat1** [comment]
I just realized probably you didn't see that libtool puts dll in a subfolder called `.libs`.  It should be visible if you did `make install`.
