### ISSUE TITLE
Compiling ./autoconf --with-jack

### ISSUE THREAD

**Issue by Cordoha** [thestk/rtaudio#115]
Trying to compile rtaudio with jack support.
``./autoconf --with-jack``

>checking for audio API... using JACK
checking for jack_client_open in -ljack... no
configure: error: JACK support requires the jack library!

Installed:

jackd 5
jackd2 2:1.9.11+git20170722-1~xenial2

Do I need to install jackd1 for compatibility? Is there anyway to enable jackd2 compatibility if that's the issue?

**libjack-jackd2-dev may have been the issue** I'm not 100%.

**Comment by radarsat1** [comment]
Can you please paste the relevant portion of  `config.log` to see which test failed?

**Comment by Cordoha** [comment]
Still an undesired result with running VCV Rack with rtaudio --with-jack. It doesn't suggest jack as an option. But that's out of the realm of this forum I think. 

Core Tests

configure:2444: checking for a BSD-compatible install
configure:2512: result: /usr/bin/install -c
configure:2523: checking whether build environment is sane
configure:2578: result: yes
configure:2729: checking for a thread-safe mkdir -p
configure:2768: result: /bin/mkdir -p
configure:2775: checking for gawk
configure:2791: found /usr/bin/gawk
configure:2802: result: gawk
configure:2813: checking whether make sets $(MAKE)
configure:2835: result: yes
configure:2864: checking whether make supports nested variables
configure:2881: result: yes
configure:3095: checking that version numbers are coherent
configure:3109: result: yes
configure:3115: checking whether to enable maintainer-specific portions of Makefiles
configure:3124: result: yes
configure:3148: checking whether make supports nested variables
configure:3165: result: yes
configure:3250: checking for g++
configure:3266: found /usr/bin/g++
configure:3277: result: g++
configure:3304: checking for C++ compiler version
configure:3313: g++ --version >&5
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

configure:3324: $? = 0
configure:3313: g++ -v >&5
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.5' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5) 
configure:3324: $? = 0
configure:3313: g++ -V >&5
g++: error: unrecognized command line option '-V'
g++: fatal error: no input files
compilation terminated.
configure:3324: $? = 1
configure:3313: g++ -qversion >&5
g++: error: unrecognized command line option '-qversion'
g++: fatal error: no input files
compilation terminated.
configure:3324: $? = 1
configure:3344: checking whether the C++ compiler works
configure:3366: g++    conftest.cpp  >&5
configure:3370: $? = 0
configure:3418: result: yes
configure:3421: checking for C++ compiler default output file name
configure:3423: result: a.out
configure:3429: checking for suffix of executables
configure:3436: g++ -o conftest    conftest.cpp  >&5
configure:3440: $? = 0
configure:3462: result: 
configure:3484: checking whether we are cross compiling
configure:3492: g++ -o conftest    conftest.cpp  >&5
configure:3496: $? = 0
configure:3503: ./conftest
configure:3507: $? = 0
configure:3522: result: no
configure:3527: checking for suffix of object files
configure:3549: g++ -c   conftest.cpp >&5
configure:3553: $? = 0
configure:3574: result: o
configure:3578: checking whether we are using the GNU C++ compiler
configure:3597: g++ -c   conftest.cpp >&5
configure:3597: $? = 0
configure:3606: result: yes
configure:3615: checking whether g++ accepts -g
configure:3635: g++ -c -g  conftest.cpp >&5
configure:3635: $? = 0
configure:3676: result: yes
configure:3710: checking for style of include used by make
configure:3738: result: GNU
configure:3764: checking dependency style of g++
configure:3875: result: gcc3
configure:3938: checking for gcc
configure:3954: found /usr/bin/gcc
configure:3965: result: gcc
configure:4194: checking for C compiler version
configure:4203: gcc --version >&5
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

configure:4214: $? = 0
configure:4203: gcc -v >&5
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.5' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5) 
configure:4214: $? = 0
configure:4203: gcc -V >&5
gcc: error: unrecognized command line option '-V'
gcc: fatal error: no input files
compilation terminated.
configure:4214: $? = 1
configure:4203: gcc -qversion >&5
gcc: error: unrecognized command line option '-qversion'
gcc: fatal error: no input files
compilation terminated.
configure:4214: $? = 1
configure:4218: checking whether we are using the GNU C compiler
configure:4237: gcc -c   conftest.c >&5
configure:4237: $? = 0
configure:4246: result: yes
configure:4255: checking whether gcc accepts -g
configure:4275: gcc -c -g  conftest.c >&5
configure:4275: $? = 0
configure:4316: result: yes
configure:4333: checking for gcc option to accept ISO C89
configure:4396: gcc  -c -g -O2  conftest.c >&5
configure:4396: $? = 0
configure:4409: result: none needed
configure:4434: checking whether gcc understands -c and -o together
configure:4456: gcc -c conftest.c -o conftest2.o
configure:4459: $? = 0
configure:4456: gcc -c conftest.c -o conftest2.o
configure:4459: $? = 0
configure:4471: result: yes
configure:4490: checking dependency style of gcc
configure:4601: result: gcc3
configure:4666: checking for ar
configure:4682: found /usr/bin/ar
configure:4693: result: ar
configure:4719: checking the archiver (ar) interface
configure:4735: gcc -c -g -O2  conftest.c >&5
configure:4735: $? = 0
configure:4737: ar cru libconftest.a conftest.o >&5
ar: `u' modifier ignored since `D' is the default (see `U')
configure:4740: $? = 0
configure:4768: result: ar
configure:4790: checking for ar
configure:4808: found /usr/bin/ar
configure:4821: result: /usr/bin/ar
configure:4865: checking build system type
configure:4879: result: x86_64-pc-linux-gnu
configure:4899: checking host system type
configure:4912: result: x86_64-pc-linux-gnu
configure:4953: checking how to print strings
configure:4980: result: printf
configure:5001: checking for a sed that does not truncate output
configure:5065: result: /bin/sed
configure:5083: checking for grep that handles long lines and -e
configure:5141: result: /bin/grep
configure:5146: checking for egrep
configure:5208: result: /bin/grep -E
configure:5213: checking for fgrep
configure:5275: result: /bin/grep -F
configure:5310: checking for ld used by gcc
configure:5377: result: /usr/bin/ld
configure:5384: checking if the linker (/usr/bin/ld) is GNU ld
configure:5399: result: yes
configure:5411: checking for BSD- or MS-compatible name lister (nm)
configure:5465: result: /usr/bin/nm -B
configure:5595: checking the name lister (/usr/bin/nm -B) interface
configure:5602: gcc -c -g -O2  conftest.c >&5
configure:5605: /usr/bin/nm -B "conftest.o"
configure:5608: output
0000000000000000 B some_variable
configure:5615: result: BSD nm
configure:5618: checking whether ln -s works
configure:5622: result: yes
configure:5630: checking the maximum length of command line arguments
configure:5761: result: 1572864
configure:5809: checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format
configure:5849: result: func_convert_file_noop
configure:5856: checking how to convert x86_64-pc-linux-gnu file names to toolchain format
configure:5876: result: func_convert_file_noop
configure:5883: checking for /usr/bin/ld option to reload object files
configure:5890: result: -r
configure:5964: checking for objdump
configure:5980: found /usr/bin/objdump
configure:5991: result: objdump
configure:6020: checking how to recognize dependent libraries
configure:6220: result: pass_all
configure:6305: checking for dlltool
configure:6335: result: no
configure:6362: checking how to associate runtime and link libraries
configure:6389: result: printf %s\n
configure:6513: checking for archiver @FILE support
configure:6530: gcc -c -g -O2  conftest.c >&5
configure:6530: $? = 0
configure:6533: /usr/bin/ar cru libconftest.a @conftest.lst >&5
/usr/bin/ar: `u' modifier ignored since `D' is the default (see `U')
configure:6536: $? = 0
configure:6541: /usr/bin/ar cru libconftest.a @conftest.lst >&5
/usr/bin/ar: `u' modifier ignored since `D' is the default (see `U')
/usr/bin/ar: conftest.o: No such file or directory
configure:6544: $? = 1
configure:6556: result: @
configure:6614: checking for strip
configure:6630: found /usr/bin/strip
configure:6641: result: strip
configure:6713: checking for ranlib
configure:6729: found /usr/bin/ranlib
configure:6740: result: ranlib
configure:6842: checking command to parse /usr/bin/nm -B output from gcc object
configure:6995: gcc -c -g -O2  conftest.c >&5
configure:6998: $? = 0
configure:7002: /usr/bin/nm -B conftest.o \| sed -n -e 's/^.*[ ]\([ABCDGIRSTW][ABCDGIRSTW]*\)[ ][ ]*\([_A-Za-z][_A-Za-z0-9]*\)$/\1 \2 \2/p' | sed '/ __gnu_lto/d' \> conftest.nm
configure:7005: $? = 0
configure:7071: gcc -o conftest -g -O2   conftest.c conftstm.o >&5
configure:7074: $? = 0
configure:7112: result: ok
configure:7159: checking for sysroot
configure:7189: result: no
configure:7196: checking for a working dd
configure:7234: result: /bin/dd
configure:7238: checking how to truncate binary pipes
configure:7253: result: /bin/dd bs=4096 count=1
configure:7389: gcc -c -g -O2  conftest.c >&5
configure:7392: $? = 0
configure:7582: checking for mt
configure:7598: found /bin/mt
configure:7609: result: mt
configure:7632: checking if mt is a manifest tool
configure:7638: mt '-?'
configure:7646: result: no
configure:8323: checking how to run the C preprocessor
configure:8354: gcc -E  conftest.c
configure:8354: $? = 0
configure:8368: gcc -E  conftest.c
conftest.c:11:28: fatal error: ac_nonexistent.h: No such file or directory
compilation terminated.
configure:8368: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "RtAudio"
| #define PACKAGE_TARNAME "rtaudio"
| #define PACKAGE_VERSION "5.0.0"
| #define PACKAGE_STRING "RtAudio 5.0.0"
| #define PACKAGE_BUGREPORT "gary@music.mcgill.ca"
| #define PACKAGE_URL ""
| #define PACKAGE "rtaudio"
| #define VERSION "5.0.0"
| /* end confdefs.h.  */
| #include <ac_nonexistent.h>
configure:8393: result: gcc -E
configure:8413: gcc -E  conftest.c
configure:8413: $? = 0
configure:8427: gcc -E  conftest.c
conftest.c:11:28: fatal error: ac_nonexistent.h: No such file or directory
compilation terminated.
configure:8427: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "RtAudio"
| #define PACKAGE_TARNAME "rtaudio"
| #define PACKAGE_VERSION "5.0.0"
| #define PACKAGE_STRING "RtAudio 5.0.0"
| #define PACKAGE_BUGREPORT "gary@music.mcgill.ca"
| #define PACKAGE_URL ""
| #define PACKAGE "rtaudio"
| #define VERSION "5.0.0"
| /* end confdefs.h.  */
| #include <ac_nonexistent.h>
configure:8456: checking for ANSI C header files
configure:8476: gcc -c -g -O2  conftest.c >&5
configure:8476: $? = 0
configure:8549: gcc -o conftest -g -O2   conftest.c  >&5
configure:8549: $? = 0
configure:8549: ./conftest
configure:8549: $? = 0
configure:8560: result: yes
configure:8573: checking for sys/types.h
configure:8573: gcc -c -g -O2  conftest.c >&5
configure:8573: $? = 0
configure:8573: result: yes
configure:8573: checking for sys/stat.h
configure:8573: gcc -c -g -O2  conftest.c >&5
configure:8573: $? = 0
configure:8573: result: yes
configure:8573: checking for stdlib.h
configure:8573: gcc -c -g -O2  conftest.c >&5
configure:8573: $? = 0
configure:8573: result: yes
configure:8573: checking for string.h
configure:8573: gcc -c -g -O2  conftest.c >&5
configure:8573: $? = 0
configure:8573: result: yes
configure:8573: checking for memory.h
configure:8573: gcc -c -g -O2  conftest.c >&5
configure:8573: $? = 0
configure:8573: result: yes
configure:8573: checking for strings.h
configure:8573: gcc -c -g -O2  conftest.c >&5
configure:8573: $? = 0
configure:8573: result: yes
configure:8573: checking for inttypes.h
configure:8573: gcc -c -g -O2  conftest.c >&5
configure:8573: $? = 0
configure:8573: result: yes
configure:8573: checking for stdint.h
configure:8573: gcc -c -g -O2  conftest.c >&5
configure:8573: $? = 0
configure:8573: result: yes
configure:8573: checking for unistd.h
configure:8573: gcc -c -g -O2  conftest.c >&5
configure:8573: $? = 0
configure:8573: result: yes
configure:8587: checking for dlfcn.h
configure:8587: gcc -c -g -O2  conftest.c >&5
configure:8587: $? = 0
configure:8587: result: yes
configure:9152: checking for objdir
configure:9167: result: .libs
configure:9431: checking if gcc supports -fno-rtti -fno-exceptions
configure:9449: gcc -c -g -O2  -fno-rtti -fno-exceptions conftest.c >&5
cc1: warning: command line option '-fno-rtti' is valid for C++/ObjC++ but not for C
configure:9453: $? = 0
configure:9466: result: no
configure:9824: checking for gcc option to produce PIC
configure:9831: result: -fPIC -DPIC
configure:9839: checking if gcc PIC flag -fPIC -DPIC works
configure:9857: gcc -c -g -O2  -fPIC -DPIC -DPIC conftest.c >&5
configure:9861: $? = 0
configure:9874: result: yes
configure:9903: checking if gcc static flag -static works
configure:9931: result: yes
configure:9946: checking if gcc supports -c -o file.o
configure:9967: gcc -c -g -O2  -o out/conftest2.o conftest.c >&5
configure:9971: $? = 0
configure:9993: result: yes
configure:10001: checking if gcc supports -c -o file.o
configure:10048: result: yes
configure:10081: checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries
configure:11344: result: yes
configure:11381: checking whether -lc should be explicitly linked in
configure:11389: gcc -c -g -O2  conftest.c >&5
configure:11392: $? = 0
configure:11407: gcc -shared  -fPIC -DPIC conftest.o  -v -Wl,-soname -Wl,conftest -o conftest 2\>\&1 \| /bin/grep  -lc  \>/dev/null 2\>\&1
configure:11410: $? = 0
configure:11424: result: no
configure:11584: checking dynamic linker characteristics
configure:12165: gcc -o conftest -g -O2   -Wl,-rpath -Wl,/foo conftest.c  >&5
configure:12165: $? = 0
configure:12414: result: GNU/Linux ld.so
configure:12536: checking how to hardcode library paths into programs
configure:12561: result: immediate
configure:13109: checking whether stripping libraries is possible
configure:13114: result: yes
configure:13149: checking if libtool supports shared libraries
configure:13151: result: yes
configure:13154: checking whether to build shared libraries
configure:13179: result: yes
configure:13182: checking whether to build static libraries
configure:13186: result: yes
configure:13209: checking how to run the C++ preprocessor
configure:13236: g++ -E  conftest.cpp
configure:13236: $? = 0
configure:13250: g++ -E  conftest.cpp
conftest.cpp:23:28: fatal error: ac_nonexistent.h: No such file or directory
compilation terminated.
configure:13250: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "RtAudio"
| #define PACKAGE_TARNAME "rtaudio"
| #define PACKAGE_VERSION "5.0.0"
| #define PACKAGE_STRING "RtAudio 5.0.0"
| #define PACKAGE_BUGREPORT "gary@music.mcgill.ca"
| #define PACKAGE_URL ""
| #define PACKAGE "rtaudio"
| #define VERSION "5.0.0"
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| #define HAVE_DLFCN_H 1
| #define LT_OBJDIR ".libs/"
| /* end confdefs.h.  */
| #include <ac_nonexistent.h>
configure:13275: result: g++ -E
configure:13295: g++ -E  conftest.cpp
configure:13295: $? = 0
configure:13309: g++ -E  conftest.cpp
conftest.cpp:23:28: fatal error: ac_nonexistent.h: No such file or directory
compilation terminated.
configure:13309: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "RtAudio"
| #define PACKAGE_TARNAME "rtaudio"
| #define PACKAGE_VERSION "5.0.0"
| #define PACKAGE_STRING "RtAudio 5.0.0"
| #define PACKAGE_BUGREPORT "gary@music.mcgill.ca"
| #define PACKAGE_URL ""
| #define PACKAGE "rtaudio"
| #define VERSION "5.0.0"
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| #define HAVE_DLFCN_H 1
| #define LT_OBJDIR ".libs/"
| /* end confdefs.h.  */
| #include <ac_nonexistent.h>
configure:13471: checking for ld used by g++
configure:13538: result: /usr/bin/ld -m elf_x86_64
configure:13545: checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld
configure:13560: result: yes
configure:13615: checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries
configure:14688: result: yes
configure:14724: g++ -c -g -O2  conftest.cpp >&5
configure:14727: $? = 0
configure:15208: checking for g++ option to produce PIC
configure:15215: result: -fPIC -DPIC
configure:15223: checking if g++ PIC flag -fPIC -DPIC works
configure:15241: g++ -c -g -O2  -fPIC -DPIC -DPIC conftest.cpp >&5
configure:15245: $? = 0
configure:15258: result: yes
configure:15281: checking if g++ static flag -static works
configure:15309: result: yes
configure:15321: checking if g++ supports -c -o file.o
configure:15342: g++ -c -g -O2  -o out/conftest2.o conftest.cpp >&5
configure:15346: $? = 0
configure:15368: result: yes
configure:15373: checking if g++ supports -c -o file.o
configure:15420: result: yes
configure:15450: checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries
configure:15493: result: yes
configure:15634: checking dynamic linker characteristics
configure:16391: result: GNU/Linux ld.so
configure:16456: checking how to hardcode library paths into programs
configure:16481: result: immediate
configure:16545: checking for ANSI C header files
configure:16649: result: yes
configure:16660: checking sys/ioctl.h usability
configure:16660: gcc -c -g -O2  conftest.c >&5
configure:16660: $? = 0
configure:16660: result: yes
configure:16660: checking sys/ioctl.h presence
configure:16660: gcc -E  conftest.c
configure:16660: $? = 0
configure:16660: result: yes
configure:16660: checking for sys/ioctl.h
configure:16660: result: yes
configure:16660: checking for unistd.h
configure:16660: result: yes
configure:16690: checking whether to compile debug version
configure:16696: result: yes
configure:16733: checking for gettimeofday
configure:16733: gcc -o conftest -g -O2  -g -O0   conftest.c  >&5
configure:16733: $? = 0
configure:16733: result: yes
configure:16742: checking for doxygen
configure:16772: result: no
configure:16825: checking for audio API
configure:16830: result: using JACK
configure:16832: checking for jack_client_open in -ljack
configure:16857: gcc -o conftest -g -O2  -g -O0   conftest.c -ljack   >&5
configure:16857: $? = 0
configure:16866: result: yes
configure:17257: checking for pthread_create in -lpthread
configure:17282: gcc -o conftest -g -O2  -g -O0   conftest.c -lpthread  -ljack  >&5
configure:17282: $? = 0
configure:17291: result: yes
configure:17596: checking that generated files are newer than configure
configure:17602: result: done
configure:17641: creating ./config.status

**Comment by radarsat1** [comment]
Sorry, I'm confused.  Your initial message says,

    checking for audio API... using JACK
    checking for jack_client_open in -ljack... no
    configure: error: JACK support requires the jack library!

but the output you just pasted says,

    configure:16825: checking for audio API
    configure:16830: result: using JACK
    configure:16832: checking for jack_client_open in -ljack
    configure:16857: gcc -o conftest -g -O2 -g -O0 conftest.c -ljack >&5
    configure:16857: $? = 0
    configure:16866: result: yes

These results seem to be at odds.

**Comment by Cordoha** [comment]
I believe I fixed it when I installed jackd2-dev package after compiling.  I'm just at odds as to why VCV Rack still says I am still using ALSA with no option to select JACK.

Thanks

**Comment by dvzrv** [comment]
Sorry for commenting on a potentially dead issue, but it seems, that when selecting `--with-jack` this is not added to `rtaudio.pc` (however, the other selected backends are!)!

Currently I'm moving rtaudio to the Arch Linux repositories and there has been a fix to add jack to the `Requires` line in above mentioned file!
This seems to be a bug.

**Comment by radarsat1** [comment]
Can you report if it's fixed in e70927f4eed0f241dfd92b5f3feccb0f4649aa2e ?

**Comment by dvzrv** [comment]
Yes, but again, I didn't know how to use that commit properly, so applied the missing line `req="$req jack"`
It's fixed in version [5.0.0-5](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/rtaudio).
