### ISSUE TITLE
Is there any example for WASAPI Loopback record ?

### ISSUE THREAD

**Issue by namkazt** [thestk/rtaudio#117]
Hi all. 

i am new to rtaudio and still looking for a way to capture audio output from global output device.
i see some document about WASAPI loopback streamflags. and do not know if RTAudio support for it or not.

thanks in advance

**Comment by radarsat1** [comment]
Not sure, I don't think so.  If you run the audioprobe example it will list all the ports you can open.  One method might be to just add a port for loop-back for audio backends that support it.  Not sure if that's the best approach.

**Comment by namkazt** [comment]
thanks. np. i got it.

**Comment by MykonCodes** [comment]
@namkazt  Hey. Would you be willing to share your solution? Would be very appreciated.

All the best,
Mykon

**Comment by namkazt** [comment]
@MykonCodes I did not use RTAudio. I wrote WASAPI directly
