### ISSUE TITLE
RtAudio NodeJS Bindings (and an ASIO question)

### ISSUE THREAD

**Issue by liamwhan** [thestk/rtaudio#121]
Hi there, 

I'm working on a [NodeJS binding for RtAudio](https://github.com/hammus/rtaudiojs). 
I just stumbled across your `contrib/` folder, and thought I might as well let you know I'm working on it in case you want to include it.

I'm happy to do the work to make it easier for you to provide a copy of it here, but it might be more trouble than its worth as the tool-chain and environment is not as simple as the Go or Python ports (i.e. it has to be compiled with `node-gyp` first so you couldn't just include source files as you've done with Go/Python), but given you've created this great library I thought you should at least have the option if you want it.

It's in it's early stages at the moment: I've only exposed a `deviceProbe()` method to Javascript which is just an implementation of `audioprobe.cpp` but its working great with the DirectSound and WASAPI preproc definitions.

### ASIO 
I'm at a bit of a loss with what to do about ASIO given the licensing restrictions on redistribution, I pushed an `include/` folder to my repo earlier that contained exactly what your `include/` folder does and a GH bot flagged my account. 

I'm curious as to how to obtained permission to redistribute them as it seems ridiculous not to offer ASIO support in the NodeJS binding when the ASIO source files are pubically available in many places (not just here).

Interested to hear your thoughts.

**Comment by garyscavone** [comment]
Stale ... closing.
