### ISSUE TITLE
FreeBSD OSS

### ISSUE THREAD

**Issue by mekanix** [thestk/rtaudio#124]
I get the following error:
`RtApiOss::probeDeviceOpen: device (pcm0:play:dsp0.p0) is busy.`

I don't know where p0 comes from. I tried hardcoding "/dev/dsp" and "/dev/dsp0" in https://github.com/thestk/rtaudio/blob/master/RtAudio.cpp#L8769 and those work. The example I tried is https://github.com/thestk/rtaudio/blob/master/doc/doxygen/playback.txt. That being said, would you accept PR adding FREEBSD_OSS in https://github.com/thestk/rtaudio/blob/master/RtAudio.h#L278? I mean, it needs more than that, but I'd like to work on that as it's so close to work on this platform, too.

**Comment by mekanix** [comment]
I guess FreeBSD enumerates devices differently than Linux, so this is what ls shows me:
```
ls -l /dev/dsp*
crw-rw-rw-  1 root  wheel   0x92 Jan  6 21:45 /dev/dsp0.0
crw-rw-rw-  1 root  wheel   0x91 Jan  6 22:37 /dev/dsp0.1
crw-rw-rw-  1 root  wheel   0x93 Jan  6 22:37 /dev/dsp0.2
crw-rw-rw-  1 root  wheel   0x9b Jan  7 15:19 /dev/dsp0.3
crw-rw-rw-  1 root  wheel   0x83 Jan  6 22:15 /dev/dsp0.p0
crw-rw-rw-  1 root  wheel   0xa5 Jan  7 15:20 /dev/dsp0.vp0
crw-rw-rw-  1 root  wheel   0xa6 Jan  7 15:26 /dev/dsp0.vp1
crw-rw-rw-  1 root  wheel   0xa8 Jan  7 15:21 /dev/dsp1.vp0
crw-rw-rw-  1 root  wheel   0xa9 Jan  7 15:21 /dev/dsp2.vp0
crw-rw-rw-  1 root  wheel   0x94 Jan  7 15:22 /dev/dsp3.vp0
```

I only wonder why /dev/dsp is not what RtAudio finds as default device:
```
ls -l /dev/dsp
crw-rw-rw-  1 root  wheel  0x96 Jan  7 15:34 /dev/dsp
```
Once I'll figure out what's wrong/special about this case, I'll get back to you!

**Comment by radarsat1** [comment]
Hi, did you ever figure out a suggestion for how to detect the OSS device?

as to your question, I'm fine with forcing FreeBSD users to use the LINUX_OSS tag for now, until we simply make it more general, distasteful as that might be.  (Eventually, I don't think it should specify the operating system at all, but just the audio API.  However, it could possibly break software using RtAudio to change this.)

**Comment by mekanix** [comment]
To be honest, I found only dumb solutions: use /dev/dsp directly. On FreeBSD devd will create it for every open call. The weird thing is that default device returned by mixer doesn't use it (weird, I have to investigate this). Anyway, once I have something meaningful, I'll write here. In the mean time, is there a mailing list or chat for discussing ideas?

**Comment by radarsat1** [comment]
Ah I see, sounds like some kind of compatibility layer.

**Comment by radarsat1** [comment]
Did you ever figure this out?

**Comment by mekanix** [comment]
No I didn't. I have no idea how to make mixer report /dev/dsp which is the device I actually need, so I started using OSS API directly.

**Comment by radarsat1** [comment]
Hm, ok weird.  Well, maybe there is a bug here but unless someone can work on it I'll keep this closed for now.  Feel free to re-open if needed.  Thanks for reporting it!
