### ISSUE TITLE
Is there any limitation while running RtAudio on a separated thread? ASIO doesn't seem to work

### ISSUE THREAD

**Issue by sinosoidal** [thestk/rtaudio#125]
I'm was trying run RtAudio on a different thread to be able to probe devices without blocking the UI. However, it seems that RtAudio is unable to work with ASIO devices under this conditions as all drivers report **RtApiAsio::getDeviceInfo: unable to load driver**. This doesn't happen with WASAPI though. 

I'm using Qt and I'm creating a class that extends QObject and has RtAudio as private member. I'm then creating it without parent to then move it to a QThread.

**Comment by radarsat1** [comment]
Not really sure.  Is the member a pointer or an instance?  i.e,. are you creating the object in the new thread or is it created in the main thread and then ownership transferred? I recommend checking RtAudio.cpp to see if it's doing anything weird, but I'm not aware of any threading related issues.

**Comment by sinosoidal** [comment]
You have just made me realize that I’m creating the RtAudio object in the constructor, prior to thread start. Maybe that’s the problem. I will try and let you know the outcome. Thx!

--
Nuno Santos

No dia 14/01/2018, às 17:47, Stephen Sinclair <notifications@github.com> escreveu:

**Comment by radarsat1** [comment]
Could definitely be related, report back ;)

**Comment by sinosoidal** [comment]
That was the problem indeed! Thanks for your insight. I will now close this issue as it is invalid.

**Comment by radarsat1** [comment]
Glad you figured it out.  I've made this mistake before, which is basically that RtAudio does some "too complicated" things in the constructor.  To be honest though I'm not sure why initializing the device in a different thread causes problems, unless there are just some race conditions that haven't been identified.
