### ISSUE TITLE
can't specify jack server name

### ISSUE THREAD

**Issue by belm0** [thestk/rtaudio#127]
Since the jackd server can only run at a single rate, it's sometimes necessary to run separate services for e.g. playback and capture.  The rtaudio API doesn't expose the setting needed to specify the jackd server.

A blunt workaround is to use the JACK_DEFAULT_SERVER environment variable of the jackd library implementations.

**Comment by tay10r** [comment]
@belm0 do you think #97 is relevant to this? I closed it because it didn't seem like it they were going to try and support it.

**Comment by radarsat1** [comment]
As I mentioned in #97, I do think adding the ability to specify a port name in StreamParameters might be useful.  I just haven't seen a good PR or suggestion for it yet, and haven't taken the time to work on it myself.

**Comment by radarsat1** [comment]
As to this bug, what does running two separate services have to do with the jackd rate?  You mean you would run jackd once for playback and a different jackd at a different rate for capture?  I wasn't aware this was even possible, or maybe I misinterpret.

**Comment by tay10r** [comment]
@radarsat1 This is my suggestion.

Don't encapsulate the entire API in the `RtAudio` class. Allow the caller to declare each API class directly and have more support for tuning the APIs as they would want to. For example, what if I wanted to modify the period count, period size, or software parameters used in the ALSA library? I'd be out of luck with RtAudio. If designed the library for APIs to be declared directly, you'd make it more semantically correct.

The only thing the base class really needs to look like is this:

```c++
class RtApi {
public:
  virtual ~RtApi() { }
  virtual void closeStream() = 0;
  virtual void setCallback(RtAudioCallback callback) = 0;
  virtual void startStream() = 0;
  virtual void stopStream() = 0;
  virtual void abortStream() = 0;
  virtual bool isRunning() const = 0;
};
```

Don't declare a `StreamParameters` and `StreamOptions` class, allow the API to take care of this. For example, an ALSA API class.

```c++
class RtApiAlsa : public RtApi {
  snd_hw_params_t *hw_params;
  snd_sw_params_t *sw_params;
  // more ALSA members go here
public:
  RtApiAlsa();
  ~RtApiAlsa();
  void setStartThreshold(unsigned int threshold);
  void setPeriodSize(unsigned int periodSize);
  void setPeriodCount(unsigned int periodCount);
  // base methods go here
};
```

For JACK:

```c++
class RtApiJack : public RtApi {
  // jack members
public:
  ~RtApiJack();
  void setPortName(const char *name);
};
```
For a behavior similar to the current `RtAudio` class.

```c++
class RtApiGeneric : public RtApi {
  // The platform specific API is guessed here,
  // or chosen through an enumeration value.
  RtApi *api;
public:
  // generic stream functions go here.
};
```

For callers that use the API specific classes, they can still cast to the base class when they need to use the class generically.

**Comment by radarsat1** [comment]
Then callers would have to know which API they are supporting, which defeats the purpose of RtAudio.  For very complex stuff it might make sense, but since we are literally talking about adding a string ot a struct (one-line change in the header) I think your idea is overkill.  Many parameters such as period size etc might be usefully shared between back-ends, so it would be too bad to make the user detect the backend and specify multiple times the information in a special struct for every supported backend.

**Comment by tay10r** [comment]
Fair enough. I don't think it's overkill, but I can only pitch an idea so many times. Thanks the feedback!

**Comment by belm0** [comment]
Yes it's possible to run multiple jackd servers (under the same user).  Working around jackd's inability to have separate playback and capture rates is one use case.

I've given up on jackd for this and a few other reasons though, so not blocked on this enhancement at all.

**Comment by garyscavone** [comment]
Stale ... closing.
