### ISSUE TITLE
OS X master volume

### ISSUE THREAD

**Issue by stellanhaglund** [thestk/rtaudio#132]
Hi i just started trying this library out.
Seems really cool, i tried the playsaw example and it worked fine but im not able to lower the volume with the normal mac volume controls.
I guess that need to be handled by me, but i cant find any information about that.
Do you have any idea how i would fix this?

**Comment by radarsat1** [comment]
Hi, no one answered because I think no one knows the answer.. it sounds really weird.  did you ever solve it?

**Comment by cmaughan** [comment]
I have the same problem here; the master volume control on the mac is not letting me adjust the output from RtAudio
