### ISSUE TITLE
RTAUDIO_SCHEDULE_REALTIME for Pulse?

### ISSUE THREAD

**Issue by terminator356** [thestk/rtaudio#133]
Hello, I noticed the Pulse code does not seem to have any realtime support.
Is it sensible to add support to the code, and any plans to do so?
Otherwise, is it OK if **we** block or wait in the callback? Even for 'short' amounts of time?
I found that the callback did not seem to be blocking or protecting variables, it allowed
 other threads to interrupt it quite soon into it.
Our code relies on realtime with our other driver support such as our native Jack driver
 (Jack runs realtime), and our own dummy audio driver (a realtime thread).
So we recently added an RtAudio driver, to broaden our reach (for Pulse and ALSA audio).
Although modern common 'low-latency' is not as iron-clad guaranteed as 'hard-realtime', 
 we've done mostly OK with our code for years, given it's worth the anti-lockup trade-off.

Thanks.
Tim, the Linux MusE sequencer project.

**Comment by radarsat1** [comment]
Hi, cool that you're looking at RtAudio for MusE.   Whether it is ok to block the callback is up to the backend I suppose but in general it's an undesirable thing to do.  Not sure if that answers your question.

As for real-time, I don't have time/plans to work on this, but if you want to add support for RTAUDIO_SCHEDULE_REALTIME I'll gladly take a look at a contribution.  Perhaps it would be as simple as copying the priority-setting code from RtApiAlsa to where `pthread_create` is called in RtApiPulse::probeDeviceOpen.

I'm not quite sure from your description exactly what the question is so perhaps you could elaborate on whether you are willing to look at the quality of real-time support in RtAudio.

Cheers!

**Comment by garyscavone** [comment]
The Pulse support in RtAudio has been fairly minimal. It was contributed by a user and has never been extensively investigated by myself or others to bring it up to what I might consider "full" support. The ALSA support, on the other hand, is (or at least was) robust and includes "realtime" functionality that was tested and verified.

**Comment by radarsat1** [comment]
That pointer flipping sounds like a pretty usual technique.  As a generalization, you might also just try a kind of FIFO queue of your CriticialVariables data structure (or pointers to) and just call it "AudioParameters" or something.  That way you can just fill out a structure, put it on the queue, update the write location and forget.  Have one FIFO for each direction if needed.  You can do this in a non-blocking manner with no mutexes.

This only works for single-reader/single-writer, in the multiple-writers case you'll need something more careful.t

**Comment by terminator356** [comment]
Howdy. I fixed the observed problems in MusE when realtime is not available.

I also created an RtAudio pull request for realtime fixes.
It'd be much appreciated if you could merge that. I hope you may have confidence in me,
 I've been with MusE 10 years, and it uses much the same realtime coding as RtAudio.
See the pull request comments. I've added a ChangeLog file, changes can be kept in one place.

I fixed the ALSA realtime support - attributes are once again all set in probeDeviceOpen().
I believe your problem may have been that it was missing a call to:
pthread_attr_setinheritsched(&attr, PTHREAD_EXPLICIT_SCHED);
And the order in which pthread_attr_setschedpolicy and pthread_attr_setschedparam
are called is important, this was fixed in the Pulse and OSS drivers, but I noticed
that the order was correct in your original old ALSA code, so the issue therefore 
must have been that missing EXPLICIT setting.

Tested and verified with MusE, with and without realtime support enabled on the system.

Note: I read that the OSS support hasn't been tested in a while and may be dropped.
AFAIK OSS is the only option on BSD. Consider keeping it.
I have modified the OSS support as well, for realtime fixes.
It's untested but should work.

Giver 'er a whirl, please. Thanks.
Tim.

**Comment by radarsat1** [comment]
#134 was merged.
