### ISSUE TITLE
stream_.lastTickTimestamp too old

### ISSUE THREAD

**Issue by sonoro1234** [thestk/rtaudio#144]
If getStreamTime is called after startStream but when tickStreamTime is still not called by the callback ,lastTickTimestamp is too old. (so streamtime jumps widly for a while)
I think that startStream should update lastTickTimestamp also:

Just tried above idea with asio and works as expected.
To do a PR, the easiest way would be to modify RtAudio::startStream by adding
```
#if defined( HAVE_GETTIMEOFDAY )
  gettimeofday( &stream_.lastTickTimestamp, NULL );
#endif
```
but stream_ is not a member of RtAudio.

Instead of modifing each RtApi specialization of startStream perhaps all could be reworked: create RtApi:startStreamPre which would call gettimeofday and after RtApiSpecialization:startStream
and then call it from RtAudio:
```
RtApi::startStreamPre(void) {
    #if defined( HAVE_GETTIMEOFDAY )
      gettimeofday( &stream_.lastTickTimestamp, NULL );
    #endif
    rtapi_->startStream();
}
inline void RtAudio :: startStream( void ) { return rtapi_->startStreamPre(); }
```
@garyscavone what do you think about that?
@radarsat1

**Comment by radarsat1** [comment]
What about calling `setStreamTime(0.0)` at the beginning of startStream()?
Can you try this?

```
diff --git a/RtAudio.h b/RtAudio.h
index 82c3f64..0a19915 100644
--- a/RtAudio.h
+++ b/RtAudio.h
@@ -870,7 +870,7 @@ inline RtAudio::DeviceInfo RtAudio :: getDeviceInfo( unsigned int device ) { ret
 inline unsigned int RtAudio :: getDefaultInputDevice( void ) { return rtapi_->getDefaultInputDevice(); }
 inline unsigned int RtAudio :: getDefaultOutputDevice( void ) { return rtapi_->getDefaultOutputDevice(); }
 inline void RtAudio :: closeStream( void ) { return rtapi_->closeStream(); }
-inline void RtAudio :: startStream( void ) { return rtapi_->startStream(); }
+inline void RtAudio :: startStream( void ) { setStreamTime(0.0); return rtapi_->startStream(); }
 inline void RtAudio :: stopStream( void )  { return rtapi_->stopStream(); }
 inline void RtAudio :: abortStream( void ) { return rtapi_->abortStream(); }
 inline bool RtAudio :: isStreamOpen( void ) const { return rtapi_->isStreamOpen(); }
```

**Comment by sonoro1234** [comment]
I use setStreamTime(34) before startStream to set the position from which I would like playing to begin (to start in second 34 of the file I am playing). This way setStreamTime(34) would be lost when doing startStream (with setStreamTime(0))

**Comment by radarsat1** [comment]
@sonoro1234 I prefer customizing it per backend because won't Windows implementations need to use a different function call?  It seems to me lastTickTimestamp is only useful on non-Windows platforms right now.

In any case I really don't like that getStreamTime seems to do something different depending on the platform.  There seems to be no way right now to get the stream time in samples independent from the system clock if I'm reading things correctly.
