### ISSUE TITLE
Using Modern C++

### ISSUE THREAD

**Issue by ghost** [thestk/rtaudio#145]
When is `RtAudio` going to end supporting pre-c++11 standards? The last C++ standard before c++11 was made fifteen years ago, I think it's safe to say we can move on. There are several advantages in using the newer C++ standards, a lot of which enable better optimization and clearer syntax. For example, `noexcept`, `final`, `override`, `enum class`.

The keyword `noexcept` can be helpful for performance reasons, such as in the audio processing loop, to tell the compiler that it does not need to pass deconstructors to the exception handling frame.

The `final` keyword helps the compiler optimize by "de-virtualizing" the functions.

The `override` functions can be helpful in determining whether or not a function actually overrides its base class function. This is nice because it prevents extremely subtle bugs when the base class function and the derived class function end up changing slightly. It's an extremely helpful keyword.

The `enum class` helps in scoping the enumeration keywords. For example:

```c++
enum RtApi {
  ALSA
};
/// Used like this:
/// RtApi api = ALSA;
```

Can become:

```c++
enum class RtApi {
  ALSA
};
/// Used like this:
/// RtApi api = RtApi::ALSA;
```

Using `enum class` also prevents arbitrary values from getting mixed up in enumeration values. Which makes it safer.

RtAudio should be evolving with the C++ standard, not falling behind. There is currently another version of the C++ standard being worked on, with even more useful features. I suggest supporting at least `c++11` and having a plan on migrating to `c++14`, `c++17` and the later versions.

Using new C++ standards will require updates to the Travis build, but it's pretty commonly done by C++ projects using Travis. I've made several Travis configuration files for using C++11 and above.

I'll contribute the code if I get the go ahead.

**Comment by radarsat1** [comment]
It would be nice to collect up proposed C++11-related changes in a few PRs.  Imho it might be cool to start integrating them after the next release, but let's see.

**Comment by radarsat1** [comment]
Cool yeah I had been planning to start up an 'experimental' branch soon, maybe now is the time.  It would be nice to synchronize such changes with RtMidi.  I have some ideas for how the callback API might change with C++11 so maybe give me a little time to work on that before proposing anything, but the "trivial" things you mention here are welcome in an experimental context.  Thanks!

**Comment by garyscavone** [comment]
I have no problem with c++11 changes if they don’t force the user to do anything special. Is c++11 standard enough now that we can simply invoke g++ without any special flags and it will compile?

—gary

**Comment by tay10r** [comment]
@garyscavone I believe the default standard, since GCC 6.1 is c++14 (according to [this](https://gcc.gnu.org/projects/cxx-status.html#cxx14)).

The c++14 standard is also the default for Visual Studio 2017.

The user doesn't have to do anything special to use c++11 or c++14. I believe most of the small changes I would write are c++11. So I suggestion would be to use c++11 and eventually move to c++14, and so forth.

This will break Travis builds that use RtAudio without updating the default C++ compiler in Travis (that is, if they update their RtAudio files.) However, a lot of C++ projects that use Travis already have this update in place, so I don't think it will be much of an issue. This is mainly a Travis issue being severely out of date, see [this issue](https://github.com/travis-ci/travis-ci/issues/6300).

**Comment by tay10r** [comment]
@radarsat1 and @garyscavone I have a branch on my fork for c++11 support, you can see it [here](https://github.com/tay10r/rtaudio/tree/cxx11).

**Comment by radarsat1** [comment]
@garyscavone yes I think it is now safe.. gcc has defaulted to c++11 enabled for the last few versions, and clang and microsoft compilers support it too.  At least experimenting in a branch for now can't hurt I think.  I would be for moving to C++11 after doing a release (still some wip to finish up.)

Thanks @tay10r i'll merge or cherry-pick from your branch when I get into this..

**Comment by autoantwort** [comment]
The people already assume that this project will use c++11 as you can see here:
8850bb6fb8fa059c9cc506be4794d39b9a080492
bfeeb815b902239f7dbeb38ef7ecdf4838d3466b

**Comment by tay10r** [comment]
It's surprising to see "fixes" for `nullptr`. I get it that some projects have very old legacy code, but they're not suppose to drag other projects down with them!

**Comment by radarsat1** [comment]
> they're not suppose to drag other projects down with them

that's a little dramatic.  it's just ensuring the project compiles with `-std=c++98` and doesn't affect projects that use RtAudio in the least, which can perfectly be C++11.

**Comment by nyanpasu64** [comment]
When writing pull requests, should I use nullptr or NULL for new code? I see a few instances of nullptr in master, but mostly NULL.

**Comment by tay10r** [comment]
Should this issue be closed now? I think the branch I made these changes for has probably gone stale. It seems like the overall consensus is that C++11 can be used within the implementation, but not in the header file. Is this right?

**Comment by radarsat1** [comment]
Closing as C++11 is supported now.
