### ISSUE TITLE
Using Multiple Files

### ISSUE THREAD

**Issue by tay10r** [thestk/rtaudio#146]
It is very nice having a single `RtAudio.cpp` and `RtAudio.hpp` for people who use this project. I've seen this done a lot and can attest to its usefulness on platforms that don't have package managers (looking at you, Windows.) The way I see project maintainers do this is by having a script that combines all the smaller files into one. Here's some examples:

- [nuklear](https://github.com/vurtun/nuklear/tree/master/src)
- [duktape](https://github.com/svaarala/duktape)
- [sqlite](https://github.com/smparkes/sqlite)

This way, the project is easy to maintain because the files are organized and easy to navigate, while still having the easy of use for Windows users. RtAudio should do it this way because the current implementation is hard to navigate.

**Comment by radarsat1** [comment]
Splitting up RtAudio.cpp has already been discussed here many times, please check some old issues e.g. #52, #56.

**Comment by tay10r** [comment]
Ah, alright. I should've checked first. I still think you're driving away contributors by doing it this way, but I suppose the decision has already been made.
