### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [thestk/rtaudio#149]
I would like to point out that an identifier like “[`__RTAUDIO_H`](https://github.com/thestk/rtaudio/blob/004d9c461d418c0e4e61da14fd93000aa26f33a8/RtAudio.h#L45 "Update candidate")” [does eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by garyscavone** [comment]
So RTAUDIO_H is better? That link didn't explicitly explain why underscores are non-conforming.

**Comment by elfring** [comment]
* Your suggestion would be [standard compliant](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?").
* How do you think about to append a kind of unique identifier to such an include guard?

**Comment by garyscavone** [comment]
RTAUDIO seems fairly unique to me. Anything extra would be superfluous.

But it seems that our preprocessor definitions are also non-conforming (__MACOSX_CORE__, __WINDOWS_DS__, __RTAUDIO_DEBUG__, ...)?

**Comment by garyscavone** [comment]
Stale ... closing.
