### ISSUE TITLE
saveDeviceInfo in ASIO

### ISSUE THREAD

**Issue by sonoro1234** [thestk/rtaudio#15]
Some ASIO devices are not well behaved and getting their info is a long task.
So getting the info for all ASIO devices when doing openStream on ASIO is too lasting operation.
I would prefer to get an error if I try to get devices info when one of them is already open.

thanks
victor

**Comment by garyscavone** [comment]
If we changed this behaviour, it would be a special case for ASIO only. And the problem seems more related to underlying device driver issues, so I'm going to close this.
