### ISSUE TITLE
getDeviceInfo() returns information on a disconnected USB DAC

### ISSUE THREAD

**Issue by turgu1** [thestk/rtaudio#152]
Hello!

First thank for this wonderful library!!

Context: Raspbian (last release), librtaudio 5.0.0, ALSA 1.1.3-5

RtAudio was compiled on the platform using the following options:

```
/configure --prefix=/usr --with-alsa --includedir=/usr/include
```

Once the rtAudio instance is running, I'm using getDeviceCount() and getDeviceInfo() in a loop every 5 seconds to discover if the device was unplugged to automate the rediscovery when it will be back connected.

When I disconnect the audio USB DAC from the computer, getDeviceCount() get updated properly, but getDeviceInfo() still returns the information from the previously opened port (the USB DAC) when devNbr is at index 2 (This was the index that the port was using when it was opened). I can confirm the device is no longer there with `lsusb` Here is the code used to discover if the device was disconnected. I'm using the same kind of logic with rtMidi successfully.

```
  RtAudio::DeviceInfo devInfo;
  bool found = false;
  int devNbr;
  int devCount = dac.getDeviceCount();

  for (devNbr = 0; (devNbr < devCount) && !found; devNbr++) {
    devInfo = dac.getDeviceInfo(devNbr);
    found   = devInfo.probed && (devInfo.name.compare(completeAudioPortName) == 0);
  }

  if (!found) {
       .... never came here ....
  }
```

Any help would be welcome!!

Cheers!

Guy

**Comment by turgu1** [comment]
Well, looking at the RtAudio code in RtAudio.cpp after the `foundDevice:` label (line number 6880), it seems to me that the code, relying on the device index number, thinks that it is related to the current opened stream but it is not, considering that when the USB DAC was disconnected, the indexes have been shuffled and the current index no longer represents the open stream. Because it thinks that this is the opened stream, it returns the cached information.

I understand that a "device" in RtAudio is related to an index in the audio device list. It would be a big change to have the code rely on something else than the device index as an identification of the current stream... I'm screwed!!

Please let me know if my understanding is correct.

Cheers!

Guy

**Comment by garyscavone** [comment]
The recent device selection code likely fixes this (if there was a bug).
