### ISSUE TITLE
Getting host time at audio callback

### ISSUE THREAD

**Issue by sinosoidal** [thestk/rtaudio#160]
Hi,

I'm trying to understand how can I get the host time on RtAudio callback. Ableton has developed Link which relies strongly on host time. They provide several examples on how to do this on several platforms:

https://github.com/Ableton/link/tree/master/examples/linkaudio

I see that RtAudio provides a getStreamTime but it does't seem useful at all in this context:

`Returns the number of elapsed seconds since the stream was started.`

For instance, on CodeAudio example, the AudioTimeStamp* inTimeStamp is used:

```
const auto bufferBeginAtOutput = engine->mLink.clock().ticksToMicros(inTimeStamp->mHostTime) + engine->mOutputLatency;
```

The Windows example is a bit more extensive but it is quite similar to RtAudio tickStreamTime:

```
    // Get the amount of padding, which basically is the amount of data in the driver's
    // ring buffer that is filled with unread data. Thus, subtracting this amount from
    // the buffer size gives the effective buffer size, which is the amount of frames
    // that can be safely written to the driver.
    UINT32 paddingFrames;
    HRESULT result = mAudioClient->GetCurrentPadding(&paddingFrames);
    if (FAILED(result))
    {
      fatalError(result, "Could not get number of padding frames");
    }

    const UINT32 numSamples = bufferSize() - paddingFrames;

    BYTE* buffer;
    result = mRenderClient->GetBuffer(numSamples, &buffer);
    if (FAILED(result))
    {
      fatalError(result, "Could not get render client buffer (in callback)");
    }

    const double sampleRate = static_cast<double>(mStreamFormat->nSamplesPerSec);
    using namespace std::chrono;
    const auto bufferDuration =
      duration_cast<microseconds>(duration<double>{numSamples / sampleRate});
```

vs

```
void RtApi :: tickStreamTime( void )
{
  // Subclasses that do not provide their own implementation of
  // getStreamTime should call this function once per buffer I/O to
  // provide basic stream time support.

  stream_.streamTime += ( stream_.bufferSize * 1.0 / stream_.sampleRate );

#if defined( HAVE_GETTIMEOFDAY )
  gettimeofday( &stream_.lastTickTimestamp, NULL );
#endif
}
```

Is there any relation between RtAudio's getStreamTime and the implementations that are present in CoreAudio and Wasapi Link platform examples?

Thanks!

**Comment by radarsat1** [comment]
I don't really follow to be honest. What do you mean by host time and why is stream time not useful?  As far as I understand it is just the time in seconds calculated by the number of samples processed so far.  What is host time and how is it different?

**Comment by sinosoidal** [comment]
Have you ever heard about Ableton Link?

https://github.com/Ableton/link/blob/master/README.md

I'm trying to integrate Link but it will not work correctly without host time integration.

**Comment by radarsat1** [comment]
So host time is the estimated time at which the system will actually play the buffer currently being processed?  It's always a future time then, is that right? Yes, that sounds like something that could be useful to put in the RtAudio interface.  But that document also says you can just get the system time and filter it.

Ideally this is something that would go in some kind of RtAudioStreamState data structure that is passed to the callback, but such such thing exists in RtAudio.  I don't want to change the callback prototype if at all possible, for backwards compatibility reasons.

**Comment by sinosoidal** [comment]
Yes, and it seems that Mac OSX and iOS are the only operating systems that provide that information with accuracy. In other systems in needs to be estimated. 

What exactly do you mean with this: `but such such thing exists in RtAudio`?

If you don't want to change the callback, what are the options then?

**Comment by radarsat1** [comment]
Ah, typo sorry.  "but no such thing"

**Comment by radarsat1** [comment]
> If you don't want to change the callback, what are the options then?

Well you could try modifying the callback experimentally for now, or pass something in by userData.  Like add a function to get this information and call it by passing a pointer through userData.

**Comment by sonoro1234** [comment]
This is the same goal that HAVE_GETTIMEOFDAY in RtAudio tries to achieve

**Comment by garyscavone** [comment]
Stale ... closing.
