### ISSUE TITLE
is it possible to record the output device with rtaudio?

### ISSUE THREAD

**Issue by MatzeOGH** [thestk/rtaudio#161]
Hi,
I want to record the sound from an output device.
Is that doable with rtaudio?

**Comment by MarcusTomlinson** [comment]
On which platform?

**Comment by MatzeOGH** [comment]
I was trying it with Windows WASAPI but you get following error message:
RtApiWasapi::probeDeviceOpen: Render device selected as input device.
I was playing around with the duplex sample from the website

**Comment by MarcusTomlinson** [comment]
> I was trying it with Windows WASAPI but you get following error message:
> RtApiWasapi::probeDeviceOpen: Render device selected as input device.
> I was playing around with the duplex sample from the website

Right, as I said, it's not currently supported. Good thing you're using WASAPI then, I'll try push a PR tonight for you to try out.

**Comment by MatzeOGH** [comment]
Thank you so much. That's awesome.

My use case is that I want to record the default output device and send the recoding to ffmpeg afterwards. Do you think that this will be possible afterwards?

Thank you so much anyway

**Comment by MarcusTomlinson** [comment]
> Thank you so much. That's awesome.
> 
> My use case is that I want to record the default output device and send the recoding to ffmpeg afterwards. Do you think that this will be possible afterwards?
> 
> Thank you so much anyway

This is definitely possible yes. Of course, what you do with the stream from RtAudio onwards is on you.

On that note, you may be interested in using a library like [DSPatch](https://github.com/MarcusTomlinson/DSPatch) to handle all your data-flow.

You can find the ready-made RtAudio component (called "AudioDevice") [here](https://github.com/MarcusTomlinson/DSPatchables).

**Comment by MatzeOGH** [comment]
I'll definitely look into DSPatch 
Thanks

**Comment by MarcusTomlinson** [comment]
@MatzeOGH here you go: https://github.com/thestk/rtaudio/pull/162

I've also updated the [AudioDevice](https://github.com/MarcusTomlinson/DSPatchables/tree/master/Components/AudioDevice) component (if you're interested in going the DSPatch route)

**Comment by MatzeOGH** [comment]
Thank you.
I tried your pull request pull request and it is definitely working.
I haven't gotten around to try DSPatch yet.

**Comment by MarcusTomlinson** [comment]
@MatzeOGH Here's the fix you needed to allow loopback without having to define output parameters: https://github.com/thestk/rtaudio/pull/165

**Comment by autoantwort** [comment]
How I have to use the API to enable loopback recording? Currently my code looks the following:
```c++
    RtAudio::StreamParameters isp;
    isp.deviceId = rtAudio.getDefaultOutputDevice();
    isp.nChannels = 2;
    isp.firstChannel = 0;
    rtAudio.openStream(nullptr, &isp, RTAUDIO_FLOAT32, samplesPerSecond, &samplesPerFrame, rtAudioCallback, nullptr, nullptr, nullptr);
    rtAudio.startStream();
```
But in my callback:
```c++
int rtAudioCallback(void *outputBuffer, void *inputBuffer, unsigned int nFrames, double /*streamTime*/, RtAudioStreamStatus /*status*/, void * /*userData*/) {
    std::cout << outputBuffer << ' ' << ((float *)outputBuffer)[0] << ' ' << inputBuffer << ' ' << ((float *)outputBuffer)[0] << ' ' << nFrames << std::endl;
    return false;
}
```
it prints `0x1bb4b6b0 0 0x20738bf0 0 441` all the time. So the buffers contains only zeros.

**Comment by MarcusTomlinson** [comment]
`... inputBuffer << ' ' << ((float *)outputBuffer)[0] ...`

should be

`... inputBuffer << ' ' << ((float *)inputBuffer)[0] ...`

**Comment by autoantwort** [comment]
Oh thanks! I hate these copy paste errors. 
I have another question: Why did I get an output buffer when I only request a buffer for recording?

**Comment by MarcusTomlinson** [comment]
> I have another question: Why did I get an output buffer when I only request a buffer for recording?

Good question. I may be instantiating one unnecessarily.

**Comment by autoantwort** [comment]
I think it done in [here](https://github.com/thestk/rtaudio/blob/master/RtAudio.cpp#L4781), but I dont know why.

**Comment by Huddie** [comment]
@MarcusTomlinson Was this ever added to Rtaudio cross platforms? I'd love this on macOS

**Comment by MarcusTomlinson** [comment]
> @MarcusTomlinson Was this ever added to Rtaudio cross platforms? I'd love this on macOS

It was not. There were no plans to add this to other platforms as far as I know.
