### ISSUE TITLE
WASAPI no sound with FLOAT32

### ISSUE THREAD

**Issue by sonoro1234** [thestk/rtaudio#170]
I am facing a very extrange issue here:

I have a standard lua binding of rtaudio in https://github.com/sonoro1234/luaRtAudio. The wasapi driver works correctly there. Buffers were FLOAT64

I am doing now a LuaJIT binding using the C interface provided by the same module (with #169 applied). ASIO and DS drivers work correctly but WASAPI driver produces no sound althought the callback is running (tested printing things) and the shared module is the same used in luaRtAudio.

I am stuck. Any suggestion?

Perhaps being a WASAPI issue @MarcusTomlinson has any clue?

Thankyou
victor bombi

**Comment by sonoro1234** [comment]
Aditional test

If I trig an error calling start_stream twice the warning is posted in all drivers. ASIO and DS let me stop_stream afterwards but WASAPI gives me a crash and DRIVER error when calling stop_stream.

If I set an error_callback that does not use throw, ASIO and DS behave as before but WASAPI gets hanged after stop_stream but without crash neither DRIVER error.

**Comment by sonoro1234** [comment]
Just compiled playsaw.cpp but with the C interface and it works on WASAPI so it is only failing in the LuaJIT binding, but I could make LuaJIT to work with SDL2 and wasapi in https://github.com/sonoro1234/LuaJIT-SDL2 so I am still stuck.

**Comment by radarsat1** [comment]
Is there any weird threading going on inside the LuaJIT interpreter? Maybe try mutexes around any accesses to RtAudio just to see if it helps.

**Comment by sonoro1234** [comment]
@radarsat1  dont be confused by my first two messages , just read the third: playsaw.cpp fails with WASAPI and FLOAT32

**Comment by MarcusTomlinson** [comment]
I'll take a look.

**Comment by MarcusTomlinson** [comment]
@sonoro1234 I can't seem to reproduce the issue you're describing (with playsaw.cpp).

Tried compiling with MinGW 32-bit and 64-bit, tried different channel counts and sample rates. In every variation FLOAT32 produces audio. In fact, all formats work for me. I am on Windows 10 though.

Just checking, you've either un-commented, or inserted exactly the following in playsaw.cpp right?

```
typedef float MY_TYPE;
#define FORMAT RTAUDIO_FLOAT32
#define SCALE  1.0

```

**Comment by sonoro1234** [comment]
Did you compiled with the three window APIS and then selected a api by `RtAudio dac = RtAudio(RtAudio::WINDOWS_WASAPI);` ?

**Comment by MarcusTomlinson** [comment]
Ah, perhaps you forgot to mention you've defined USE_INTERLEAVED? Just tried this and no audio. Looking into it.

**Comment by sonoro1234** [comment]
Yes, sorry, forgot that.
 It is the default libsndfile uses reading sounfiles.

**Comment by MarcusTomlinson** [comment]
Doh. Silly mistake. Thanks for your help.

This should be fixed now in: #170

**Comment by MarcusTomlinson** [comment]
Oops, that was actually not the right way to fix this issue. This is: #175

**Comment by sonoro1234** [comment]
I getting sound with PR174 but I guess PR175 should be better!!

**Comment by radarsat1** [comment]
Please close if this is fixed.
