### ISSUE TITLE
C interface error management proposal

### ISSUE THREAD

**Issue by sonoro1234** [thestk/rtaudio#176]
The actual pattern is:

```cpp
int rtaudio_start_stream(rtaudio_t audio) {
  try {
    audio->has_error = 0;
    audio->audio->startStream();
  } catch (RtAudioError &err) {
    audio->has_error = 1;
    strncpy(audio->errmsg, err.what(), sizeof(audio->errmsg) - 1);
  }
  return 0;
}
const char *rtaudio_error(rtaudio_t audio) {
  if (audio->has_error) {
    return audio->errmsg;
  }
  return NULL;
}
```
So the way the application has to know if error happened is to pull audio->errmsg with rtaudio_error and getting not null string.(after every used rtaudio C function) I find it quite cumberstone.
Beasides the errorCalback mechanism is not used and a NULL is passed to openStream (could be reworked but it has the limitation that does not work until the stream is open (not problem in C++ because we still have try catch but a problem in other languajes))

My proposal would be to have a function for setting an error handling callback at the module level (could be setted before rtaudio_create and rtaudio_open_stream) that would receive error type and error message and would let to just print message or trig an error in the application (call error in LuaJIT for example) this callback would be invoked from every catch in rtaudio_c.cpp (even rtaudio_create)

resulting in
```cpp
int rtaudio_start_stream(rtaudio_t audio) {
  try {
    audio->has_error = 0;
    audio->audio->startStream();
  } catch (RtAudioError &err) {
    audio->has_error = 1;
    strncpy(audio->errmsg, err.what(), sizeof(audio->errmsg) - 1);
    if(moduleErrorCallback){
        moduleErrorCallback(err.type, err.what());
    }
  }
  return 0;
}
```

I can implement it if there is agreement with the proposal.

**Comment by radarsat1** [comment]
It makes some sense and it wouldn't need to be global, you could register it in the `struct rtaudio` although then it would have to be passed to `rtaudio_create`.  However, I'm not sure it simplifies everything for you.  In the callback you would still need to set an error and check it in the cases where you expect to have serious errors.  Which could be pretty much everywhere.  (openStream, startStream, etc.)

How many calls do you have where you really do not want to check this error message but just do some standard 'print' instead?  Another solution could be to make yourself a RTAUDiO_CHECK macro that always checks the error status after a call to RtAudio_c, many C libraries do this kind of thing.

**Comment by garyscavone** [comment]
I don't think this is relevant now that we removed exceptions. If there is still an issue, please reopen with a proposed change.
