### ISSUE TITLE
WASAPI wrong streamTime in RtAudioCallback while recording

### ISSUE THREAD

**Issue by jwang0512** [thestk/rtaudio#182]
```
int CMainDlg::audioInOut(void *outputBuffer, void *inputBuffer, unsigned int nBufferFrames, double streamTime, RtAudioStreamStatus status, void *data)
{
	auto time_now = std::chrono::system_clock::now();
	auto duration_in_ms = std::chrono::duration_cast<std::chrono::milliseconds>(time_now.time_since_epoch());
	uint64_t tsx = duration_in_ms.count();
	char tmp[128];
	sprintf(tmp, "%lld --> %.6f  :  %d\n", tsx, streamTime, nBufferFrames);
	OutputDebugStringA(tmp);
        return 0;
}

```
OpenStream with parameter : RTAUDIO_SINT16 , 48000 , 1 channel , 1920 samples.
output logs as below:
1547808941021 --> 0.000000  :  1920
1547808941056 --> 0.240000  :  1920
1547808941095 --> 0.440000  :  1920
1547808941136 --> 0.640000  :  1920
1547808941176 --> 0.840000  :  1920
1547808941216 --> 1.040000  :  1920
1547808941256 --> 1.240000  :  1920
1547808941296 --> 1.440000  :  1920
1547808941335 --> 1.640000  :  1920
1547808941376 --> 1.840000  :  1920
1547808941416 --> 2.040000  :  1920

48000hz,1920 samples should be 40ms interval right?  seems the streamTime here is 200ms interval.

**Comment by MarcusTomlinson** [comment]
Hmm, another weird one... I just ran your test code on my machine with both MinGW and VC2017 compilers and I got correct intervals of 40ms:

1548592643844 --> 0.000000  :  1920
1548592643863 --> 0.040000  :  1920
1548592643903 --> 0.080000  :  1920
1548592643944 --> 0.120000  :  1920
1548592643983 --> 0.160000  :  1920
1548592644023 --> 0.200000  :  1920
1548592644063 --> 0.240000  :  1920
1548592644103 --> 0.280000  :  1920
1548592644143 --> 0.320000  :  1920
1548592644184 --> 0.360000  :  1920
1548592644223 --> 0.400000  :  1920
1548592644253 --> 0.440000  :  1920

I believe there were some streamTime related bugs fixed recently in RtAudio. Could you just make sure you have the latest from master and try again?

**Comment by jwang0512** [comment]
Hi, sorry for the late reply.
I tested it again today, with latest code. (MD5 RtAudio.cpp = d57d7d717ecc55b4db3b97af327b5279
)
but the streamTime still not correct.

1550224108817 --> 2.000000  :  1920
1550224108858 --> 2.200000  :  1920
1550224108897 --> 2.400000  :  1920
1550224108938 --> 2.600000  :  1920
1550224108978 --> 2.800000  :  1920
1550224109018 --> 3.000000  :  1920
1550224109058 --> 3.200000  :  1920
1550224109098 --> 3.400000  :  1920
1550224109138 --> 3.600000  :  1920
1550224109177 --> 3.800000  :  1920
1550224109228 --> 4.040000  :  1920
1550224109268 --> 4.240000  :  1920
1550224109307 --> 4.440000  :  1920
1550224109347 --> 4.640000  :  1920
1550224109387 --> 4.840000  :  1920
1550224109428 --> 5.040000  :  1920

Compiled with VC2017.  (with flag __WINDOWS_WASAPI__)

I noticed RtApi::tickStreamTime() executed 5 times before audioInOut get called. that's why streamTime not correct.

line 5185
`          callbackPulled = captureBuffer.pullBuffer( convBuffer,
                                                     samplesToPull * stream_.nDeviceChannels[INPUT],
                                                     stream_.deviceFormat[INPUT] );
`
callbackPulled does not always return true, in my case ,it returns false 4 times, and then return true.
that cause the RtApi::tickStreamTime() called 5 times and then audioInOut get called.

hope that helps.
Thanks.

**Comment by MarcusTomlinson** [comment]
That helps a lot @jwang0512, thanks. It's possible in my testing I tried playback instead of recording, or maybe a particular combination of in and out sample rate worked for me. I'll have another look.

**Comment by radarsat1** [comment]
Thanks for the report, does this only affect WASAPI?

**Comment by jwang0512** [comment]
> Thanks for the report, does this only affect WASAPI?

I am not sure if it only affect WASAPI. I will try ASIO later.（not sure if I can do that test, because I did not got an ASIO sound card yet.）

**Comment by jwang0512** [comment]
> From @jwang0512's comment about the behaviour of captureBuffer.pullBuffer(), it's likely to only be WASAPI. This is I think due to the way we're resampling through the ring buffers there. I'm sorry I haven't yet looked at this, will try again this weekend.

OK. Thanks. Let me know if you want any tests :)

**Comment by MarcusTomlinson** [comment]
Hi @jwang0512, would you please test #191 for me. I managed to reproduce the issue. Looks to be resolved now with that PR.

**Comment by jwang0512** [comment]
Hi @marcelofg55, I have tested #191 , it is fixed. and the streamTime now is also correct. Great :)
Thanks.
