### ISSUE TITLE
rtaudio doesn't build on windows using CMake and VS 2017

### ISSUE THREAD

**Issue by markusobi** [thestk/rtaudio#187]
I am using CMake and Visual Studio 2017 on Windows 10.
The following linker errors are shown when building target rtaudio:
>exports.def : error LNK2001: unresolved external symbol =
>D:/rtaudio/build/Debug/rtaudiod.lib : fatal error LNK1120: 1 unresolved externals
>Done building project "rtaudio.vcxproj" -- FAILED.

This is the commit that broke it: https://github.com/thestk/rtaudio/commit/9802c1285962f4bb187ee280a21908dc134083d0
The commit before that commit worked.

There isn't any other information shown. I don't know why the linker wants to find a symbol named `=`.
This is how I call cmake:
```bash
mkdir build
cd build
cmake -D CMAKE_INSTALL_PREFIX=./install ..
cmake --build . --target install
```

**Comment by sonoro1234** [comment]
this is my cmake
```
cmake  -G"MinGW Makefiles"  -DCMAKE_BUILD_TYPE=DebWithRelInfo -DRTAUDIO_API_DS=on -DCMAKE_INSTALL_PREFIX="./install" ..
```
`-G"Visual Studio 15 2017 Win64"` in your case?

**Comment by markusobi** [comment]
I've tried on a different windows machine with latest VS 2017 and latest cmake.
I get the same linker error, but also additional errors.
The root cause is, that some preprocessor defines are not propated correctly.
The test targets i.e. playsaw are not compiled with the defines from `${API_DEFS}`.
This expression is always false:
https://github.com/thestk/rtaudio/blob/master/tests/playsaw.cpp#L44

**Comment by sonoro1234** [comment]
got the same VC2017 32 bits
```
[100%] Linking CXX shared library rtaudio.dll
LINK Pass 1: command "C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1415~1.267\bin\Hostx86\x86\link.exe /no
logo @CMakeFiles\rtaudio.dir\objects1.rsp /out:rtaudio.dll /implib:rtaudio.lib /pdb:C:\luaGL\gitsources\BUILDS
\anima_build_nmake32\LuaJIT-rtaudio\rtaudio\rtaudio.pdb /dll /version:6.0 /machine:X86 /debug /INCREMENTAL /DE
F:CMakeFiles\rtaudio.dir\exports.def dsound.lib ksuser.lib mfplat.lib mfuuid.lib wmcodecdspuuid.lib winmm.lib
ole32.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.
lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\rtaudio.dir/intermediate.manifest CMakeFiles\rtaudio.dir/m
anifest.res" failed (exit code 1120) with the following output:
exports.def : error LNK2001: sÝmbolo externo = sin resolver
rtaudio.lib : fatal error LNK1120: 1 externos sin resolver
NMAKE : fatal error U1077: 'C:\cmake-3.13.0-rc1-win64-x64\bin\cmake.exe' : código devuelto '0xffffffff'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15
.26726\bin\HostX86\x86\nmake.exe"' : código devuelto '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15
.26726\bin\HostX86\x86\nmake.exe"' : código devuelto '0x2'
Stop.
```

**Comment by MarcusTomlinson** [comment]
Hi @markusobi, please could you give #190 a spin and let me know if your problem goes away.

**Comment by sonoro1234** [comment]
Linking succeds now. Still warnings.

**Comment by MarcusTomlinson** [comment]
Indeed there are still warnings, but those have been around for a long time to be fair. They're also the same regardless of API.

Perhaps if you feel strongly that all compiler warnings should be resolved, you could submit a separate ticket for that.

**Comment by markusobi** [comment]
@MarcusTomlinson It compiles on windows, but now `${API_DEFS}` is set globally for all targets which might cause problems.

I suggest using `#if defined(WIN32)` instead of `#if defined( __WINDOWS_ASIO__ ) || defined( __WINDOWS_DS__ ) || defined( __WINDOWS_WASAPI__ )`.

Another solution: Just use `<chrono>` and `<thread>` for the sleep function, but this would required C++11 for the test targets (i.e. `std::this_thread::sleep_for(std::chrono::milliseconds(100))`).

The linker doesn't complain anymore about missing symbol `=`, because it now doesn't export any symbols _at all_. That means the library will probably not work anymore when building as SHARED on windows.
I will investigate about the symbol `=` and try to find the root for this error.

**Comment by MarcusTomlinson** [comment]
Thanks @markusobi

**Comment by MarcusTomlinson** [comment]
Ok I agree with the `#if defined(WIN32)`, updated my PR with that change.

I don't see the point in using `WINDOWS_EXPORT_ALL_SYMBOLS` though when we have:

`#define RTAUDIO_DLL_PUBLIC __declspec(dllexport)`

I can perhaps see the use-case of using the .def file from a MinGW build to generate a MSVC .lib. How about we just limit `WINDOWS_EXPORT_ALL_SYMBOLS` to MinGW builds?

Proposed changes pushed to #190.

**Comment by radarsat1** [comment]
I just confirmed that I have same errors as @markusobi and that #190 fixes it.

Another thing I noticed, separate issue I guess, is that it produces rtaudiod.dll, even though I have CMAKE_BUILD_TYPE set to "Release".  Actually I think ideally it would produce a dll with a suffix of the ABI major version, something like rtaudio6.dll, although I would have thought CMake could take care of this automatically since it is provided with SOVERSION in the target properties.  Maybe it is just not a standard practice on Windows?

**Comment by radarsat1** [comment]
> Another thing I noticed, separate issue I guess, is that it produces rtaudiod.dll, even though I have CMAKE_BUILD_TYPE set to "Release".

Figured this out.  Even though CMAKE_BUILD_TYPE is set to Release, if I open the produced sln file, Visual Studio configuration is set to Debug.  So I assume the build command was also building Debug.  If I run this commend, there is no "d", it produces "rtaudio.dll":

    cmake --build . --target install --config Release

**Comment by markusobi** [comment]
> I don't see the point in using `WINDOWS_EXPORT_ALL_SYMBOLS` though when we have:
> 
> `#define RTAUDIO_DLL_PUBLIC __declspec(dllexport)`

My fault, I didn't know that the symbols where already explicitly exported.
 
> > Another thing I noticed, separate issue I guess, is that it produces rtaudiod.dll, even though I have CMAKE_BUILD_TYPE set to "Release".
> 
> Figured this out. Even though CMAKE_BUILD_TYPE is set to Release, if I open the produced sln file, Visual Studio configuration is set to Debug. So I assume the build command was also building Debug. If I run this command, there is no "d", it produces "rtaudio.dll":
> 
> ```
> cmake --build . --target install --config Release
> ```

When generating for a single configuration build system like MAKE, cmake wants the configuration at configure time.
so for make do:
```
cmake --DCMAKE_BUILD_TYPE=Release ..
cmake --build .
```
for multi configuration build system like Visual Studio (or is it MSBuild?) cmake will need the configuration at build time.
```
cmake ..
cmake --build . --config Release
```
https://cmake.org/cmake/help/v3.9/prop_gbl/GENERATOR_IS_MULTI_CONFIG.html
