### ISSUE TITLE
Update WASAPI compilation command in docs

### ISSUE THREAD

**Issue by ad8e** [thestk/rtaudio#189]
As described in https://github.com/thestk/rtaudio/issues/184, the compilation command at http://www.music.mcgill.ca/~gary/rtaudio/compiling.html should be instead `g++ -Wall -D__WINDOWS_WASAPI__ -Iinclude -o audioprobe audioprobe.cpp RtAudio.cpp -lole32 -lksuser -lmfplat -lmfuuid -lwmcodecdspuuid`

**Comment by MarcusTomlinson** [comment]
In fact, the docs in GitHub are up to date, the site just needs a new Doxygen build.

**Comment by garyscavone** [comment]
Closing, as this has apparently been dealt with.

**Comment by MarcusTomlinson** [comment]
@garyscavone it’s dealt with in the repo but music.mcgill.ca/~gary/rtaudio need to be regenerated.

**Comment by garyscavone** [comment]
We’re pushing for a new release soon, so that will be fixed at that point.
