### ISSUE TITLE
Documentation can not be generated with CMake setup

### ISSUE THREAD

**Issue by dvzrv** [thestk/rtaudio#198]
Currently, when packaging rtaudio 5.1.0 I have to jump through hoops to use the cmake setup and generate documentation:

```
autoreconf -vfi
mkdir -p build
cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr -DRTAUDIO_API_ALSA=ON -DRTAUDIO_API_JACK=ON -DRTAUDIO_PULSE=ON -DRTAUDIO_BUILD_PYTHON=ON ..
make
cd ..
./configure --prefix=/usr --with-alsa --with-jack --with-pulse
cd docs
make
```

It would be very benificial, if this could be integrated into the CMake setup as well.

**Comment by radarsat1** [comment]
I would accept a PR that does this.

But, i recommend that packaging is based onthe automake-based build system.

**Comment by dvzrv** [comment]
A note in the README.md would be great to clarify this.

**Comment by garyscavone** [comment]
I see a note in the README ... closing.
