### ISSUE TITLE
pyrtaudio is not compatible with python >= 3.6

### ISSUE THREAD

**Issue by dvzrv** [thestk/rtaudio#199]
Given, that [python2 is soon EOL](https://pythonclock.org/), it would be great to make pyrtaudio compatible with python3 (only).
A separate repository might even actually make more sense.
In any case: Currently it's not possible to build it with the provided setuptools configuration, using python3.

**Comment by dvzrv** [comment]
As python2 is EOL, I will now remove the python2 bindings, to allow Arch Linux to drop python2 from the official repositories in the near future.

If anyone with knowledge about the bindings is able to update them to be python3 compatible, I will of course add them back.

**Comment by radarsat1** [comment]
Fixed in 84126ff13b149aa4cfa72dacfc45ee74aa7ab122
