### ISSUE TITLE
WASAPI - channel offset has no effect

### ISSUE THREAD

**Issue by rick-spada** [thestk/rtaudio#202]
I've been experimenting with RtAudio compiled with WASAPI and the playsaw test.  When I run playsaw and specify a channelOffset, the audio always comes out of the first channel.  I've compiled playsaw both with Visual Studio and mingw and the result is the same.

**Comment by MarcusTomlinson** [comment]
Hi Rick, thanks for bringing this to our attention. Fix incoming...

**Comment by rick-spada** [comment]
Marcus,

The fix works great, thanks!

-- Rick
