### ISSUE TITLE
ASIO: with a Sound Devices USBPre 2 ASIO driver, you can start a stream even if no device is connected !

### ISSUE THREAD

**Issue by renaud-sc** [thestk/rtaudio#208]
I have encountered an issue on a computer where the driver for a Sound Devices USBPre 2 was installed. Even if the device was not connected to the computer, RtAudio did selected it as default device. 

As my application is designed to immediately start working with the first ASIO device it find (of course when started the user can choose another device and use it as default for next startup), the audio processing was "freezed" and it was impossible to stop it.

In fact this problem can easily be reproduced by installing the driver from the following URL:
https://www.sounddevices.com/usbpre-2-asio-driver-download/
No device required ;-)

I found out that RtApiAsio::callbackEvent never get called which make sense there is no clock I guess, but because it is never called there is no way to stop the audio thread:
WaitForSingleObject( handle->condition, INFINITE );  // block until signaled
in
RtApiAsio::stopStream()
will wait forever.

OK, the driver is probably buggy but I believe the host application should not remain stuck.

I have check how the Reaper DAW deal with it and basically when you hit play it says something like 'impossible to initialise the audio device' and it doesn't freeze. So there is a way to detect that things went wrong but I am not an ASIO specialist so if someone could point me to the right direction I can probably debug further.

**Comment by Youlean** [comment]
The same is true for DS.
I did some modifications (hacks) to prevent this. 
For example I did set WaitForSingleObject( handle->condition, 1000);
