### ISSUE TITLE
Include <algorithm> for VC++2013 compatibility

### ISSUE THREAD

**Issue by camlorn** [thestk/rtaudio#21]
When building on VC++2013, std::max needs to be obtained by including algorithm.  If not included, Rtaudio won't build.
Not sure what other windows headers might offer std::max, but <algorithm> is the one I always use.

**Comment by garyscavone** [comment]
I guess this is for WASAPI? I don't see any other uses of the std::max function.

**Comment by radarsat1** [comment]
This was fixed by PR #26
