### ISSUE TITLE
MacOS CoreAudio issue

### ISSUE THREAD

**Issue by joeladams** [thestk/rtaudio#211]
I'm running MacOS High Sierra, have the commandline tools installed, and am using homebrew's gcc/g++ 7.3.0. I am trying to begin installing RTAudio by entering:

./configure --with-core

but I get this:
...
checking for unistd.h... (cached) yes
checking whether to compile debug version... no
checking for gettimeofday... yes
checking for doxygen... doxygen 
checking CoreAudio/CoreAudio.h usability... no
checking CoreAudio/CoreAudio.h presence... yes
configure: WARNING: CoreAudio/CoreAudio.h: present but cannot be compiled
configure: WARNING: CoreAudio/CoreAudio.h:     check for missing prerequisite headers?
configure: WARNING: CoreAudio/CoreAudio.h: see the Autoconf documentation
configure: WARNING: CoreAudio/CoreAudio.h:     section "Present But Cannot Be Compiled"
configure: WARNING: CoreAudio/CoreAudio.h: proceeding with the compiler's result
configure: WARNING:     ## ----------------------------------- ##
configure: WARNING:     ## Report this to gary@music.mcgill.ca ##
configure: WARNING:     ## ----------------------------------- ##
checking for CoreAudio/CoreAudio.h... no
configure: error: CoreAudio header files not found!

So it is finding the CoreAudio header files but cannot compile or use them for some reason.

I've contacted gary@music.mcgill.ca and he hadn't seen this problem before, so he suggested I post the issue here in case someone has a suggestion... Ideas? 

-Joel.

**Comment by lizny** [comment]
I just got a similar but not identical error - this is the rtaudio packaged in LoopAuditioneer:

checking for audio API... using CoreAudio
checking CoreAudio/CoreAudio.h usability... no
checking CoreAudio/CoreAudio.h presence... no
checking for CoreAudio/CoreAudio.h... no
configure: error: CoreAudio header files not found!

I commented out the part of the configure file checking for the presence of the CoreAudio.h file - that let configure complete with no further errors.   Make now craps out - but on a completely different issue. It is possible it is a following from messing with configure, but doesn't smell like it:

/usr/local/include/Block.h:16:3: error: Never include this file directly. Use <lzma.h> instead.
#       error Never include this file directly. Use <lzma.h> instead.
/usr/local/include/Block.h:88:2: error: unknown type name 'lzma_check'
        lzma_check check;
        ^
/usr/local/include/Block.h:143:2: error: unknown type name 'lzma_vli'
        lzma_vli compressed_size;

--snipping bunch of similar complaints--
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [RtAudio.o] Error 1

**Comment by garyscavone** [comment]
This seems like a compiler environment problem, not something related to RtAudio.
