### ISSUE TITLE
rtaudio.dll not found

### ISSUE THREAD

**Issue by davispolito** [thestk/rtaudio#219]
I have been trying to get this library up and running all day. 
I have finally gotten to this error
`` 'playsaw.exe' (Win32): Loaded 'C:\Users\Davis\Desktop\rtaudio-master\build\tests\Debug\playsaw.exe'. Symbols loaded.
'playsaw.exe' (Win32): Loaded 'C:\Windows\System32\ntdll.dll'. Cannot find or open the PDB file.
'playsaw.exe' (Win32): Loaded 'C:\Windows\System32\kernel32.dll'. Cannot find or open the PDB file.
'playsaw.exe' (Win32): Loaded 'C:\Windows\System32\KernelBase.dll'. Cannot find or open the PDB file.
'playsaw.exe' (Win32): Loaded 'C:\Windows\System32\apphelp.dll'. Cannot find or open the PDB file.
The thread 0x7234 has exited with code -1073741515 (0xc0000135).
The thread 0x6530 has exited with code -1073741515 (0xc0000135).
The program '[14632] playsaw.exe' has exited with code -1073741515 (0xc0000135) 'A dependent dll was not `found'.`
I am not sure what to do here as all i have done is pulled down, and ran cmake

**Comment by radarsat1** [comment]
Do you find RtAudio.dll somewhere?  If so, try copying it to the same folder as playsaw.exe.

**Comment by davispolito** [comment]
I was able to come to that conclusion last night eventually haha, I had never tried to use an SDK  pulled from github so i didn't realize cmake --install would put the dlls etc. into Program Files and then go from there. My new issue is trying to get this all to compile with a cuda kernel as well. Wish me luck!

**Comment by radarsat1** [comment]
> i didn't realize cmake --install would put the dlls etc. into Program Files 

it's possible this could be done differently / better
