### ISSUE TITLE
Can't use ASIO API after build with CMAKE

### ISSUE THREAD

**Issue by rope50** [thestk/rtaudio#223]
I'm developing a real time audio app. I'm trying to use the ASIO API for better latency, but after executing my program I see the message "RtAudio: no compiled support for specified API Argument!"

I'm using CMAKE for build the Visual Studio project, and setting: option(RTAUDIO_API_ASIO "Build ASIO API" ${WIN32}) in CmakeLists.txt

After run "cmake ." I got the message "-- Compiling with support for: asio".

Am I forgetting something? Thank you!

**Comment by garyscavone** [comment]
What API argument did you use when instantiating RtAudio?

**Comment by rope50** [comment]
Hi @garyscavone, I used: ** RtAudio(RtAudio::Api::WINDOWS_ASIO)**

**Comment by garyscavone** [comment]
Then it would seem to be a CMAKE issue, which I don’t know anything about. Hopefully, someone that has worked on the CMAKE stuff can figure it out. Or you can try to figure it out. In fact, all you need to do is make sure the correct preprocessor definition is used when compiling and all the code is in only the two files (RtAudio.h and .cpp).

**Comment by sonoro1234** [comment]
I have used cmake to build RtAudio without having this issue

**Comment by radarsat1** [comment]
@rope50 can you check the Visual Studio project preprocessor defines?  `__WINDOWS_ASIO__` should be in there.

**Comment by rope50** [comment]
I set RTAUDIO_API_ASIO as ON in CmakeLists file:

![image](https://user-images.githubusercontent.com/2730873/67700638-189a9680-f98d-11e9-869c-462d9d40e225.png)

After I run "cmake ." I can see ASIO sources in the rtaudio project:

![image](https://user-images.githubusercontent.com/2730873/67700311-80041680-f98c-11e9-83c0-fcdd2f6b99d0.png)

But in preprocessor defines there is no __WINDOWS_ASIO__ define:

![image](https://user-images.githubusercontent.com/2730873/67700372-97db9a80-f98c-11e9-9f8f-f077fd6563c6.png)

Thanks to all.

**Comment by sonoro1234** [comment]
Modifying CMakeLists.txt is not necessary.
Which is your command line for cmake?

**Comment by rope50** [comment]
@sonoro1234 thank you for your response.

I'm just using "cmake ." in my root project directory.

I'm had also made the same in rtaudio root directory with same results.

**Comment by sonoro1234** [comment]
Try this:
From a directory next to project directory run
`cmake -G"Visual Studio 15 2017" -DCMAKE_BUILD_TYPE=Release -DRTAUDIO_API_ASIO=ON  ../rtaudio`

**Comment by rope50** [comment]
@sonoro1234 It was the same =/. I finally created my own CMakeLists file including all the ASIO sources manually and finally works.

**Comment by radarsat1** [comment]
I guess this didn't result in any contributions, so closing.
