### ISSUE TITLE
Detect loopback ability?

### ISSUE THREAD

**Issue by cmaughan** [thestk/rtaudio#227]
On my windows system, with RtAudio compiled for WASAPI, I found I could set an input channel to be the output speaker device.  Stepping through the code this seems to enable a loop back ability where the output sound is fed into the input stream.

I'm imagine this wouldn't work for all API's.  And the audio out devices are not listed in the list of input channels.  So my question is: how to detect that it will be possible to set an output as an 'input' and have it work?  I can't see any flags, and those channels aren't marked 'Duplex' either.

**Comment by MarcusTomlinson** [comment]
There is no way currently to detect if loopback is supported. At the same time however, I can tell you that WASAPI is the only API that supports this.

**Comment by cmaughan** [comment]
Well, I guess that's good enough :)
