### ISSUE TITLE
Memory Leak using Alsa on Linux ( RtApiAlsa::probeDeviceOpen )

### ISSUE THREAD

**Issue by A-Ribeiro** [thestk/rtaudio#228]
### RtAudio.cpp

in the RtApiAlsa::probeDeviceOpen (7529)

in the debug you attach the output to stderr

```c++
#if defined(__RTAUDIO_DEBUG__)
	snd_output_t *out;
	snd_output_stdio_attach(&out, stderr, 0);
#endif
```

But you don't release the output on the end of the method... each time you leak 16 to 24 bytes due to this attachment.

### Solution

 - before each return in this function put something like this:

```c++
#if defined(__RTAUDIO_DEBUG__)
//stops mem leak at debug
snd_output_close(out);
#endif
return FAILURE;
```

And finally you can return success with no leaks.

```c++
#if defined(__RTAUDIO_DEBUG__)
//stops mem leak at debug
snd_output_close(out);
#endif
return SUCCESS;
```

That's it.

**Comment by garyscavone** [comment]
Thanks! Can you submit a PR?

**Comment by A-Ribeiro** [comment]
is there a tutorial I can follow to make a pull request?

I dont have the repo clone, I downloaded a zip...

p.s.: I'm new using git

**Comment by A-Ribeiro** [comment]
I created a PR... but I don't know how to bind it to this issue

**Comment by garyscavone** [comment]
Great … many thanks! I’ll take a look within the next week.
