### ISSUE TITLE
CoreAudio stop stream with wrong input stream id (RtApiCore::stopStream)

### ISSUE THREAD

**Issue by A-Ribeiro** [thestk/rtaudio#229]
When call RtApiCore::stopStream the input was trying to stop the record id...

given me this message at the program ends:

```
[AudioHAL_Client] AudioHardware.cpp:2682:AudioDeviceStop:  AudioDeviceStop: no device with given ID
```

### Solution

In RtAudio.cpp line 1631 the code is:

```c++
result = AudioDeviceStop(handle->id[0], handle->procId[1]);
```

Needs to change it to:

```c++
result = AudioDeviceStop(handle->id[1], handle->procId[1]);
```

**Comment by tucano42** [comment]
Same issue here. I can confirm that this fix is necessary and working.

**Comment by garyscavone** [comment]
This is odd, as it doesn't cause an error on my OS-X laptop. But it does appear to be a bug so I just fixed it.
