### ISSUE TITLE
In Windows DS, default device name is hardcoded to English

### ISSUE THREAD

**Issue by tucano42** [thestk/rtaudio#231]
The RtAudio implementation for Windows DirectSound is overwriting the localized name of the default device to its english name.
This happens in line 7046 of the current RtAudio.cpp:
`  if ( lpguid == NULL )`
`    name = "Default Device";`

If the device names are shown to the user on a system where English is not the system language, this will look incorrect, because the localized names are normally provided by the OS, so an English name is not expected there.

I tried to simply remove this line, but then the sorting of the devices is wrong, because it will cause the default capture device to no longer be at the beginning of the list. This is because the RtAudio DS implementation mixes the input and output devices into one array. So a fix might require to use separate array entries for input and output devices. This is what I will try to fix this for myself.

**Comment by radarsat1** [comment]
I doubt this will ever get fixed unless Windows provides a way to get the device name or some equivalent of the "Default Device" string from a localized API.  Feel free to make suggestions for how to handle this simply, but I highly doubt RtAudio will ever integrate a full localization system.  Applications that are concerned with localization can of course detect the string "Default Device" and replace it with whatever they want on display.. not so elegant but I don't see an alternative.

**Comment by tucano42** [comment]
Windows already does provide localized device names, including the name of the default device. That is the whole problem: On a non-english system, all device names will be localized, except for the default device, which has been overwritten by RtAudio to the English "Default Device". So RtAudio doesn't need a localization system, it just has to not interfere with the existing localization system of the operating system.

To fix this, I changed RtAudio.cpp, lines 7043-7063 from this:
```C++
// If good device, then save its name and guid.
  std::string name = convertCharPointerToStdString( description );
  //if ( name == "Primary Sound Driver" || name == "Primary Sound Capture Driver" )
  if ( lpguid == NULL )
    name = "Default Device";
  if ( validDevice ) {
    for ( unsigned int i=0; i<dsDevices.size(); i++ ) {
      if ( dsDevices[i].name == name ) {
        dsDevices[i].found = true;
        if ( probeInfo.isInput ) {
          dsDevices[i].id[1] = lpguid;
          dsDevices[i].validId[1] = true;
        }
        else {
          dsDevices[i].id[0] = lpguid;
          dsDevices[i].validId[0] = true;
        }
        return TRUE;
      }
    }
```

into this:
```C++
  // If good device, then save its name and guid.
  std::string name = convertCharPointerToStdString( description );
  //if ( name == "Primary Sound Driver" || name == "Primary Sound Capture Driver" )
  //if ( lpguid == NULL )
  //  name = "Default Device";  //localize?
  if ( validDevice ) {
    for ( unsigned int i=0; i<dsDevices.size(); i++ )
    {
      if ( dsDevices[i].name == name ) 
      {
        if ( probeInfo.isInput && dsDevices[i].id[1] == lpguid) 
        {
          dsDevices[i].found = true;
          dsDevices[i].id[1] = lpguid;
          dsDevices[i].validId[1] = true;
        }
        else if (dsDevices[i].id[0] == lpguid)
        {
          dsDevices[i].found = true;
          dsDevices[i].id[0] = lpguid;
          dsDevices[i].validId[0] = true;
        }
        return TRUE;
      }
    }
```

With this fix, all localized device names will be used. In the original code, RtAudio tries to merge input and output devices into a single entry in the device array. This might fail with localized device names, because the default input and default output devices have different names. I guess that's the reason the original code overwrote the default device name in the first place.
In my changed code, separate array entries are used for input and output devices. This will preserve the relative order of the devices: the default device will always come first, and all names will preserve the localization provided by the OS.

**Comment by radarsat1** [comment]
> That is the whole problem: On a non-english system, all device names are localized correctly by the OS, and then RtAudio overwrites the default device name to the hardcoded English string "Default Device".

Ah perfect then, if the patch fixes then I'm all for it.
