### ISSUE TITLE
New type suggestion to represent RTAUDIO_SINT24

### ISSUE THREAD

**Issue by A-Ribeiro** [thestk/rtaudio#233]
I took a look at the code in the place you defined the S24 type... 

I'm posting here a suggestion on RTAUDIO_SINT24 type.

```c++
#include <stdint.h>

#pragma pack(push, 1)
class int24_t {
public:
	uint8_t bytes[3];

	int24_t() {}

	inline void operator = (const int32_t& i) {
#ifdef __BIG_ENDIAN__
		//not tested...
		bytes[2] = (i & 0x000000ff);
		bytes[1] = (i & 0x0000ff00) >> 8;
		bytes[0] = (i & 0x007f0000) >> 16 |
			(i & 0x80000000) >> 24;//sign bit
#else 
		// little endian - tested!
		bytes[0] = (i & 0x000000ff);
		bytes[1] = (i & 0x0000ff00) >> 8;
		bytes[2] = (i & 0x007f0000) >> 16 |
			(i & 0x80000000) >> 24;//sign bit
#endif

	}

	inline int24_t(const int8_t& c) { *this = (int32_t)c; }
	inline int24_t(const int16_t& s) { *this = (int32_t)s; }
	inline int24_t(const int32_t& i) { *this = i; }
	inline int24_t(const int64_t& i) { *this = (int32_t)i; }
	inline int24_t(const double& d) { *this = (int32_t)d; }
	inline int24_t(const float& f) { *this = (int32_t)f; }

	//allow this kind of casting:
	//  int24_t value24 = -1;
	//  int32_t value32 = (int32_t)value24;
	inline operator int32_t()const {
#ifdef __BIG_ENDIAN__
		//not tested...
		int32_t bitsign = bytes[0] & 0x80;
		int32_t result = bytes[2] | (bytes[1] << 8) | ((bytes[0] & 0x7f) << 16);
#else
		// little endian - tested!
		int32_t bitsign = bytes[2] & 0x80;
		int32_t result = bytes[0] | (bytes[1] << 8) | ((bytes[2] & 0x7f) << 16);
#endif
		//Two's complement conversion
		if (bitsign)
			result |= 0xff800000;
		return  result;
	}

	inline operator int64_t() const {
		return (int32_t)(*this);
	}

	inline operator float()const {
		return (int32_t)(*this);
	}

	inline operator double()const {
		return (int32_t)(*this);
	}
};
#pragma pack(pop)
```

This way we can implement an integer linear interpolation like this:

```c++

#define _UINT8_MAX 0x7f
#define _UINT16_MAX 0x7fff
#define _UINT24_MAX 0x7fffff
#define _UINT32_MAX 0x7fffffff

#include <stdint.h>

static inline
int32_t int_lerp32_single(const int32_t&a, const int32_t&b, float lerp) {
	float result = (float)a * (1.0f - lerp) + (float)b * lerp;
	if (result < 0)
		result -= 0.5f;
	else
		result += 0.5f;
	return (int32_t)result;
}


static inline
int32_t int_lerp32_double(const int32_t&a, const int32_t&b, double lerp) {
	double result = (double)a * (1.0 - lerp) + (double)b * lerp;
	if (result < 0)
		result -= 0.5f;
	else
		result += 0.5f;
	if (result <= -_UINT32_MAX)
		return -_UINT32_MAX;
	else if (result >= _UINT32_MAX)
		return _UINT32_MAX;
	return (int32_t)result;
}

template<typename C>
static inline
C int_lerp(const C&a, const C&b, float lerp) {
	if (sizeof(C) >= 4)
		return int_lerp32_double(a, b, lerp);
	else
		return int_lerp32_single(a, b, lerp);
}
```

Test code:

```c++
	printf("%i\n", int_lerp<int32_t>(-_UINT32_MAX, _UINT32_MAX, 0.0f));
	printf("%i\n", int_lerp<int32_t>(-_UINT32_MAX, _UINT32_MAX, 0.5f));
	printf("%i\n", int_lerp<int32_t>(-_UINT32_MAX, _UINT32_MAX, 1.0f));

	printf("%i\n", (int32_t)int_lerp<int24_t>(-_UINT24_MAX, _UINT24_MAX, 0.0f));
	printf("%i\n", (int32_t)int_lerp<int24_t>(-_UINT24_MAX, _UINT24_MAX, 0.5f));
	printf("%i\n", (int32_t)int_lerp<int24_t>(-_UINT24_MAX, _UINT24_MAX, 1.0f));

	printf("%i\n", int_lerp<int16_t>(-_UINT16_MAX, _UINT16_MAX, 0.0f));
	printf("%i\n", int_lerp<int16_t>(-_UINT16_MAX, _UINT16_MAX, 0.5f));
	printf("%i\n", int_lerp<int16_t>(-_UINT16_MAX, _UINT16_MAX, 1.0f));

	printf("%i\n", int_lerp<int8_t>(-_UINT8_MAX, _UINT8_MAX, 0.0f));
	printf("%i\n", int_lerp<int8_t>(-_UINT8_MAX, _UINT8_MAX, 0.5f));
	printf("%i\n", int_lerp<int8_t>(-_UINT8_MAX, _UINT8_MAX, 1.0f));
```
I noticed the library doesn't resample the input. 

I have a camera with native 32khz samplerate and the app I'm developing needs 44.1khz.

I used this to implement a resampler template, you can take a look [here]( https://github.com/A-Ribeiro/OpenGLStarter/blob/master/projects-lib/rtaudio-wrapper/AudioResampler.h). With this template, it is possible to convert any samplerate to any samplerate, using linear interpolation.

**Comment by radarsat1** [comment]
Note that linear interpolation is good enough for a lot of purposes, but for a general purpose implementation it's important to be ware of [aliasing](https://ccrma.stanford.edu/~jos/lumped/Linear_Interpolation_Frequency_Response.html).

In your implementation you are performing int to double to int conversion on every sample which is maybe a little wasteful too.  I recommend taking a look at [libsamplerate](http://www.mega-nerd.com/SRC/) if you want to do this for a serious application.  Unfortunately it seems not to support 24-bit integers.

**Comment by A-Ribeiro** [comment]
Hi,

I don´t know other interpolation I could use for audio resampling... I apreciate if you could point me to some algorithm or equation to do that. I think it might be possible to use some gaussian distribution, when convert a higher samplerate to a lower sample rate.

About the interpolation I did, it uses the single (float) when you are interpolating int24, int16 or int8. The use of double is for the int32 (the range becomes too wide to use float...).

I taken a look at the source of the libsamplerate. It uses double to interpolate the values and convert the result back to float.

About the aliasing... I believe it will occur when you are converting a higher sample rate to a lower sample rate. The opposite relation it will not be present.

**Comment by radarsat1** [comment]
Ok interesting note about libsamplerate, but in any case my point about it was just that there already exist some good open source implementations, so no need to reinvent the wheel.  And, if you're going to convert between float and int, I suggest keeping your signal in float as much as possible and just convert to 24-bit integers for output.  (Or letting RtAudio do this for you.)

The linear interpolation you suggest is ok, certainly better than simpler alternatives, but just be aware of the spectral implications, (check the last two bullet points of the article I linked to -- basically the lobes of the filter it represents do alias).  Typically a good way to implement up/downsampling is through decimation + a polynomial FIR filter, where linear interpolation corresponds to 1st-order polynomial interpolation, and 2nd and 3rd (cubic) interpolation do a better job.  Usually downsampling is pre-filtered and upsampling is post-filtered.  Check the docs of [intfilt](https://www.mathworks.com/help/signal/ref/intfilt.html) for example.  Some coefficients for rate doubling using a cubic FIR filter are given [in this article](https://upcommons.upc.edu/bitstream/handle/2117/16993/Paper85.pdf) that is worth reading on the topic.  Finally I recommend looking through [Windowed Sinc Interpolation](https://ccrma.stanford.edu/~jos/pasp/Windowed_Sinc_Interpolation.html) and [Digital Audio Resampling](https://ccrma.stanford.edu/~jos/resample/) for some theory.

In any case RtAudio does not currently do sample rate conversion, except when it's supported by the underlying audio system (e.g. WASAPI).  So it's a bit off-topic here unless that changes, although maybe useful for some users of RtAudio to have some notes here on it.

**Comment by garyscavone** [comment]
In fact, the WASAPI implementation in RtAudio does perform its own sample rate conversion (not using a built-in function supported by the API) because the WASAPI system isn't as flexible in terms of allowing the user to change the sample rate. And I believe that the implemented sample rate conversion is simple linear interpolation, which is not good.

Since this only affects the one API, I've been ignoring this issue. However, if we could come up with a fairly simple sinc interpolation scheme, along the lines of the current convertBuffer() function (something like resampleBuffer()), that would seem like a good addition to RtAudio. However, it would probably need to be defined in a class with persistent memory, as you wouldn't want to be recalculating the filter coefficients for each buffer (and you'd need to maintain the filter state between calls).

**Comment by MarcusTomlinson** [comment]
> I believe that the implemented sample rate conversion is simple linear interpolation, which is not good.

The WASAPI implementation used to use a simple linear interpolator, but now it's done using the Media Foundation Resampler DSP [1].

https://github.com/thestk/rtaudio/blob/8c1610a91b0d9067e3111361d149a97f36088d05/RtAudio.cpp#L4012

[1] https://docs.microsoft.com/en-us/windows/win32/medfound/audioresampler

**Comment by garyscavone** [comment]
I'm closing this, as I don't feel the proposed change is necessary for RtAudio.
