### ISSUE TITLE
Latency with Coreaudio is 4-5x times what it should be.

### ISSUE THREAD

**Issue by RemiCollin** [thestk/rtaudio#239]
From this issue on VCVRack :[Actual latency much higher than expected with VCV Audio]( https://github.com/VCVRack/Rack/issues/1734)

Measured latency when using rtAudio's core audio implementation is 4 to 5 times what is reported by the driver.

**Comment by garyscavone** [comment]
The value returned by RtAudio represents the _internal_ latency reported by the device. But there is also inherent latency due to your own buffering. Did you add the latency due to the buffer size you are using?

**Comment by RemiCollin** [comment]
To my knowledge, VCV doesn't add buffering and process audio sample by sample. Maybe @AndrewBelt can confirm this. Also, it seems to be happening only with CoreAudio (and ALSA apparently to a lesser extent), it doesn't happen with ASIO.

**Comment by lfnoise** [comment]
VCV does *compute* one sample at a time, however CoreAudio buffers are not single sample. VCV is filling a buffer. VCV's AudioInterface.cpp, line 36, sets the default block size on RtAudio as 256 samples @ 44100 Hz.  So you're getting that latency (5.8 msec), plus the driver. (NB. I am not that familiar with the internals of either VCV or RtAudio, but I am a former Apple CoreAudio engineer.)

**Comment by garyscavone** [comment]
Stale ... closing.
