### ISSUE TITLE
Distorted audio on simple ASIO loop through

### ISSUE THREAD

**Issue by jheliker** [thestk/rtaudio#24]
Hello - 

I am currently testing RtAudio in hopes to use it on a project, and am getting unexpected results!

Given my code below (hooked up to a known-good ASIO device), I would expect my output to be essentially a copy of my input; that said it is very distorted and only somewhat recognizable with all the static / noise. Using Audacity or other known-good software I can run the same test on my hardware with no audible problems.

My setup is very simple:

audioDriver->openStream(&parameters, &parameters, RTAUDIO_SINT16, sampleRate, &bufferFrames, &input, NULL, &options);
audioDriver->startStream();

And my callback is very simple too:

int input(void *outputBuffer, void *inputBuffer, unsigned int nBufferFrames,
	double streamTime, RtAudioStreamStatus status, void *userData)
{	
	if (status)
		std::cout << "input: " << status << std::endl;
	memcpy(outputBuffer, inputBuffer, nBufferFrames);
	return 0;
}

Any insight you could offer would be so appreciated!! Sorry if this is the wrong place to post a question / issue of this nature.

Kind Regards,

 - James Heliker

**Comment by radarsat1** [comment]
Closing because no response in several months.
