### ISSUE TITLE
PulseAudio doesn't work correctly on Ubuntu 19.10

### ISSUE THREAD

**Issue by loics2** [thestk/rtaudio#240]
I wrote a basic program to list the available devices (taken from [here](https://www.music.mcgill.ca/~gary/rtaudio/probe.html)) : 

```cpp
    RtAudio audio;
    auto count = audio.getDeviceCount();

    std::cout << count << " devices detected :\n" << std::endl;

    RtAudio::DeviceInfo info;
    for (unsigned int i = 0; i < count; i++) {
        info = audio.getDeviceInfo(i);
        if (info.probed) {
            std::cout << '\t' << i << ") " << info.name << '\n';
        }
        std::cout << std::endl;
    }
```

I want to use a USB Audio class 2 device, it's correctly detected by the system and shown in the output of `pacmd list-sources`, but without specifying the API to RtAudio, the output of my program is:

```
1 devices detected :

        0) PulseAudio
```

And that's it. Same result when I specify `RtAudio::Api::LINUX_PULSE`. When I use `RtAudio::Api::LINUX_ALSA`, everything seems to work correctly.

**Comment by radarsat1** [comment]
Thanks for pointing this out. I have not been much into the PA code but now that I look there is definitely some things left unimplemented on the device discovery side of things, e.g.,

```
unsigned int RtApiPulse::getDeviceCount( void )
{
  return 1;
}
```

However I think I found the relevant docs, https://www.freedesktop.org/software/pulseaudio/doxygen/introspect.html#sinksrc_subsec
So it should hopefully be somewhat straightforward, let's see..

**Comment by radarsat1** [comment]
Can you try master?

**Comment by loics2** [comment]
It seems to work!

I use the basic code I mentioned previously and I open a stream in duplex mode and everything seems to work just fine.

**Comment by radarsat1** [comment]
Excellent!

**Comment by loics2** [comment]
Thanks! That was quick
