### ISSUE TITLE
Mono playback on CoreAudio will only play on left channel

### ISSUE THREAD

**Issue by tucano42** [thestk/rtaudio#243]
To test this, run the "playsaw" test that comes with RtAudio:
`./playsaw 1 44100`

On macOS Catalina, this will only play on the left channel. On Windows with DirectSound, it will play on both channels. 
For comparison, with PortAudio, opening a mono stream for playback will play on both channels (both on Windows and Mac).

Is this the expected behaviour of RtAudio, or is this a bug? The documentation states that "RtAudio will provide automatic channel number compensation when the number of channels set by the user is less than that required by the device." This does not clarify if it will send a mono stream from the user to both stereo channels or just the left one.

**Comment by garyscavone** [comment]
That is the expected behaviour. If you want it to play on both channels, then you need to open a two-channel instance and copy the mono samples to both channels.

**Comment by tucano42** [comment]
Ok, thanks.
Is there a use case for playing a mono file just on the left speaker? 
I would like to request an enhancement to RtAudio to be able to send mono streams to both output channels. For now I'll just do that on the client side, as you suggested.

**Comment by nyanpasu64** [comment]
On Windows (I think it's WASAPI but the device name doesn't say which API was used), a mono stream only plays in the left speaker.

On Linux PulseAudio, a mono stream plays in both speakers.

This is inconsistent behavior.

I guess in my app, I'll implement copying the samples to both channels at some point, unless I implement proper stereo support later on.

**Comment by radarsat1** [comment]
I agree that it's not clear in the docs what should happen, this has tripped me up a couple of times too and indeed there are inconsistencies across APIs on this.  I'm having a hard time thinking of cases when it would be desirable behaviour.  Gary what do you think about the idea of enforcing mono to stereo broadcasting across APIs?

Usually we default to the API default behaviour -- so perhaps a StreamOptions flag would be appropriate.  I don't think we should go as far as arbitrary channel mapping and all its complexities, but a simple "please broadcast mono to stereo" or "mono to surround" might be quite useful.

**Comment by nyanpasu64** [comment]
When using PortAudio, on all platforms (Windows DirectSound, WASAPI, Linux ALSA), a mono stream plays in both speakers.

In [portaudio/src/hostapi/wasapi/pa_win_wasapi.c](https://app.assembla.com/spaces/portaudio/git/source/master/src/hostapi/wasapi/pa_win_wasapi.c), `GetMonoToStereoMixer()` gets called whenever I open a WASAPI output stream in mono, and `PaWasapiSubStream` `monoMixer` gets called whenever I write to the stream. Interestingly, `_MixMonoToStereo_1TO2_32f` is being called despite me selecting int16 (not float32) as an output format.

This means that portaudio has code to broadcast mono to stereo.

**Comment by garyscavone** [comment]
Personally, I would prefer that all APIs send mono data to only one channel. It is up to the users to decide if they want mono data to be played back on two channels (very easy to implement in the callback function by copying the data twice). And what if someone really wanted mono data played on a single channel but RtAudio prevented that? I would suggest that we attempt to get the APIs that don't meet this behaviour to conform to it if possible.

**Comment by ricardopolo** [comment]
Any advice about how can I convert my mono audio to stereo to make it sound in both speakers?

**Comment by garyscavone** [comment]
This has come up a few times. Generally, you open a two-channel stream and just “copy” your mono signal into both channels.

**Comment by daankets** [comment]
I think this issue could be closed, it seems stale, and the behavior seems to be as desired & designed?

**Comment by garyscavone** [comment]
I'm going to leave it open as a reminder that we need to look into making sure all APIs are consistent on this issue.

**Comment by garyscavone** [comment]
A note about this is now on the README.md.
