### ISSUE TITLE
RtAudio.getDeviceCount returns incorrect number.

### ISSUE THREAD

**Issue by R030t1** [thestk/rtaudio#244]
I lifted the "enumerate devices" example off of the documentation and receive only one device in response:

```
device = 0: maximum output channels = 2
```

I should have a lot more than that:
```
% aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: HDMI [HDA Intel HDMI], device 3: Generic Digital [Generic Digital]
  Subdevices: 0/1
  Subdevice #0: subdevice #0
card 1: PCH [HDA Intel PCH], device 0: Generic Analog [Generic Analog]
  Subdevices: 0/1
  Subdevice #0: subdevice #0
card 2: Gadget [Bar Gadget], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

```
% arecord -l
**** List of CAPTURE Hardware Devices ****
card 1: PCH [HDA Intel PCH], device 0: Generic Analog [Generic Analog]
  Subdevices: 0/1
  Subdevice #0: subdevice #0
card 2: Gadget [Bar Gadget], device 0: USB Audio [USB Audio]
  Subdevices: 0/1
  Subdevice #0: subdevice #0
```

To date I've found no audio library that is actually usable for both enumerating the devices and reading from them. Best I got was ALSA, but then if the user has PA you can't read from the device with ALSA.

At one point I had to resort to using libusb.

**Comment by radarsat1** [comment]
Related to #224.

**Comment by jonasreijniers** [comment]
I have exactly the same problem - it returns one device only:  

` device 0 = PulseAudio: maximum input channels = 2 `                                                              `

Has anyone found a solution to this?

**Comment by lp35** [comment]
Solution is here: #270 

https://github.com/thestk/rtaudio/issues/270#issuecomment-733130335

**Comment by garyscavone** [comment]
Closing ... this has been fixed.
