### ISSUE TITLE
WASAPI Input stream issue

### ISSUE THREAD

**Issue by jkeller51** [thestk/rtaudio#248]
Hi,

Up until recently I couldn't use WASAPI at all or I'd get a crash. But with the latest version of RtAudio a1ddca0c4, I was excited to find that I can use it now.

However, if I use RtAudio in duplex mode with microphone input selected and using WASAPI driver, I get a weird glitchy-sounding microphone signal overlayed in my output, even when I just fill the output with 0s, e.g.:

```c++
static int RtAudioStreamCallback(void * outputBuffer, void * inputBuffer, unsigned int nBufferFrames, double streamTime, RtAudioStreamStatus status, void * data) {
    /* data should be a pointer to a ZivixPlugin */
    ZivixPlugin * zivixPlugin = (ZivixPlugin *) data;
    uint32_t och = zivixPlugin->getNumOutputChannels();
    uint32_t ich = zivixPlugin->getNumInputChannels();
    double * out = (double *) outputBuffer;
    for (uint32_t ch=0; ch<och; ch++) {  // non-interleaved mode
        for (uint32_t s=0;s<nBufferFrames;s++) {
            out[ch*nBufferFrames + s] = 0;
        }
    }
    return 0;
}
```

This callback code causes weird distorted microphone input coming through to my output.

I've been using DirectSound and ASIO without any audio issues.

I discovered that if I set the input settings to NULL (so we are in playback-only mode), the issue goes away.

**Comment by MarcusTomlinson** [comment]
Could you please run RtAudio's own duplex test app locally and see if the problem persists:
https://github.com/thestk/rtaudio/blob/master/tests/duplex.cpp

I've just given this ^ a go locally without issue.

**Comment by jkeller51** [comment]
I ran the test with WASAPI API and FLOAT64 data type. I had the same type of audio issues. Github doesn't allow embedding videos, so here is a link:

https://streamable.com/9ty1ra

**Comment by jkeller51** [comment]
I changed the audio callback to clear the output buffer

```c++
int inout( void *outputBuffer, void *inputBuffer, unsigned int /*nBufferFrames*/,
           double /*streamTime*/, RtAudioStreamStatus status, void *data )
{
  // Since the number of input and output channels is equal, we can do
  // a simple buffer copy operation here.
  if ( status ) std::cout << "Stream over/underflow detected." << std::endl;

  unsigned int *bytes = (unsigned int *) data;
  //memcpy( outputBuffer, inputBuffer, *bytes );
  memset(outputBuffer, 0, *bytes);
  return 0;
}
```

Here is the result
https://streamable.com/hllsgx

**Comment by MarcusTomlinson** [comment]
Could you do me a favour and tell me what format your Playback device is set to.

And the same for your Recording device too please.

<img width="751" alt="Screenshot 2020-05-09 at 00 01 55" src="https://user-images.githubusercontent.com/7335138/81455839-4eb0a280-9188-11ea-8df3-c1224af1adbc.png">

**Comment by MarcusTomlinson** [comment]
Oh and also, what command-line arguments are you passing duplex?

**Comment by MarcusTomlinson** [comment]
Would you also please make sure that the defines at the top of your duplex.cpp look like this:

```
/*
typedef char MY_TYPE;
#define FORMAT RTAUDIO_SINT8

typedef signed short MY_TYPE;
#define FORMAT RTAUDIO_SINT16

typedef S24 MY_TYPE;
#define FORMAT RTAUDIO_SINT24

typedef signed long MY_TYPE;
#define FORMAT RTAUDIO_SINT32

typedef float MY_TYPE;
#define FORMAT RTAUDIO_FLOAT32
*/

typedef double MY_TYPE;
#define FORMAT RTAUDIO_FLOAT64
```

**Comment by jkeller51** [comment]
![image](https://user-images.githubusercontent.com/20546616/81456453-efd33500-9157-11ea-9d40-054c21247455.png)

Command
duplex.exe 2 48000

Maybe a 24 bit audio issue? I'll try setting it to CD quality.

**Comment by MarcusTomlinson** [comment]
Would you also please make sure that the defines at the top of your duplex.cpp look like this:

```
/*
typedef char MY_TYPE;
#define FORMAT RTAUDIO_SINT8

typedef signed short MY_TYPE;
#define FORMAT RTAUDIO_SINT16

typedef S24 MY_TYPE;
#define FORMAT RTAUDIO_SINT24

typedef signed long MY_TYPE;
#define FORMAT RTAUDIO_SINT32

typedef float MY_TYPE;
#define FORMAT RTAUDIO_FLOAT32
*/

typedef double MY_TYPE;
#define FORMAT RTAUDIO_FLOAT64
```

**Comment by jkeller51** [comment]
That's exactly how it looks. I can just send you the whole file if you want.

I didn't have CD quality as an option on my windows audio settings, but I tried DVD quality (16-bit, 48 kHz) and had the same exact result.

**Comment by MarcusTomlinson** [comment]
> I can just send you the whole file if you want.

Yes please

**Comment by MarcusTomlinson** [comment]
Could I have the format your Recording device too please.

**Comment by jkeller51** [comment]
```c++
/******************************************/
/*
  duplex.cpp
  by Gary P. Scavone, 2006-2007.

  This program opens a duplex stream and passes
  input directly through to the output.
*/
/******************************************/

#include "RtAudio.h"
#include <iostream>
#include <cstdlib>
#include <cstring>

/*
typedef char MY_TYPE;
#define FORMAT RTAUDIO_SINT8

typedef signed short MY_TYPE;
#define FORMAT RTAUDIO_SINT16

typedef S24 MY_TYPE;
#define FORMAT RTAUDIO_SINT24

typedef signed long MY_TYPE;
#define FORMAT RTAUDIO_SINT32

typedef float MY_TYPE;
#define FORMAT RTAUDIO_FLOAT32
*/

typedef double MY_TYPE;
#define FORMAT RTAUDIO_FLOAT64

void usage( void ) {
  // Error function in case of incorrect command-line
  // argument specifications
  std::cout << "\nuseage: duplex N fs <iDevice> <oDevice> <iChannelOffset> <oChannelOffset>\n";
  std::cout << "    where N = number of channels,\n";
  std::cout << "    fs = the sample rate,\n";
  std::cout << "    iDevice = optional input device to use (default = 0),\n";
  std::cout << "    oDevice = optional output device to use (default = 0),\n";
  std::cout << "    iChannelOffset = an optional input channel offset (default = 0),\n";
  std::cout << "    and oChannelOffset = optional output channel offset (default = 0).\n\n";
  exit( 0 );
}

int inout( void *outputBuffer, void *inputBuffer, unsigned int /*nBufferFrames*/,
           double /*streamTime*/, RtAudioStreamStatus status, void *data )
{
  // Since the number of input and output channels is equal, we can do
  // a simple buffer copy operation here.
  if ( status ) std::cout << "Stream over/underflow detected." << std::endl;

  unsigned int *bytes = (unsigned int *) data;
  //memcpy( outputBuffer, inputBuffer, *bytes );
  memset(outputBuffer, 0, *bytes);
  return 0;
}

int main( int argc, char *argv[] )
{
  unsigned int channels, fs, bufferBytes, oDevice = 0, iDevice = 0, iOffset = 0, oOffset = 0;

  // Minimal command-line checking
  if (argc < 3 || argc > 7 ) usage();

  RtAudio adac(RtAudio::Api::WINDOWS_WASAPI);
  if ( adac.getDeviceCount() < 1 ) {
    std::cout << "\nNo audio devices found!\n";
    exit( 1 );
  }

  channels = (unsigned int) atoi(argv[1]);
  fs = (unsigned int) atoi(argv[2]);
  if ( argc > 3 )
    iDevice = (unsigned int) atoi(argv[3]);
  if ( argc > 4 )
    oDevice = (unsigned int) atoi(argv[4]);
  if ( argc > 5 )
    iOffset = (unsigned int) atoi(argv[5]);
  if ( argc > 6 )
    oOffset = (unsigned int) atoi(argv[6]);

  // Let RtAudio print messages to stderr.
  adac.showWarnings( true );

  // Set the same number of channels for both input and output.
  unsigned int bufferFrames = 512;
  RtAudio::StreamParameters iParams, oParams;
  iParams.deviceId = iDevice;
  iParams.nChannels = channels;
  iParams.firstChannel = iOffset;
  oParams.deviceId = oDevice;
  oParams.nChannels = channels;
  oParams.firstChannel = oOffset;

  if ( iDevice == 0 )
    iParams.deviceId = adac.getDefaultInputDevice();
  if ( oDevice == 0 )
    oParams.deviceId = adac.getDefaultOutputDevice();

  RtAudio::StreamOptions options;
  //options.flags |= RTAUDIO_NONINTERLEAVED;

  bufferBytes = bufferFrames * channels * sizeof( MY_TYPE );
  try {
    adac.openStream( &oParams, &iParams, FORMAT, fs, &bufferFrames, &inout, (void *)&bufferBytes, &options );
  }
  catch ( RtAudioError& e ) {
    std::cout << '\n' << e.getMessage() << '\n' << std::endl;
    exit( 1 );
  }

  // Test RtAudio functionality for reporting latency.
  std::cout << "\nStream latency = " << adac.getStreamLatency() << " frames" << std::endl;

  try {
    adac.startStream();

    char input;
    std::cout << "\nRunning ... press <enter> to quit (buffer frames = " << bufferFrames << ").\n";
    std::cin.get(input);

    // Stop the stream.
    adac.stopStream();
  }
  catch ( RtAudioError& e ) {
    std::cout << '\n' << e.getMessage() << '\n' << std::endl;
    goto cleanup;
  }

 cleanup:
  if ( adac.isStreamOpen() ) adac.closeStream();

  return 0;
}
```

**Comment by jkeller51** [comment]
![image](https://user-images.githubusercontent.com/20546616/81456706-00d07600-9159-11ea-92e1-50d46c8a2f65.png)

**Comment by jkeller51** [comment]
Tried changing it to
![image](https://user-images.githubusercontent.com/20546616/81456739-278eac80-9159-11ea-8ab7-cb032864a25f.png)

With DVD quality for the output format. Same result.

**Comment by MarcusTomlinson** [comment]
Very weird... If I replicate your setup exactly I still have no issues. Is there still such a thing as a 32bit Windows install? And do you by chance have one? (Clutching at straws now)

**Comment by jkeller51** [comment]
I think there is, considering Windows can now run on ARM to some extent.

However, I am not running a 32-bit OS. Here are my system specs:

![image](https://user-images.githubusercontent.com/20546616/81456870-adaaf300-9159-11ea-8cc0-70713c630fc5.png)

**Comment by jkeller51** [comment]
I'd be happy to run any test code you can whip up. Exporting a buffer to a txt file, maybe?

**Comment by MarcusTomlinson** [comment]
2x raw files (output written direct to file) may be useful yeah - one with the passthrough, and with your cleared output patch.

**Comment by MarcusTomlinson** [comment]
I have to ask, you are running rtaudio from the latest master without any modification right?

**Comment by jkeller51** [comment]
I am running the commit on master referenced in the OP. I'm being technical here because I just saw that a change was pushed this afternoon, which I have not pulled.

The ONLY change I made was to this section of the CMakeLists.txt:
```
if(MSVC AND RTAUDIO_IS_STATIC)
  #foreach(flag_var
  #    CMAKE_CXX_FLAGS CMAKE_CXX_FLAGS_DEBUG CMAKE_CXX_FLAGS_RELEASE
  #    CMAKE_CXX_FLAGS_MINSIZEREL CMAKE_CXX_FLAGS_RELWITHDEBINFO)
  #  if(${flag_var} MATCHES "/MD")
  #    string(REGEX REPLACE "/MD" "/MT" ${flag_var} "${${flag_var}}")
  #  endif(${flag_var} MATCHES "/MD")
  #endforeach(flag_var)
endif()
```

So to be clear, I am building and using the static library, but compiling it with /MD or /MDd because that's what CMake defaults to on all my other projects

**Comment by jkeller51** [comment]
[bufferWithClear.txt](https://github.com/thestk/rtaudio/files/4602287/bufferWithClear.txt)
[bufferWithCopy.txt](https://github.com/thestk/rtaudio/files/4602288/bufferWithCopy.txt)

```c++
/******************************************/
/*
  duplex.cpp
  by Gary P. Scavone, 2006-2007.

  This program opens a duplex stream and passes
  input directly through to the output.
*/
/******************************************/

#include "RtAudio.h"
#include <iostream>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <iomanip>

/*
typedef char MY_TYPE;
#define FORMAT RTAUDIO_SINT8

typedef signed short MY_TYPE;
#define FORMAT RTAUDIO_SINT16

typedef S24 MY_TYPE;
#define FORMAT RTAUDIO_SINT24

typedef signed long MY_TYPE;
#define FORMAT RTAUDIO_SINT32

typedef float MY_TYPE;
#define FORMAT RTAUDIO_FLOAT32
*/

typedef double MY_TYPE;
#define FORMAT RTAUDIO_FLOAT64

double* gExportOutput = nullptr;
double* gExportInput = nullptr;
uint32_t gOutputSize;

void usage( void ) {
  // Error function in case of incorrect command-line
  // argument specifications
  std::cout << "\nuseage: duplex N fs <iDevice> <oDevice> <iChannelOffset> <oChannelOffset>\n";
  std::cout << "    where N = number of channels,\n";
  std::cout << "    fs = the sample rate,\n";
  std::cout << "    iDevice = optional input device to use (default = 0),\n";
  std::cout << "    oDevice = optional output device to use (default = 0),\n";
  std::cout << "    iChannelOffset = an optional input channel offset (default = 0),\n";
  std::cout << "    and oChannelOffset = optional output channel offset (default = 0).\n\n";
  exit( 0 );
}

int inout( void *outputBuffer, void *inputBuffer, unsigned int nBufferFrames,
           double /*streamTime*/, RtAudioStreamStatus status, void *data )
{
  // Since the number of input and output channels is equal, we can do
  // a simple buffer copy operation here.
  if ( status ) std::cout << "Stream over/underflow detected." << std::endl;

  unsigned int *bytes = (unsigned int *) data;
  //memcpy( outputBuffer, inputBuffer, *bytes );
  memset(outputBuffer, 0, *bytes);

  delete[] gExportInput;
  delete[] gExportOutput;

  
    gExportOutput = new double[nBufferFrames*2];
    gExportInput = new double[nBufferFrames*2];
    gOutputSize = nBufferFrames;
    memcpy(gExportOutput, outputBuffer, *bytes);
    memcpy(gExportInput, inputBuffer, *bytes);
    

  return 0;
}

int main( int argc, char *argv[] )
{
  unsigned int channels, fs, bufferBytes, oDevice = 0, iDevice = 0, iOffset = 0, oOffset = 0;

  // Minimal command-line checking
  if (argc < 3 || argc > 7 ) usage();

  RtAudio adac(RtAudio::Api::WINDOWS_WASAPI);
  if ( adac.getDeviceCount() < 1 ) {
    std::cout << "\nNo audio devices found!\n";
    exit( 1 );
  }

  channels = (unsigned int) atoi(argv[1]);
  fs = (unsigned int) atoi(argv[2]);
  if ( argc > 3 )
    iDevice = (unsigned int) atoi(argv[3]);
  if ( argc > 4 )
    oDevice = (unsigned int) atoi(argv[4]);
  if ( argc > 5 )
    iOffset = (unsigned int) atoi(argv[5]);
  if ( argc > 6 )
    oOffset = (unsigned int) atoi(argv[6]);

  // Let RtAudio print messages to stderr.
  adac.showWarnings( true );

  // Set the same number of channels for both input and output.
  unsigned int bufferFrames = 512;
  RtAudio::StreamParameters iParams, oParams;
  iParams.deviceId = iDevice;
  iParams.nChannels = channels;
  iParams.firstChannel = iOffset;
  oParams.deviceId = oDevice;
  oParams.nChannels = channels;
  oParams.firstChannel = oOffset;

  if ( iDevice == 0 )
    iParams.deviceId = adac.getDefaultInputDevice();
  if ( oDevice == 0 )
    oParams.deviceId = adac.getDefaultOutputDevice();

  RtAudio::StreamOptions options;
  //options.flags |= RTAUDIO_NONINTERLEAVED;

  bufferBytes = bufferFrames * channels * sizeof( MY_TYPE );
  try {
    adac.openStream( &oParams, &iParams, FORMAT, fs, &bufferFrames, &inout, (void *)&bufferBytes, &options );
  }
  catch ( RtAudioError& e ) {
    std::cout << '\n' << e.getMessage() << '\n' << std::endl;
    exit( 1 );
  }

  // Test RtAudio functionality for reporting latency.
  std::cout << "\nStream latency = " << adac.getStreamLatency() << " frames" << std::endl;

  try {
    adac.startStream();

    char input;
    std::cout << "\nRunning ... press <enter> to quit (buffer frames = " << bufferFrames << ").\n";
    std::cin.get(input);

    // Stop the stream.
    adac.stopStream();

    // write export txt file
    std::ofstream file;
    file.open("buffer.txt");
    file << "Input:\n";
    for (uint32_t i = 0; i < gOutputSize; i++)
        file << std::setw(4) << i << "     " << std::setw(20) << gExportInput[i] << std::endl;
    file << "\n\nOutput:\n";
    for (uint32_t i = 0; i < gOutputSize; i++)
        file << std::setw(4) << i << "     " << std::setw(20) << gExportOutput[i] << std::endl;

    file.close();

    std::cout << "\nWrote to file buffer.txt\n";

    delete[] gExportInput;
    delete[] gExportOutput;

    
  }
  catch ( RtAudioError& e ) {
    std::cout << '\n' << e.getMessage() << '\n' << std::endl;
    goto cleanup;
  }

 cleanup:
  if ( adac.isStreamOpen() ) adac.closeStream();

  return 0;
}
```

**Comment by jkeller51** [comment]
For what it's worth
![image](https://user-images.githubusercontent.com/20546616/81458885-8573c200-9162-11ea-9205-5e04bc1908df.png)

**Comment by jkeller51** [comment]
I recorded the output of the test program, here is part of the signal I recorded. Very interesting:
![image](https://user-images.githubusercontent.com/20546616/81459661-b2c26f00-9166-11ea-9d36-8ac03f62075e.png)

The period from one burst to the next is 512 samples.

[outputMix.txt](https://github.com/thestk/rtaudio/files/4602395/outputMix.txt)
^ this is a .wav file of the above recording, but github wouldn't let me upload .wav. Just change the extension.

**Comment by MarcusTomlinson** [comment]
Does your output device have more than 2 channels by chance?

**Comment by MarcusTomlinson** [comment]
Could you please test if the following branch fixes your issue:
https://github.com/thestk/rtaudio/tree/issue-248

**Comment by jkeller51** [comment]
I've been testing on a pair of stereo headphones -- 2 channels.

I checked out branch issue-248 and ran the duplex test, the issue persists.

**Comment by MarcusTomlinson** [comment]
Next question: Do any of the formats work? Such as RTAUDIO_FLOAT32 or any of the RTAUDIO_SINT variants?

**Comment by jkeller51** [comment]
Tested all SINT variants, 8 16 24 32, and RTAUDIO_FLOAT32 and the issue persists in each case.

**Comment by MarcusTomlinson** [comment]
It really sucks that I can’t recreate this. I had a theory that it could have something to do with multichannel audio out, like if your device is a studio grade interface or supports surround sound out, but you’re saying this is not the case right?

**Comment by jkeller51** [comment]
I don't think so, I'm just using my laptop's headphone jack. If there is some way to prove how many audio outputs the laptop has, I don't know where to find it.

**Comment by MarcusTomlinson** [comment]
Could you please break on line 4840 of RtAudio.cpp:

`stream_.nDeviceChannels[mode] = deviceFormat->nChannels;`

and line 4770:

`stream_.nDeviceChannels[mode] = deviceFormat->nChannels;`

and let me know what the value of deviceFormat->nChannels is for each?

**Comment by jkeller51** [comment]
Aha! 

2 input channels.

8 output channels.

**Comment by MarcusTomlinson** [comment]
Ah good, getting somewhere thanks! I’ll pursue this theory further then.

**Comment by MarcusTomlinson** [comment]
Could you please test if https://github.com/thestk/rtaudio/pull/249 fixes the issue now.

**Comment by MarcusTomlinson** [comment]
This is how I ended up reproducing this:

1. Selected my output device, then clicked "Configure".
<img width="448" alt="Screenshot 2020-05-10 at 11 55 44" src="https://user-images.githubusercontent.com/7335138/81497302-7e10fd80-92b5-11ea-9b74-cd1ee91621cf.png">

2. Selected "5.1 Surround", then clicked "Next".
<img width="556" alt="Screenshot 2020-05-10 at 11 55 55" src="https://user-images.githubusercontent.com/7335138/81497310-86693880-92b5-11ea-9c18-67e74d280d95.png">

3. Selected "Center" only, then clicked "Next".
<img width="552" alt="Screenshot 2020-05-10 at 11 56 03" src="https://user-images.githubusercontent.com/7335138/81497313-89fcbf80-92b5-11ea-8fd3-1ffa2df04449.png">

4. Left this page as is, clicked "Next", then "Finish".
<img width="552" alt="Screenshot 2020-05-10 at 11 56 16" src="https://user-images.githubusercontent.com/7335138/81497320-93862780-92b5-11ea-9816-58e9329b1297.png">

5. Then ran the duplex test application again (`duplex.exe 2 48000`) -> Noise.

**Comment by jkeller51** [comment]
You've done it!

The updated branch issue-248 solves the issue.

**Comment by MarcusTomlinson** [comment]
Thanks for your help in tracking this down @jkeller51!

**Comment by MarcusTomlinson** [comment]
https://github.com/thestk/rtaudio/pull/249 is still waiting for a review. Re-opening.
