### ISSUE TITLE
CMake deprecation warning on `cmake_policy(SET CMP0042 OLD)`

### ISSUE THREAD

**Issue by nyanpasu64** [thestk/rtaudio#253]
https://github.com/thestk/rtaudio/blob/a1ddca0c452c05a5f5d0b36d5a5648296061d4e2/CMakeLists.txt#L207

When I run CMake, I get the output:

> CMake Deprecation Warning at 3rdparty/rtaudio/CMakeLists.txt:207 (cmake_policy):
>   The OLD behavior for policy CMP0042 will be removed from a future version
>   of CMake.
> 
>   The cmake-policies(7) manual explains that the OLD behaviors of all
>   policies are deprecated and that a policy should be set to OLD only under
>   specific short-term circumstances.  Projects should be ported to the NEW
>   behavior and not rely on setting a policy to OLD.

I don't fully understand what CMP0042 does, but is it possible to rewrite CMakeLists to remove it?

I'm running cmake version 3.17.2.

**Comment by radarsat1** [comment]
@berkus 
3a3d648108cdaa53d1199aa3c15a4b8878693f65

**Comment by berkus** [comment]
I believe this policy can be removed now [according to docs](https://cmake.org/cmake/help/latest/policy/CMP0042.html).

However, it might require making sure [INSTALL_NAME_DIR](https://cmake.org/cmake/help/latest/prop_tgt/INSTALL_NAME_DIR.html#prop_tgt:INSTALL_NAME_DIR) is unset when building.
