### ISSUE TITLE
Using arbitrary channels on playback and recording

### ISSUE THREAD

**Issue by monocasual** [thestk/rtaudio#260]
Assuming I got the `RtAudio::StreamParameters` usage right, `nChannel` defines the number of inputs (or outputs) and `firstChannel` sets the starting point in the channel list to read from (or write to). As a result, such design allows only consecutive channels: `0`, `1,2`, `5,6,7`, ... . What if I have an audio interface with, say, 6 input channels and I want to record a stereo stream from channel 2 and channel 5 instead?

**Comment by garyscavone** [comment]
Two options … take the input cable plugged into channel 5 and instead plug it into channel 3 (or plug those two cables into channels 1 and 2 and don’t use the offset parameter). Or record all channels from 2 to 5 but only save 2 and 5.

**Comment by monocasual** [comment]
> Or record all channels from 2 to 5 but only save 2 and 5.

I think I'll go with this one. Thanks @garyscavone for the help.
