### ISSUE TITLE
Possible conversion bug

### ISSUE THREAD

**Issue by bflamig** [thestk/rtaudio#271]
Around line 10584 in the RtAudio.cpp file there is the following code, which is supposed to convert a float32 sample coming in, into a int32 sample, changing scales along the way:

```
    else if (info.inFormat == RTAUDIO_FLOAT32) {
      Float32 *in = (Float32 *)inBuffer;
      for (unsigned int i=0; i<stream_.bufferSize; i++) {
        for (j=0; j<info.channels; j++) {
          out[info.outOffset[j]] = (Int32) std::min(std::lround(in[info.inOffset[j]] * 2147483648.f), 2147483647L);
        }
        in += info.inJump;
        out += info.outJump;
      }
    }

```

However, if the input number is 1.0f, you'll get back an int32 of -2147483648. At least, that's the case using MSVC 2019 C++ compiler. One would think you should get back a value of +2147483647. That would be the reasonable choice.

Note that I didn't test this in-situ, but rather pulled out the following line and tested it using various input values:

`out[info.outOffset[j]] = (Int32) std::min(std::lround(in[info.inOffset[j]] * 2147483648.f), 2147483647L);`

which I changed to something like:

```
Float32 src = 1.0f;
Int32 dest = (Int32) std::min(std::lround(src * 2147483648.f), 2147483647L);
```

I discovered this error after investigating different conversion scaling strategies in code like PortAudio and RtAudio.

**Comment by AndrewBelt** [comment]
Fixed by https://github.com/thestk/rtaudio/pull/279

**Comment by bflamig** [comment]
Okay, thanks. I'll check it out when I get some time.
