### ISSUE TITLE
RtApiPulse::probeDeviceOpen does not work with unusual sample rates.

### ISSUE THREAD

**Issue by ic-scm** [thestk/rtaudio#272]
The RtApiPulse::probeDeviceOpen function always uses a hardcoded list of "supported" sample rates (https://github.com/thestk/rtaudio/blob/master/RtAudio.cpp#L8486) and returns an error if the requested input sample rate is not on that list. I don't understand the point of this restriction, the rest of the library and PulseAudio itself seem to be perfectly capable of working with any other sample rate.

I removed the restriction myself, as seen in my ugly fix here: https://github.com/ic-scm/rtaudio/commit/483b69fa11a833e35442fde1072579c17170e724 (built on top of version 5.1.0, the latest commit on master does not seem to work correctly, at least with my system and configuration).
With this fix I am now able to play at any other sample rate like 32728Hz or 12000Hz, it sounds perfectly fine and doesn't cause any other problems or errors.

**Comment by garyscavone** [comment]
I assume the Pulse API provides automatic sample rate conversion but that is not necessarily the case for most of the other APIs. That said, there might be an inconsistency in the Pulse API implementation (which I didn’t make) because in the past I tried to first use the sample rate passed in the openStream() function and then, if it doesn’t work, either report an error or move to the next closest rate that is supported.

**Comment by ic-scm** [comment]
Does this really solve the issue? Every unusual sample rate should be supported, not just 192000Hz along with the ones that were already on the list.

**Comment by ic-scm** [comment]
Ah, okay, I noticed that you merged my commit there. I would have expected that you would prefer to implement a cleaner solution to that, but I guess it'll work if you're fine with that.

**Comment by radarsat1** [comment]
If someone wants to go ahead and remove the "supported samplerates" in a nice way then I can probably approve it, but I don't have time to do the work right now.

So, I'm open to suggestions/PRs but happy to get a work-around in place for now ;)
