### ISSUE TITLE
duplex mode causes underrun with ALSA on ubuntu on Parallels Desktop

### ISSUE THREAD

**Issue by tomoyanonymous** [thestk/rtaudio#282]
Hello. I am using RtAudio with ALSA backend on Ubuntu on Parallels Desktop.

I had no problem when I was using RtAudio to output sounds but I encountered an audio underrun when I used it for processing input and passing sound into output.

Increasing a buffer size did not work, however, with a debugger attached, once the audio callback is interrupted by setting a breakpoint and resumed, the underrun completely disappeared.

`RtApiAlsa::probeDeviceOpen` seems to always fail with an internal call of `snd_pcm_link` function.

The result of `./duplex 1 44100` `./audioprobe` were like below.
Parallels desktop seems to provide a virtual audio device always with 32 inputs & 32 outputs as a default device regardless of an actual choice of the audio device in VM configuration. 

```sh
./duplex 1 44100

RtApiAlsa::probeDeviceOpen: unable to synchronize input and output devices.

Stream latency = 0 frames

Running ... press <enter> to quit (buffer frames = 512)

RtApiAlsa::callbackEvent: audio write error, underrun.

Stream over/underflow detected.

RtApiAlsa::callbackEvent: audio write error, underrun.

Stream over/underflow detected.

...
```

```sh
./audioprobe

RtAudio Version 5.1.0

Compiled APIs:
  Linux ALSA

Current API: Linux ALSA

Found 3 device(s) ...

Device Name = default
Device ID = 0
Probe Status = Successful
Output Channels = 32
Input Channels = 32
Duplex Channels = 32
This is the default output device.
This is the default input device.
Natively supported data formats:
  16-bit int
  24-bit int
  32-bit int
  32-bit float
Supported sample rates = 4000 5512 8000 9600 11025 16000 22050 32000 44100 48000 88200 96000 176400 192000
Preferred sample rate = 48000

RtApiAlsa::getDeviceInfo: snd_pcm_open error for device (hw:0,0), Device or resource busy.


RtApiAlsa::getDeviceInfo: snd_pcm_open error for device (hw:0,0), Device or resource busy.


Device Name =
Device ID = 1
Probe Status = UNsuccessful

Device Name = hw:Intel 82801BA-ICH2,1
Device ID = 2
Probe Status = Successful
Output Channels = 0
Input Channels = 2
Duplex Channels = 0
This is NOT the default output device.
This is NOT the default input device.
Natively supported data formats:
  16-bit int
Supported sample rates = 48000
Preferred sample rate = 48000
```

Host Computer: MacbookPro 16inch 2019 /  macOS 10.15.5
Parallels Desktop version 16.0.0

I could not find to solve this problem and maybe this is Parallels Desktop's issue but just for a report.
Thanks.

**Comment by garyscavone** [comment]
I'm closing this, as it seems to be either related to Parallels or a configuration issue (but not RtAudio).
