### ISSUE TITLE
Pipewire JACK buffer problem

### ISSUE THREAD

**Issue by cropinghigh** [thestk/rtaudio#286]
I'm using Manjaro with Pipewire as audio server. If i don't use pipewire-jack, i can use RtAudio without problems with pipewire-pulse. But if i install pipewire-jack and pipewire-jack-dropin, i can't use both testing programs from this repository(like playraw) and software using RtAudio(like SDRPlusPlus). 
If i comple code from this repo and run "./playraw 2 48000 .../audio.raw", it tries to put audio to Firefox instead of default audio sink. Can be fixed by adding device ID at the end. But then, randomly i'm getting endless 
"RtApiCore::callbackEvent(): the JACK buffer size has changed ... cannot process!"
messages without audio(if i add line "printf("Test! buffSize: %u, nframes: %lu\n", stream_.bufferSize, nframes);" after error, i got "Test! buffSize: 1024, nframes: 2048"), 
or it's running without problems and playing audio.

**Comment by garyscavone** [comment]
A wishlist issue already exists for this ... closing.

**Comment by runiq** [comment]
@garyscavone May I ask where? There are currently only two issues with the `wishlist` label, and neither seems to be related to this…
