### ISSUE TITLE
asiolist.cpp has an unused variable

### ISSUE THREAD

**Issue by dyfer** [thestk/rtaudio#287]
Hello,

~~I was trying to add building with ASIO API as a "feature" in RtAudio's VCPKG port and it seems that VCPKG insists on having Debug builds with the `-Werror` flag. IIUC this causes the build to fail, because of an unused variable in [asiolist.cpp](https://github.com/thestk/rtaudio/blob/master/include/asiolist.cpp#L169).~~

I was able to add `-Wno-unused` in VCPKG build to make the build succeed. Still, should that unused variable be removed? I'd be happy to make a PR but I'm not sure if that's desirable.

**Comment by autoantwort** [comment]
I didn't know that you have created an issue, I have created the PR #288 :D

**Comment by dyfer** [comment]
Fixed in #288
