### ISSUE TITLE
`pa_strerror` symbol not found link error.

### ISSUE THREAD

**Issue by Parakleta** [thestk/rtaudio#293]
Not sure if this is a FreeBSD issue specifically, but I found that I got link errors when just `pulse-simple` was linked since the `pa_strerror` symbol could not be found.  This symbol is in the base `pulse` library.  I'm not sure if this is a version or distribution thing or what.

To get a successful build on FreeBSD I needed to define the following environment variables:

LDFLAGS='-L/usr/local/lib -lpulse'
CFLAGS='-I/usr/local/include'

**Comment by ntonnaett** [comment]
CMake and Meson check also for the pulse dependency. You could try if it works when you build with one of them. Meson doesn't produce a pkgconfig file yet. But you can use it as a subproject.
