### ISSUE TITLE
[REQ] Set license on GH

### ISSUE THREAD

**Issue by forart** [thestk/rtaudio#315]
Hi there, this project is awesome !

Since we've collected it in our [HyMPS project list](https://github.com/forart/HyMPS) (in the [AudioLIBs section](https://github.com/forart/HyMPS/blob/main/AudioLIBs.md)), can you please set licensing terms on this git ?

Thanks in advance !

**Comment by radarsat1** [comment]
the license is [here](https://github.com/thestk/rtaudio/blob/master/LICENSE)

**Comment by forart** [comment]
Hi there, thanks for reply.

If we understood correctly, the license is similar but not MIT, right ?
This means that is not officially supported by GH...

Our "problem" is that it does not generates the correct badge: 
![](https://flat.badgen.net/github/license/thestk/rtaudio/?label=LICENSE)
(generate string: https://flat.badgen.net/github/license/thestk/rtaudio/?label=LICENSE)

Thanks anyway for your work !

**Comment by garyscavone** [comment]
Closing.
