### ISSUE TITLE
Error: RtApiCore::probeDeviceOpen: the device (1) does not support the requested channel count.

### ISSUE THREAD

**Issue by daankets** [thestk/rtaudio#319]
When opening a playback stream on a device (macOs, CoreAudio, MacBook Pro) that has a different number of channels than the corresponding input device (if duplex), RtAudio always throws this error on me. It does not happen when I use a device that does have an equal number of channels (Focusrite Scarlett 2i2).

I'm using the library via the [audify](https://github.com/almoghamdani/audify), but the error seems to be caused by RtAudio itself. Any ideas or known workarounds?

**Comment by garyscavone** [comment]
I'm not sure this is an RtAudio problem but perhaps I'm not understanding the problem. I just revised the duplex.cpp test example to use a single-channel input device (the device only supports 1 channel of input) and a different device for two-channel output and it seemed to work.

**Comment by daankets** [comment]
Hi @garyscavone thanks for your reply. I have just been able to find the root cause of the issue: a wrong offset caused the device id for the input device to be reused for the output device :cold_sweat:... I'm closing the issue.
