### ISSUE TITLE
Understanding audioprobe output, and sending 1 channel mic input to stereo 2 channel output simultaneously in raspberry pi zero

### ISSUE THREAD

**Issue by mahaju** [thestk/rtaudio#328]
Hi I'm sorry if this is something obvious, but I was just introduced to RtAudio library and have some confusions

I downloaded the RtAudio tar.gz from "http://www.music.mcgill.ca/~gary/rtaudio/", and I am using it in raspberry pi zero W. I built it using ./configure --with-alsa.

I have a generic looking USB sound card connected to the pi zero (the USB sound card has Ucommerce written on it and I can't find much information about it). If I run the audioprobe sample program, I get this result:

> RtAudio Version 5.1.0
> 
> Compiled APIs:
>   Linux ALSA
> 
> Current API: Linux ALSA
> 
> Found 3 device(s) ...
> 
> Device Name = hw:bcm2835 HDMI 1,0
> Device ID = 0
> Probe Status = Successful
> Output Channels = 8
> Input Channels = 0
> Duplex Channels = 0
> This is NOT the default output device.
> This is NOT the default input device.
> Natively supported data formats:
>   16-bit int
> Supported sample rates = 8000 9600 11025 16000 22050 32000 44100 48000 88200 96000 176400 192000
> 
> Device Name = hw:USB PnP Sound Device,0
> Device ID = 1
> Probe Status = Successful
> Output Channels = 2
> Input Channels = 1
> Duplex Channels = 1
> This is NOT the default output device.
> This is NOT the default input device.
> Natively supported data formats:
>   16-bit int
> Supported sample rates = 44100 48000
> 
> Device Name = default
> Device ID = 2
> Probe Status = Successful
> Output Channels = 32
> Input Channels = 32
> Duplex Channels = 32
> This is NOT the default output device.
> This is NOT the default input device.
> Natively supported data formats:
>   16-bit int
>   24-bit int
>   32-bit int
>   32-bit float
> Supported sample rates = 4000 5512 8000 9600 11025 16000 22050 32000 44100 48000 88200 96000 176400 192000
> 

I can understand what 0 and 1 are, but what is device ID 2? Can I just ignore it? I don't understand how this relates with the output of aplay -l and aplay -L. For exampl, aplay -l give me 

> **** List of PLAYBACK Hardware Devices ****
> card 0: b1 [bcm2835 HDMI 1], device 0: bcm2835 HDMI 1 [bcm2835 HDMI 1]
>   Subdevices: 8/8
>   Subdevice #0: subdevice #0
>   Subdevice #1: subdevice #1
>   Subdevice #2: subdevice #2
>   Subdevice #3: subdevice #3
>   Subdevice #4: subdevice #4
>   Subdevice #5: subdevice #5
>   Subdevice #6: subdevice #6
>   Subdevice #7: subdevice #7
> card 1: Device [USB PnP Sound Device], device 0: USB Audio [USB Audio]
>   Subdevices: 1/1
>   Subdevice #0: subdevice #0
> 

What I actually want to do is get audio from the microphone, perform some DSP operations on it and pass it through to the speakers. From audioprobe I see that for device 1, input channel  = 1, which I suppose means that the mic input on this sound card is single channel. I am OK with this, but I need to know how to send this single channel mic data simultaneously to two output channels.

I see that running
./duplex 1 48000 1 1
sends mic input to the left channel speaker, but the right channel is muted. I also see that for device 1, Duplex channels = 1

What does this mean? Is this only capable of sending left channel mic data to left channel speaker at the hardware level, or is it possible to tweak some settings in the duplex sample code to send mic data simultaneously to both the left and right channel outputs?

**Comment by mahaju** [comment]
@garyscavone I skimmed through all the questions here but I can't find where this has been discussed. But this is definitely doable? I am asking because using channel number = 2 on device 1 causes error and program closes (which I suppose is because audioprobe shows Duplex Channels = 1). Can I use number of channels as 1, but assume outputBuffer in the callback function as interleaved left and right channel and change the " memcpy( outputBuffer, inputBuffer, *bytes );" line? Is this the right way to think about this?

**Comment by radarsat1** [comment]
@mahaju can you close this issue if it is resolved?  Otherwise I am not sure if there is any action to take here.  Regards.
