### ISSUE TITLE
WASAPI Error in IAudioCaptureClient::GetBuffer

### ISSUE THREAD

**Issue by jkeller51** [thestk/rtaudio#333]
Hi,

After pulling recent changes to this repo (https://github.com/thestk/rtaudio/commit/5dbffa2628a460d2e101a78ee7e57a83fed0dbc4), I couldn't get an audio stream going with WASAPI.

Specs:
Windows 10 21H1
Intel i7--7700HQ
16 GB RAM
Realtek audio drivers

The WASAPI thread fails here:
```c++
      // Get capture buffer from stream
      hr = captureClient->GetBuffer( &streamBuffer,
                                     &bufferFrameCount,
                                     &captureFlags, NULL, NULL );
      if ( FAILED( hr ) ) {
        errorText = "RtApiWasapi::wasapiThread: Unable to retrieve capture buffer.";
        goto Exit;
      }
```

The error code (`hr`) is `AUDCLNT_E_DEVICE_INVALIDATED`.

WASAPI works as of commit https://github.com/thestk/rtaudio/commit/2f2fca4502d506abc50f6d4473b2836d24cfb1e3, so I think it's related to the recent IAudioClient3 code.

**Comment by garyscavone** [comment]
I just tested in Windows 10 and I didn't run into that problem.

**Comment by MarcusTomlinson** [comment]
I'm going to close this as none of us can reproduce the issue. Please feel free to re-open if you're able to provide a reproducible example. Thanks!
