### ISSUE TITLE
Exporting of RtAudioError gives warning with Visual Studio C++

### ISSUE THREAD

**Issue by ntonnaett** [thestk/rtaudio#334]
When compiling 5.2.0 with Visual Studio it warns about export RtAudioError because it's derived from str::runtime_error:
https://github.com/mesonbuild/wrapdb/runs/4304083253?check_suite_focus=true#step:6:134

Isn't exporting it actually unnecessary because the implementation is in the header file?

**Comment by garyscavone** [comment]
This is no longer relevant, since exceptions have been removed.
