### ISSUE TITLE
WASAPI: data races and synchronization issues

### ISSUE THREAD

**Issue by petiaccja** [thestk/rtaudio#335]
Hi,

I had some issues in the WASAPI `stopStream`, with the processing thread's handle being freed multiple times. It seems that  `stopStream` is being called twice, concurrently: once from the destructor and once from the temporary thread created by the processing thread after the callback returned 1.

Solving the problem looks more complicated:
- stream_.state should be atomic to ensure proper synchronization between `stopStream`, `isStreamRunning`, `wasapiThread`
- the closing procedure should be protected by a mutex so that only one thread executes it
- the `stopStream` call from the main thread should only exit after the thread handle was updated to NULL from any thread

It would probably be better to use `std::async` and the associated `future` to host the processing thread. Also, these problems might affect the other APIs, I only looked at WASAPI.

Are there any plans to address this?

**Comment by garyscavone** [comment]
Thank you for the careful analysis. I think this is a specific issue with the WASAPI implementation. A good approach to solve it may be to see what is done in the other APIs (one using an audio API closest to wasapi). So far, I haven't touched the WASAPI implementation ... that has been handled by @MarcusTomlinson.

**Comment by MarcusTomlinson** [comment]
Yeah thanks for this @petiaccja!

There is a stream status check in `stopStream` that should allow it to be called multiple times, though it appears that can be racy (as you've said). I suspect all that's really needed here is a mutex protecting `stopStream` (and `abortstream` for that matter).

I'll have a look when I get some time.

**Comment by petiaccja** [comment]
Thanks guys for taking a look. 

@MarcusTomlinson yes, locking the entire `stopStream` from entry to return probably solves the race condition problem. The processing thread should also be signaled through atomics (or at least volatile) because, theoretically, stream_.state could be kept in a register and then changes from the main thread won't be visible in the processing thread.

I dropped a PR on how it could be done with std::async, which is a bit different than the current implementation, but I find it easier to reason about its correctness.
PR: https://github.com/thestk/rtaudio/pull/336

**Comment by MarcusTomlinson** [comment]
> I had some issues in the WASAPI `stopStream`, with the processing thread's handle being freed multiple times.

This core issue should be resolved now.

As for the wider proposed architectural changes (making stream_.state atomic etc), I'll leave that to the core devs to ponder :)
