### ISSUE TITLE
Check and Fix (Clipping/Saturation) for float32/64 samples?

### ISSUE THREAD

**Issue by hayguen** [thestk/rtaudio#343]
the header simply writes

> static const RtAudioFormat RTAUDIO_FLOAT32 = 0x10; // Normalized between plus/minus 1.0.
> static const RtAudioFormat RTAUDIO_FLOAT64 = 0x20; // Normalized between plus/minus 1.0.

is there any check or correction, if the sample values lie outside plus/minus 1.0 ?
would be great, if documentation or the comments in the header file would drop a note on this.

**Comment by garyscavone** [comment]
No, there are no checks for values beyond plus/minus 1.0. I just added a comment in the header file.
