### ISSUE TITLE
macOS 10.15 - undeclared identifier 'kAudioObjectPropertyElementMain'

### ISSUE THREAD

**Issue by fferri** [thestk/rtaudio#355]
Trying to build latest rtaudio from git on macOS 10.15.7.

I get this error:

/Users/me/Dev/rtaudio-test/external/rtaudio/RtAudio.cpp:596:43: error: use of
      undeclared identifier 'kAudioObjectPropertyElementMain'; did you mean
      'kAudioObjectPropertyElementName'?
                                          KAUDIOOBJECTPROPERTYELEMENT };
                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
                                          kAudioObjectPropertyElementName
/Users/me/Dev/rtaudio-test/external/rtaudio/RtAudio.cpp:583:39: note: expanded from
      macro 'KAUDIOOBJECTPROPERTYELEMENT'
  #define KAUDIOOBJECTPROPERTYELEMENT kAudioObjectPropertyElementMain
                                      ^

I have to either:

- set(CMAKE_OSX_DEPLOYMENT_TARGET 10.11) or less in my CMakeLists.txt
- comment out lines in 580~584 so that the one _without_ `kAudioObjectPropertyElementMain` is used

Possibly related to #351 and/or #345

**Comment by garyscavone** [comment]
I am closing this, as I haven't seen other reported problems and it works fine on my system (though I don't use cmake). If there needs to be a build system fix, please submit a PR.
