### ISSUE TITLE
PulseAudio playback stream name

### ISSUE THREAD

**Issue by SeeLook** [thestk/rtaudio#36]
As long as "Record" supports streamName parameter "Playback" is not.
Any PulseAudio GUI displays then 
Record:AppName and Playback:RtAudio
Small thing but maybe.

Here is a patch:

diff -r a0f06e0ef24e src/libs/sound/rt/RtAudio.cpp
--- a/src/libs/sound/rt/RtAudio.cpp	Wed Apr 08 11:00:37 2015 +0200
+++ b/src/libs/sound/rt/RtAudio.cpp	Thu Apr 09 11:48:15 2015 +0200
@@ -8499,7 +8499,7 @@
     }
     break;
   case OUTPUT:
-    pah->s_play = pa_simple_new( NULL, "RtAudio", PA_STREAM_PLAYBACK, NULL, "Playback", &ss, NULL, NULL, &error );
+    pah->s_play = pa_simple_new( NULL, streamName.c_str(), PA_STREAM_PLAYBACK, NULL, "Playback", &ss, NULL, NULL, &error );
     if ( !pah->s_play ) {
       errorText_ = "RtApiPulse::probeDeviceOpen: error connecting output to PulseAudio server.";
       goto error;

**Comment by garyscavone** [comment]
Fixed in latest commit.
