### ISSUE TITLE
No driver while opening input buffer

### ISSUE THREAD

**Issue by AlexBolotsin** [thestk/rtaudio#364]
Hi,
I have RtAudio 5.0 (I guess) as part of UnrealEngine Epic Online Subsystem as VoiceChat input API.

There is issue that some players experience. An error while trying to open input buffer of a certain device:
 ```[2022.07.27-20.12.16:473][423]LogEOS: Error: [LogAudioCaptureCore] RtApiDs::probeDeviceOpen: error (No driver) creating input buffer (VR HEADSET (Valve VR Radio & HMD Mic))!```
What can cause it? I see it uses DirectSound is there some missing dll or such? Really lost here.
Thanks!

**Comment by garyscavone** [comment]
The DirectSound code hasn't changed substantially in many years. And it is odd that it fails at that particular point in the code, after several other calls to the DirectSoundCapture system. I have to assume it is a driver issue. Perhaps you can try reinstalling the device driver.

**Comment by AlexBolotsin** [comment]
After reinstalling windows a player got mic fixed. It's definetely not a RtAudio issue.
