### ISSUE TITLE
How to perform input/output syncing

### ISSUE THREAD

**Issue by SeeLook** [thestk/rtaudio#37]
I dared to put a question here, sorry if it is not good place but seems to be the only place....

I have problems with synchronization of input and output devices in duplex mode when they are different.
Problems occur either with my app and with duplex test.
After while (10-20s) of properly forwarding input to output some glitches are audible (like trrrrr :-) ).
Buffer size is set to 512 or 1024 (it makes no difference)
Interesting is a fact that it occurs under Linux ALSA but with PulseAudio it works well.
Also under Windows (7) WASAPI gives glitches but DirectSounds and ASIO not (In ASIO case set stream option flag to RTAUDIO_MINIMIZE_LATENCY helped). 

It seems like sound servers (WASAPI seems to imitate DS) take care about syncing but working on "raw" devices moves responsibility on developer. (I'm guessing this)

Is it difficult to sync?

**Comment by garyscavone** [comment]
I don’t think you should expect two different devices to be synchronized in duplex mode.  If you want synchrony, use the same device for both input and output.

—gary

**Comment by SeeLook** [comment]
So, please give me a clue what will be the best solution for situation I have.
(I will try to be short)

I have an app (nootka.sf.net). I wrote You last year about my troubles with two instances of RtAudio separately for in and out. You advised me to have single instance, so obediently I implemented it. 

So, the app gets input data to perform pitch detection on them. Sometimes user wants to listen to a sound (a note). To achieve that, there is a duplex callback. Input is processed and output ignored and when playing is demanded input is ignored and output data is sent.
The app is dedicated mostly to guitarists so it is often a case when one has guitar plugged into some external sound card and wants to have output sound in built-in card (another device).
As long as the forwarding input to output is just an additional option, 
the most important condition is: input data have to be consistent. 
But it is a rule - when forwarding cracks, the input is usually chopped (sometimes just a bit and it causes detecting single note a few times)
I'm close to release new version of Nootka but I stopped with that, 
so maybe You can give me some clear idea.
Thank You in advance

**Comment by garyscavone** [comment]
The use of a single instance is the best option, as that allows you to use the same device in synchrony.  I think the user should be discouraged from using two different audio devices with your app, as they inevitably run at slightly different rates (even when set to the same rate) and after a while will likely get a little out of sync. But perhaps your problem isn’t necessarily a synchrony problem but some sort of issue with the driver or underlying API (or with how RtAudio uses that API). ALSA has a lot of functions in its API and perhaps there is a better way to code the case of using two different devices.

With ASIO, you can only use a single device at a time, so I’m not surprised it works without a problem.  The WASAPI implementation in RtAudio is relatively new and there are still things that need to be fixed (such as the sample rate conversion).  I’m surprised that DirectSound seems to work, as that is the poorest of all the APIs.

—gary

**Comment by SeeLook** [comment]
Thank You so much.
It gives me more wide view on my situation.
I think, the best way to solve Nootka problems will be to get rid of input forwarding and opening sound stream for input only and when playing is required close it and open for output.
Opening/closing I tested well with those two instances - it works fast enough and even if output clicks sometimes at start it is bearable.
I may leave option for forwarding if in & out are the on same device but I can't demand from users to avoid using multiple devices - I'm doing it myself in most cases.
And I tested it once more - multiple devices work on ASIO - I may select different input and output from its console - all works pretty good. One of testers reported me that it works even with two different ASIO drivers (ASIO4ALL and guitar sound card dedicated one) - input consistency was tested for long time.
Maybe it is worthy to write about syncing more in doc.

Thank You once again.
Tomasz
.

**Comment by VincentBruinink** [comment]
Because both the input and output device has its own clock the input and output buffers will shift in time. You can solve this by initiating two instances of RTAudio. One for input and one for the output. Then setup a callback for both the input and output. Make sure you have the same buffer length for input / output. You use this for reference. Then you have to setup two microseconds timers. One for the input and one for the output. Each time the input and output callback gets called you calculate the time difference between the current call and the previous call. that way you can calculate the real samplerate. Then you can calculate the offset between the input and output samplerate and resample the input buffer to match the output rate. There are several good resamplers on the net you can use.
