### ISSUE TITLE
[ask question] Pass sample rate and channel count to the callback.

### ISSUE THREAD

**Issue by fasxmut** [thestk/rtaudio#377]
I dont know where to ask question, so I ask here.

```cpp
int my_callback(void * out, void * in, std::uint32_t frames, double time, RtAudioStreamStatus status, void * user_data)
{
        return 0;
}

audio.openStream(&out_param, nullptr, RTAUDIO_FLOAT64, sample_rate, &frames, my_callback, user_data);
```

I can not find way to get the sample rate and channel count in the `my_callback` function, so I pass them through user_data, but in this way, the data is sent twice by `openStream`. Do you have better solution?

**Comment by garyscavone** [comment]
Passing those values via the user_data pointer is normal. I'm not quite sure what you mean by "data is sent twice."
