### ISSUE TITLE
[question] Is blocking playback no longer supported?

### ISSUE THREAD

**Issue by bignick26** [thestk/rtaudio#380]
Not mentioned anywhere in the doc and no longer compatible with old example code: http://web.mit.edu/carrien/Public/speechlab/marc_code/ADAPT_VC/rtaudio/doc/html/index.html#playbackb

**Comment by garyscavone** [comment]
Blocking playback was removed many releases ago. The current release is 5.2, while the documentation you point to (which is not maintained by this project), is 3.0.

**Comment by bignick26** [comment]
Copy, thanks for the fast response. An opinion that you didn't ask for: I'd love to use/contribute to the project, but I'm a noob and callbacks functions are intimidating. I imagine most of the other users/contributors here are audio gurus, but since I am coming from a background in SDR, the last of my concerns is performance and blocking playback functionality was very desirable to test the output of signal processing algorithms. As I get more experience though I'll probably revisit this project. Thanks again
