### ISSUE TITLE
Separate backend in different headers

### ISSUE THREAD

**Issue by lp35** [thestk/rtaudio#383]
Hi,

I know that rtaudio is a single hpp/cpp library but still.
Today, we have CMake as build system for c/c++, and it is widely used.

While digging to find a bug in RTAudio, I've found very difficult to navigate/search into the code. My suggestion is to separate each backend in their own hpp/cpp.

```
rtaudio.hpp
rtaudio.cpp

backend/rtjack.hpp
backend/rtjack.cpp


backend/rtalsa.hpp
backend/rtalsa.cpp
```

This will lead to better separation of the code, easier tracing of backend modification throught git (as you can select history by file), and make the life of contributors easier.

I can make a PR for this.

Thanks!

**Comment by garyscavone** [comment]
Sorry, but I'm not interested in this. I greatly prefer having everything confined to two files.
