### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [thestk/rtaudio#387]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [ASIOInit](https://github.com/thestk/rtaudio/blob/8f8250e311946b6b831357bdd6a030db3b75c057/include/asio.cpp#L48 "ASIOInit function")
- [RtAudio::openRtApi](https://github.com/thestk/rtaudio/blob/406e1420977218968283b218c5e159f00503205e/RtAudio.cpp#L521 "RtAudio::openRtApi function")

**Comment by garyscavone** [comment]
ASIOInit is a function in the ASIO API ... I'm not changing that. It is true that as currently used, the check in RtAudio::openRtApi() is not necessary. However, the code could be changed in the future such that openRtApi() is called from another function (not just the constructor) and there might be an instance of rtapi allocated. So, I don't see the harm in leaving it as is.
