### ISSUE TITLE
Build problem with MSYS2 + MinGW

### ISSUE THREAD

**Issue by killkrt** [thestk/rtaudio#39]
Hi,

I've tried to compile RtAudio with MSYS2 + MinGW, but I got these errors:

`/rtaudio/RtAudio.cpp:3878:73: error: 'roundf' was not declared in this scope
   outSampleCount = ( unsigned int ) roundf( inSampleCount * sampleRatio );`

`/rtaudio/tests/duplex.cpp:58:3: error: 'uint32_t' was not declared in this scope
   uint32_t *bytes = (uint32_t *) data;`

It turned out that to solve easily these errors (without changes the code) it is enough to add `-std=c++11` to the `CMAKE_CXX_FLAGS` 

Anyway I think it would be better to include the right headers.

System information:
OS: Windows 7 SP1 64bit
MSYS2 with the following package installed: mingw-w64-x86_64-gcc mingw-w64-x86_64-gdb git vim make mingw-w64-x86_64-cmake-git mingw-w64-x86_64-pkgconf

**Comment by garyscavone** [comment]
The uint32_t issue was fixed a few days ago.  I don't want to require C++11.  Can you figure out what header is needed for the roundf() function? I don't have access to a Windows system.

**Comment by radarsat1** [comment]
I think roundf() was introduced in C99, not sure which C++, but maybe C++11.  In any case, can't we just replace it with `(unsigned int)(inSampleCount * sampleRatio + 0.5)` here?  I know there are some corner cases where this isn't precise, but I think it'd be fine for this.

**Comment by killkrt** [comment]
Yes, I agree with you @radarsat1, anyway I am not 100% sure that in case of values like `x.5` the classic C casting would be round to `x + 1` or `x` (same story for `static_cast`).

**Comment by soundbysean** [comment]
Just curious where this landed.  Am I to understand that replacing line 3878 with:

outSampleCount = ( unsigned int )( inSampleCount * sampleRatio + 0.5);

Is an acceptable workaround for now?

**Comment by radarsat1** [comment]
Does it work?  You are in the best position to test it ;)

**Comment by soundbysean** [comment]
Ha, well put.  :)

I should have been more detailed.  It does build, I was following up on this: _"I know there are some corner cases where this isn't precise, but I think it'd be fine for this."_  As a non-expert I am unsure what the implications of this change are.  I was seeking any information that might have been gleaned since this solution was offered, about whether it was indeed fine.

**Comment by soundbysean** [comment]
Or, I suppose this must be the roundf function from math.h, so I'll just include that.  It builds that way as well (using MinGW 32 and 64 on Windows).

**Comment by radarsat1** [comment]
Oh well if you just need to add `#include <math.h>` then that's clearly the right approach.

**Comment by garyscavone** [comment]
Was this ever resolved?
