### ISSUE TITLE
Understanding duplex mode with different sample rates (if possible)

### ISSUE THREAD

**Issue by gvnnz** [thestk/rtaudio#391]
Say I want to both play and record audio at the same time with two different devices, which support different sample rates. For example:

* record with device A at 44.1k
* playback with device B at 96k

Is this technically possible? If so, what value should I pass as `sampleRate` to the [RtAudio::openStream](https://www.music.mcgill.ca/~gary/rtaudio/classRtAudio.html#a6907539d2527775df778ebce32ef1e3b) method, since it takes only one parameter relative to the sample rate to use?

**Comment by garyscavone** [comment]
It is _not_ possible to open a duplex stream with input and output devices running at different rates. If both devices have a rate in common, you can obviously use that. The only other option is to try to open two separate input and output streams, running at different rates and perform your own sample rate conversion if you want to share the data between streams. However, you may run into synchronization or overrun/underrun issues. If you have output data that needs to be played at 96K and you want to record resulting audio at 44.1K, then two separate input and output streams at the two different rates should work fine.

**Comment by gvnnz** [comment]
Hi @garyscavone , thanks a lot for your explanation. That was helpful. I guess I can close this.
