### ISSUE TITLE
clarification on behavior of functions

### ISSUE THREAD

**Issue by BillyDM** [thestk/rtaudio#395]
I'm creating Rust bindings for RtAudio using the C header in https://github.com/thestk/rtaudio/blob/master/rtaudio_c.h.

I have a few questions about the behavior of certain functions. The docs don't make it very clear.

1. When calling the function `rtaudio_open_stream()`, is it guaranteed that the `rtaudio_cb_t` callback will not be called until after the `rtaudio_start_stream()` method is called?

2. When calling the function `rtaudio_stop_stream()`, does it block the calling thread until the stream is successfully stopped?

3. Likewise, does `rtaudio_close_stream()` and `rtaudio_abort_stream()` block the calling thread until the stream is successfully dropped?

4. When the `rtaudio_error_cb_t` callback passed to the `rtaudio_open_stream()` function is called, does it mean that the stream was stopped and/or closed because of an error? If so, do all the error types mean that the stream was closed, or do only certain error types mean that the stream was closed?

**Comment by BillyDM** [comment]
5. Also, is `rtaudio_stop_stream()` guaranteed to stop the stream and  `rtaudio_close_stream()` guaranteed to close the stream? Or is it when those functions return an error, it means that they failed to do that operation?

**Comment by BillyDM** [comment]
I found the answer to question 1 in the docs. https://www.music.mcgill.ca/~gary/rtaudio/playback.html

**Comment by BillyDM** [comment]
Ok, thanks for the clarification!

A follow-up question about error handling: Does the error callback get used at all while the stream is running? Like if the user unplugs a device while the stream is running, does the error callback get called? And if it does, does it mean that the stream is in an invalid state and should be closed, or will the stream keep running regardless?

**Comment by garyscavone** [comment]
The desired behaviour if a device in use is unplugged is to close the stream and report the problem via the error callback with the RTAUDIO_DEVICE_DISCONNECT type. However, not all APIs have listeners to detect and deal with such disconnections.

**Comment by BillyDM** [comment]
Ok cool. I figured that's how it works but I wanted to make sure. Thanks again!
