### ISSUE TITLE
include_directories needed

### ISSUE THREAD

**Issue by marcelinorc** [thestk/rtaudio#40]
I was trying to compile RtAudio for the Raspberry PI. The compiler complained about not finding the alsa/asound.h include file.

I'm not sure if this is needed for another Linux distributions, but I had to include the ALSA_INCLUDE_DIRs at the end of the main CMakeList.txt file like this:

include_directories(rtaudio ${ALSA_INCLUDE_DIR})

**Comment by garyscavone** [comment]
I don't use CMake, so it would be best if you submitted this as a PR.

**Comment by garyscavone** [comment]
This is very old and I cannot test it, as I don't use CMake. I'm closing it.

**Comment by radarsat1** [comment]
In any case the line "include_directories(${ALSA_INCLUDE_DIR})" is present in CMakeLists.txt after "if (AUDIO_LINUX_ALSA)"
