### ISSUE TITLE
soname version bump for RtAudio-6.0.0

### ISSUE THREAD

**Issue by umlaeute** [thestk/rtaudio#405]
RtAudio-5.2.0 built a dynamic library `librtaudio.so.6.0.2`
RtAudio-6.0.0 builds a dynamic library `librtaudio.so.6.0.0` (regardless of buildsystem; I tried with autotools, Cmake and meson)

so obviously the (full) soname version **decreased* from `6.0.2` to `6.0.0` :thinking: 

what makes matters (much) worse however, is that RtAudio-6.0.0 not only breaks API (as mentioned in the release notes), but also the library's ABI:  an application that links against `librtaudio.so.6` from RtAudio-5.2.0 (e.g. `jacktrip`) no longer loads with the `librtaudio.so.6` provided by RtAudio-6.0.0

```bash
$ jacktrip
jacktrip: symbol lookup error: jacktrip: undefined symbol: _ZN7RtAudioC1ENS_3ApiE
$ echo _ZN7RtAudioC1ENS_3ApiE | c++filt 
RtAudio::RtAudio(RtAudio::Api)
```

Therefore, I would like to ask^Wurge you to **bump the soversion** of librtaudio to **7**.
see
- https://en.wikipedia.org/wiki/Soname#Name
- https://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html
- https://semver.org/

note that release version and soversion need not be the same.

**Comment by dvzrv** [comment]
I came here to ask for the same @garyscavone, packaging this project for Arch Linux.
Others may accidentally upgrade this for their downstream distribution, which would break consumers.

Please release a 6.0.1 with a soname bump so that it becomes clear what is going on.
