### ISSUE TITLE
Was 6.0.1 retagged?

### ISSUE THREAD

**Issue by SMillerDev** [thestk/rtaudio#416]
Homebrew updated the release in https://github.com/Homebrew/homebrew-core/pull/138221/files, but when I download the same file now, the checksum is different.

Was the file reuploaded? Or is something malicious going on?

**Comment by garyscavone** [comment]
I had to recreate the distribution provided at http://www.music.mcgill.ca/~gary/rtaudio/ shortly after the release because there was a problem with the xattributes. But nothing changed in terms of the code.

—gary

**Comment by SMillerDev** [comment]
Thanks for confirming that.
