### ISSUE TITLE
WASAPI broken on master, callback called with 20k Hz rate

### ISSUE THREAD

**Issue by Daninet** [thestk/rtaudio#433]
I'm getting no sound through WASAPI. The callback function is called too fast (20k times / sec), without waiting for the buffer to be played. There is no sound output, but it might be caused by my implementation not being able to deliver 20k buffers / sec.

I tried to bisect it, and I think it's caused by this PR (last commit on master): https://github.com/thestk/rtaudio/pull/431

The commit before works without any issues: https://github.com/thestk/rtaudio/commit/c5993f01df32421d9fd6bdf693cf0fa110613f89

**Comment by Xenakios** [comment]
Also having the same issue, no sound from WASAPI. Going back to commit c5993f0 works.

**Comment by lalitshankarchowdhury** [comment]
Please check if #435 fixes this.

**Comment by Xenakios** [comment]
> Please check if #435 fixes this.

Thanks, I'll take a look in the coming days
