### ISSUE TITLE
duplex vs two threads - and what does RTAUDIO_HOG_DEVICE mean?

### ISSUE THREAD

**Issue by jmansion** [thestk/rtaudio#44]
Hi

I'm interested in writing a digital crossover.  I'm typing while I play with a duplex open on my soundcard that delegates buffers to a background thread.  There are some 'zero' buffers in the system to start with, so processing those is supposed to hide scheduling latencies for the worker thread (and compute, I'm interested in FIR as well as IIR).  It seems to be working, albeit on passthrough currently.  (And I'm rather enjoying Enya's new album, actually)

Anyway - while I ponder using lockfree queues instead of the std::mutex/std::condition stuff I have now, I wonder if there is any practical improvement to be had with dedicated threads running the input and output, vs a duplex open.  I'm using a single soundcard, so I have a coherent sample clock either way.  The CPU has multiple cores.  I'm aware (well, guessing) that the rtaudio upcall is in some sense driven from the card clock, while other threads are running from the OS scheduler.

I (very occasionally) get a click - I'm assuming that this is from the duplex thread getting thrown off the CPU when trying to pull a chunk for output - its just acquiring a std::mutex while it does so, and potentially broadcasting on a condition.

I'm inclined to use RTAUDIO_HOG_DEVICE - the comment says 'Attempt grab device and prevent use by others.' but does it defend against other applications, or would an input-only stream with HOG prevent the same process opening output?

(Currently running on Win10 with ASIO, but I'd like to be able to work against native audio, and later compile to run on raspberry pi, albeit output only - which suggests to me that a twin thread system would work better - so there is some benefit from leaving the duplex arrangement I'm listening to).

Nice library, anyway.

**Comment by garyscavone** [comment]
If performing duplex operations, especially on the same soundcard, it is necessary to use a duplex stream.  That is the only way to guarantee your input and output streams do not get out of sync.

The HOG_DEVICE flag is not universally implemented on all APIs and I’m not even sure it is working correctly on those where it is implemented.

Regards,

—gary

**Comment by jmansion** [comment]
On 20/01/2016 02:27, garyscavone wrote:
> If performing duplex operations, especially on the same soundcard, it 
> is necessary to use a duplex stream. That is the only way to guarantee 
> your input and output streams do not get out of sync.
Thanks - but I don't understand.  Is there some problem with two open 
operations?

I'm pretty sure that the card has one master clock, and I'm assuming 
that an attempt to open input and output at different rates would be 
rejected.

I add zero samples before start to allow for some jitter in the 
processing rae at the back end - but every sample received on input will 
generate a sample for output (ie no loss, and no injection) - so how can 
I get out of sync if I never find that there is no buffer ready when the 
output side callback runs?  If there is no under- or over-run then the 
data stream is merely delayed, surely?

James

**Comment by garyscavone** [comment]
Hi James,

If you have two separate RtAudio instances, one for input and the other for output, they will each run their own thread to read and write data to/from the soundcard. These two threads may not always execute in synchrony.  With a duplex stream, there is only one thread, so you are guaranteed to have synchrony between the input and output streams.

—gary

**Comment by jmansion** [comment]
Well, I understand that - but I don't see why it matters?

I have an input thread, which is generally blocked waiting for data from 
the card - it puts that data into an internal queue as soon as the data 
is available and blocks waiting again.

And I have an output thread, which is generally blocked trying to write 
to the card - as soon as it manages it, then it picks a waiting buffer 
from an internal queue and tries again.

So both of these run at different times - but so long as they both move 
data to or from the internal queue before the card enables the call 
again, then the card is none the wiser, surely? Everything hinges on 
there always being an output buffer waiting, and there always being a 
slot to write the input buffer to.

Why do they need to run in synchrony - the overall data rate will be the 
same for each, and driven by the master clock on the card, surely, 
rather than any thread timer?

**Comment by garyscavone** [comment]
It might work as you say … but I wouldn’t do it. Duplex mode is intended for simultaneous input and output operations and was designed for such. Separate input and output streams won’t necessarily start at the same time and they may involve an added burden on the soundcard (again, I don’t know that for sure, but different APIs and drivers may behave in different ways).

—gary
