### ISSUE TITLE
RtAudio::openStream Crash on Linux with PulseAudio

### ISSUE THREAD

**Issue by jcelerier** [thestk/rtaudio#46]
I do the following : 
		
```
RtAudio audio(RtAudio::LINUX_PULSE);
StreamParameters parameters;

parameters.deviceId = audio.getDefaultOutputDevice();
parameters.nChannels = 2; // Checked that this was correct by printing the info
parameters.firstChannel = 0;
unsigned int frames = 1024;
audio.openStream( &parameters,
                                  nullptr,
                                  RTAUDIO_FLOAT32,
                                  44100,
                                  &frames,
                                  &generate_sound);
```

But I get a segfault in :

`RtApiPulse::probeDeviceOpen(unsigned int, RtApi::StreamMode, unsigned int, unsigned int, unsigned int, unsigned long, unsigned int *, RtAudio::StreamOptions *)`

Here is the memory content of `audio.getDeviceInfo(audio.getDefaultOutputDevice()); ` :

```
info	@0x7fffffffe060	RtAudio::DeviceInfo
    duplexChannels	2	unsigned int
    inputChannels	2	unsigned int
    isDefaultInput	true	bool
    isDefaultOutput	true	bool
    name	"PulseAudio"	std::string
    nativeFormats	26	RtAudioFormat
    outputChannels	2	unsigned int
    probed	true	bool
    sampleRates	<7 éléments>	std::vector<unsigned int>
```

What might I be doing wrong ?

**Comment by jcelerier** [comment]
The same code with LINUX_ALSA works but I have to quit pulseaudio in this case.

**Comment by radarsat1** [comment]
I just tested your example code and didn't get a segfault.  (Ubuntu 15.10, x86-64)

Can you investigate more, with gdb perhaps?  Give a backtrace?  Where is it crashing exactly?

**Comment by jcelerier** [comment]
I'll rebuild it in debug. I'm getting it from arch linux, from this package : https://aur.archlinux.org/packages/rtaudio/ (which basically just fetches the release and builds it from source)

**Comment by radarsat1** [comment]
Ah, but that seems to build the 4.1.1 release.  Important detail ;)  I'll try again with that version.

**Comment by radarsat1** [comment]
Yup, now I get a segfault!  I suppose that means it's fixed in master.  I'll see if I can identify the commit.

**Comment by radarsat1** [comment]
Seems like 8408e11e is responsible for the fix.  Arch should wait for the next release.  In the meantime I suggest you locally use the master branch for now if you want.

**Comment by jcelerier** [comment]
thank you very much!
