### ISSUE TITLE
WASAPI and MINGW32 4.9.2

### ISSUE THREAD

**Issue by ptstream** [thestk/rtaudio#53]
Hi,
I cannot build RtAudio with the Mingw compiler version 4.9.2 32 bits under Windows 10.
The same problem exists with the version 4.11 of RtAudio.
At the link phase, 2 errors are generated:
1) `...\audiotools\RtAudio.cpp:4193: erreur : undefined reference to KSDATAFORMAT_SUBTYPE_IEEE_FLOAT`
2) `..\audiotools\RtAudio.cpp:4204: erreur : undefined reference to KSDATAFORMAT_SUBTYPE_PCM`

Probably it is a Mingw problem.
To fix temporarly the problem I add at the function `RtAudio::DeviceInfo RtApiWasapi::getDeviceInfo( unsigned int device)`

`// Define uuid structure due to a problem with Mingw compiler.`
`// Mingw generates an undefined symbol KSDATAFORMAT_SUBTYPE_FLOAT and KSDATAFORMAT_SUBTYPE_PCM`

`static IID KSDATAFORMAT_SUBTYPE_IEEE_FLOAT_GCC; // static variable for KSDATAFORMAT_SUBTYPE_IEEE_FLOAT symbol`
`static IID KSDATAFORMAT_SUBTYPE_PCM_GCC; // static variable for KSDATAFORMAT_SUBTYPE_PCM symbol`
`static bool KSDATAFORMAT_SUBTYP_INIT = false; // Static variable to initialize once`

`// Initialize KSDATAFORMAT_SUBTYPE_IEEE_FLOAT_GCC struct`
`auto KSDATAFORMAT_SUBTYPE_FLOAT_IEEE_INIT = [] ()`
`{`
`unsigned char * uuid = (unsigned char * )"00000003-0000-0010-8000-00aa00389b71";`
`::UuidFromStringA (uuid, &KSDATAFORMAT_SUBTYPE_IEEE_FLOAT_GCC);`
`};`

`// Initialize KSDATAFORMAT_SUBTYPE_PCM_GCC struct`
`auto KSDATAFORMAT_SUBTYPE_PCM_INIT = [] ()`
`{`
    `unsigned char * uuid = (unsigned char * )"00000001-0000-0010-8000-00aa00389b71";`
   `::UuidFromStringA (uuid, &KSDATAFORMAT_SUBTYPE_PCM_GCC);`
};`

`// Initialize once`
`if (!KSDATAFORMAT_SUBTYP_INIT)`
`{`
`KSDATAFORMAT_SUBTYPE_PCM_INIT ();`
`KSDATAFORMAT_SUBTYPE_FLOAT_IEEE_INIT ();`
`KSDATAFORMAT_SUBTYP_INIT = true;`
`}`

and replace all references at `KSDATAFORMAT_SUBTYPE_IEEE_FLOAT` by `KSDATAFORMAT_SUBTYPE_IEEE_FLOAT_GCC` and `KSDATAFORMAT_SUBTYPE_PCM` by `KSDATAFORMAT_SUBTYPE_PCM_GCC`

I validated it on 4.11 version of RtAudio.

Many thanks for this job.
Patrice

**Comment by paulmasri** [comment]
I had this same problem a few months back. Take a look at my StackOverflow question... and the solution http://stackoverflow.com/questions/35130096/c-undefined-reference-to-defined-constant

**Comment by garyscavone** [comment]
Should be fixed in recent WASAPI updates.
