### ISSUE TITLE
Supported deviceInfo.sampleRates seems not correct using WINDOWS_DS.

### ISSUE THREAD

**Issue by ptstream** [thestk/rtaudio#54]
Hi,
It seems that deviceInfo.sampleRates is not correct using WINDOWS_DS.
On my laptop, for WINDOWS_DS api, the function getDeviceInfo returns samples rates from 4000 to 192000.
If I used a sample rate greater than 48000, the sound is distorded.
RtAudio version tested:4.1.2
Patrice

**Comment by radarsat1** [comment]
It's just relaying information from directsound's GetCaps(), which gives [this struct](https://msdn.microsoft.com/en-us/library/windows/desktop/microsoft.directx_sdk.reference.dscaps%28v=vs.85%29.aspx).  A remark on that pages says that higher sample rates may require more buffers.  Have you tried increasing the number of buffers (StreamOptions::numberOfBuffers) or increasing the buffer size (openStream() bufferFrames argument)?

"distorted" doesn't tell us much, does it sound like frames are being dropped, or is it noise, or is it clipping?

**Comment by ptstream** [comment]
Many thanks for your reply.

My test is:
 -Format= RTAUDIO_SINT16.
-Sample rate=96000Hz.
-Buffer size=512.
-Number of buffers=1.

In this case the symptoms are a short 'tac' supperposed at the music.

Buffer size=1024 or more. Effectivelly if I increase the size of the buffer everything works perfectly.
For buffer size:512 it's correct if the number of buffers is greater or equal 4.
Just for information, if I use WASAPI, my configuration with a buffer size equal at 512 run perfectly.
The latency is not a problem for me, I will used a buffer size of 2048.
Thanks again.
Patrice

**Comment by radarsat1** [comment]
Yep, I think that's your answer... higher sample rates necessarily require more data, faster, and perhaps your setup just can't provide 5 ms latency.  If there's a difference between DS and WASAPI, well, I can't explain that, but it might be a Windows thing.  If there's an inefficiency in RtAudio (always possible), more work would be needed to narrow it down.
