### ISSUE TITLE
Supported deviceInfo.nativeFormats seems not correct using WINDOWS_WASAPI.

### ISSUE THREAD

**Issue by ptstream** [thestk/rtaudio#55]
Hi,
When using WINDOWS_WASAPI api, getDeviceInfo function returns the value 16 for nativeFormats. This means that only RTAUDIO_FLOAT32 is supported. I try also RTAUDIO_SINT8, RTAUDIO_SINT16, RTAUDIO_SINT24, RTAUDIO_SINT32. Its run perfectly on my laptop.

In the same way, using WINDOWS_DS, getDeviceInfo function returns the value 3 for nativeFormats. This means that only RTAUDIO_SINT8 and RTAUDIO are supported. I check RTAUDIO_FLOAT32 on my laptop, it runs well.
RtAudio version tested:4.1.2.

**Comment by marcoose777** [comment]
Similar, on linux build querying native format produces differing result every time not FLOAT32 as expected? 
@ptstream I think you'll find RTAUDIO_FLOAT_32 is correct behaviour from the source code:
see line 820 from RTAudio.cpp
// CoreAudio always uses 32-bit floating point data for PCM streams.
  // Thus, any other "physical" formats supported by the device are of
  // no interest to the client.
info.nativeFormats = RTAUDIO_FLOAT32;

**Comment by garyscavone** [comment]
Should be resolved in more recent WASAPI updates.
