### ISSUE TITLE
Stereo does not work even if it's specified to play in stereo

### ISSUE THREAD

**Issue by xXSeraphimXx** [thestk/rtaudio#57]
Hello,
I'm trying to play in stereo (set the value of nChannels=2) but it doesn't plays in stereo.
Has the data to be in a special format? 

I'm using WASAPI with NON_INTERLEAVED Buffers. If I'm using Interleaved Buffers I have stereo output.

**Comment by xXSeraphimXx** [comment]
Okay I fixed it, but I have to critizise, that it's not registered in the documentation how it's done.

**Comment by radarsat1** [comment]
Docs are in github!  Feel free to PR!  Or share here how you fixed it, for future people.
