### ISSUE TITLE
Access to stream with realtime flag is heavily restricted

### ISSUE THREAD

**Issue by xXSeraphimXx** [thestk/rtaudio#58]
Hello,
If I open a stream with RTAUDIO_SCHEDULE_REALTIME on Windows with WASAPI,
no external acess is possible. 
**Word example:**

Audio reference for all threads available;
Thread one{

Opens stream with all needed params
}

Thread two{
//If stream is stopped
  pushes new data to buffer.
 starts the stream again.
}

--> Result is, that the callback function will only work for maximal 2 times!!! So at all, the program is not working right...

**Solution:**
_Deselect realtime flag and access to stream is not restricted any more._

**Question:**
Is that intended to do so or is that a bug?

**PS:
Thanks a lot for this great API :smiley:  !**

**Comment by xXSeraphimXx** [comment]
Okay no, solution does not work...
That's really strange, the stream stops immediately after starting without any exception.
I'm still trying to find out, why this is not working.

**Comment by xXSeraphimXx** [comment]
Okay, fixed the problem.
I'll give a commit.
The solution is quite simple. If a stream is stopped and the method which opened the stream has already returned to go on with other things, the stream will be deleted immideately after stopping(Rather the instance of RtApi). But that's not in the sense of this method I thought. Solution is, to give RtAudio a own thread, because as said in the documentation of RtAudio.h, RtAudio is only a controller and a controllor shouldn't go away only because the method to start a stream is done. It should be deleted if the programmer specified to close the stream.

**Comment by radarsat1** [comment]
I'm not sure from your comment, but are you starting and stopping the same RtAudio instance from different threads? This is not recommended.

**Comment by xXSeraphimXx** [comment]
I habe to admit, that I'm using RtAudio to build a Java Sound Api. So  Im accessing RtAudio over the Java Native Interface (JNI). Of course I'm accessing tHan the instance of RtAudio over different threads because the stream should be opened with one call. Other asynchron calls are send from different threads eigthe to put new data into the stream or to stop the stream

**Comment by xXSeraphimXx** [comment]
As I see the problem I had is caused from the JNI. The instance gets deleted after the stream is empty and or a new call to the JNI is been made (Please excuse the writing. On my smartphone it is difficult to write because I'm using a bilingual keyboard so some words are like a German woRd :'D ).

At all the soLuton for JNI calls is to use a own thread for the openStream call which keeps alive during the stream HAS NOT been closed.

**Comment by radarsat1** [comment]
I see. I don't think RtAudio includes any thread safety measures, so you should either

1) Put RtAudio on its own thread and communicate with it as you see fit, in a thread-safe manner
2) Wrap calls to RtAudio in a mutex

I think either of these approaches should be possible from Java though, perhaps you can use Java's threading support to take care of the details instead of doing it in C++.  Alternatively it could be a good chance to explore C++11 threading and mutex support.  http://en.cppreference.com/w/cpp/thread/mutex
