### ISSUE TITLE
stopStream() should only stop the stream and not allow  to delete the instance

### ISSUE THREAD

**Issue by xXSeraphimXx** [thestk/rtaudio#59]
stopStream() allows C++ to delete the instance, if the method where the stream has been started has allready ended. This is wrong, stream stop should keep the instance alive. closeStream() only should allow the deletion!

**Comment by garyscavone** [comment]
I assume all your comments concern the WASAPI implementation? I have the feeling that code should go in a separate branch, as it was never adequately tested. It also needs some interpolation in the way it supports multiple sample rates � currently, it simple rounds or truncates to the nearest sample. I try my best to stay away from Windows, so if you have some specific improvements for the code, please submit them as pull requests.
