### ISSUE TITLE
Starting a RtAudio app at Linux startup

### ISSUE THREAD

**Issue by sinosoidal** [thestk/rtaudio#61]
Hi,

This is not a RtAudio issue but I'm wondering if anyone has already dealt with this problem and what it is the solution. 

I have created a init.d script to startup a RtAudio app at startup. I'm having a problem though. Sometimes it is not able to detect the audio device. In this case the audio device is a simple usb audio sound card. It seems that sometimes the device is already present and sometimes it is not.

Thanks in advance. Best regards

**Comment by radarsat1** [comment]
Indeed, it's probably a better question for the linux audio users mailing list. However, in init.d you can play with service priorities to get the order right. Alternatively you could set it up to launch by modprobe after the audio driver loads, or you could have your program or a launch script loop until the audio device becomes available.
