### ISSUE TITLE
No C API like RtMidi has?

### ISSUE THREAD

**Issue by 0joshuaolson1** [thestk/rtaudio#64]
RtMidi [mentions](https://github.com/thestk/rtmidi/blob/master/doc/release.txt) one, but RtAudio's [release.txt](https://github.com/thestk/rtaudio/blob/master/doc/release.txt) doesn't.

**Comment by radarsat1** [comment]
It's something someone contributed, there has been no similar contribution for RtMidi. Feel free to propose ;)

**Comment by 0joshuaolson1** [comment]
It's RtMidi that apparently has one, but I'll keep that in mind if libsoundio doesn't work out for me!

**Comment by radarsat1** [comment]
Sorry, yeah meant to say RtAudio there !

**Comment by zserge** [comment]
I've started making a C wrapper as a part of my sweet dream to make C+Golang bindings for all three libraries (RtAudio, PortAudio, libsoundio) that would be easy to use. So I've made a C wrapper for RtAudio and amalgamated PortAudio and libsoundio.

Here are the RtAudio wrappers:

* https://github.com/naivesound/audio/blob/master/rtaudio/rtaudio_c.cpp
* https://github.com/naivesound/audio/blob/master/rtaudio/rtaudio_c.h

I would be thankful is someone could review it and give some feedback.

**Comment by tay10r** [comment]
@zserge Looks great! Personally, I don't like typedef'ing the pointer and the usage of POSIX suffix `_t` in the type names. But that's just me. You should definitely submit a PR.

**Comment by zserge** [comment]
@tay10r I hear you, and I normally don't prefer it either, but this was primarily done for Go bindings, and it looks a bit cleaner for me to write `C.rtaudio_device_info_t` than `C.struct_rtaudio_device_info`, especially in a language where long line wrapping is not a norm.

**Comment by tay10r** [comment]
@zserge Gotcha, that makes sense. Are you going to submit a PR for this?

**Comment by zserge** [comment]
@tay10r Yes, I'm right now working on naivesound/audio library and once I'm confident with my rtaudio/rtmidi bindings (there are a few mislooked points in that, too) - I will make PRs to both.

In fact, on a broader topic - is anyone interested in Go bindings for this? Technically, as the library is only 2 files + 2 C wrapper, Go bindings would add one more `.go` file to this and people would be able to use it in Go by adding just one import line. It's mostly straightforward and probably I would be happier to put my Go bindings into this official repo rather than keep a separate repo and copy RtAudio sources regularly into it.

**Comment by zserge** [comment]
@tay10r I've made a pull request #98 for C API wrappers. If you give me a green light - I can also make a pull request for Go API wrapper. That hopefully could make this nice little library a bit more popular among modern developers, comparing to the bloated portaudio. I see there are some Python bindings in the repo, so I hope adding Go wrapper should not be a problem for the maintainers.

**Comment by tay10r** [comment]
@zserge I'm not one of the maintainers, but hopefully they'll get around to viewing the PR.

**Comment by radarsat1** [comment]
Hi guys, don't have time atm but keep working, I'll take a look at the PR as soon as I get a chance.  Mostly leaving the C API up to people who are motivated, so go for it, I'll merge without too much argument ;)

**Comment by radarsat1** [comment]
Closed in #98
