### ISSUE TITLE
Add payload (userData) in error callback

### ISSUE THREAD

**Issue by antis81** [thestk/rtaudio#66]
Hey,

I'm implementing a Qt-wrapper and Qt consequently disables exception handling. Thus, most RtAudio examples won't even compile with that - like in the [device settings example](https://www.music.mcgill.ca/~gary/rtaudio/settings.html):

``` c++
#include "RtAudio.h"
int main()
{
  RtAudio dac;
  if ( dac.getDeviceCount() == 0 ) exit( 0 );
  RtAudio::StreamParameters parameters;
  parameters.deviceId = dac.getDefaultOutputDevice();
  parameters.nChannels = 2;
  unsigned int sampleRate = 44100;
  unsigned int bufferFrames = 256; // 256 sample frames
  RtAudio::StreamOptions options;
  options.flags = RTAUDIO_NONINTERLEAVED;
  try {
    dac.openStream( &parameters, NULL, RTAUDIO_FLOAT32,
                    sampleRate, &bufferFrames, &myCallback, NULL, &options );
  }
  catch ( RtAudioError& e ) {
    std::cout << '\n' << e.getMessage() << '\n' << std::endl;
    exit( 0 );
  }

  return 0;
}
```

I assume to set a `bool isOpen` member variable depending on the success of the `dac.openStream` function call. As there is no error return value, I don't see a chance other than to pass `this` as `userData` to the `RtAudioErrorCallback` - which is not possible. Thus, I'm somewhat stuck.

Questions:
1. If exceptions have to be enabled, can I achieve that only for RtAudio?
2. Is there a way to use RtAudio without exceptions?

Btw. passing a C++11/14 lambda would also work fine, if the context could be passed along with it. I.e. something like this:

``` c++
a.openStream(…, [&](RtAudioError::Type t, const std::string& msg) { 
    this->mIsOpen = false; 
    std::cerr << msg;
});
```

**Comment by radarsat1** [comment]
Why are you disabling exception handling in the first place? I don't think Qt requires this.  I just tried compiling a Qt4 program with a function that throws an exception and it works fine.  You're saying that you cannot put the following in a button handler?

~~~
try {
    dac.openStream( &parameters, NULL, RTAUDIO_FLOAT32,
                    sampleRate, &bufferFrames, &myCallback, NULL, &options );
  }
  catch ( RtAudioError& e ) {
    std::cout << '\n' << e.getMessage() << '\n' << std::endl;
    exit( 0 );
  }
~~~

In any case, have you tried splitting off your GUI code into a separate part of the program?

This issue with exceptions seems quite different from the userData suggestion, I don't know why you are conflating the two things.  I *do* think it's a good idea to pass userData to the error callback.

I don't think there's any intention to explicitly support C++11/14 lambdas for now.

**Comment by antis81** [comment]
Thanks for the quick reply!

>Why are you disabling exception handling in the first place?

Well, it's true we set `QMAKE_CXXFLAGS += -fno-exceptions` in our project (Qt5 based). This works fine in general with most API's out there (e.g. ffmpeg, opus, …). As this is a compiler flag, I don't think it's possible to disable it just for a specific code block unless it is compiled as a library by itself and I avoid that completely.

>In any case, have you tried splitting off your GUI code into a separate part of the program?

Yes. What I'm coding doesn't contain any GUI code, yet it is planned to be used from within a GUI later. Basically the code encapsulates RtAudio and the GUI code doesn't know anything about RtAudio.

>… I *do* think it's a good idea to pass userData to the error callback.

That's fine! It will solve my problem. If I understand this correctly, the callback is used in addition to the exception, right?

>I don't think there's any intention to explicitly support C++11/14 lambdas for now.

No problem. As long as one doesn't pass a context (reference `&` or copy `=`), it works out of box! This makes the callback itself live within the same scope as the caller function and is destroyed, when this scope is left.

**Comment by antis81** [comment]
Btw. clang's static code analysis states: `dynamic exception allocation is deprecated. Please use 'noexcept' instead`. Don't know if that helps with the topic though.

**Comment by radarsat1** [comment]
I believe the callback is used throughout the life of the open stream, whereas the exception is only for things that happen during the `openStream()` call.

**Comment by radarsat1** [comment]
For better or worse, RtAudio uses exceptions to deal with initialization issues.  However, `throw` only appears a handful of times in RtAudio.cpp.  If you need a version of RtAudio that doesn't use exceptions, I encourage you to just make the necessary modifications in your own project.  You can submit a PR if you have a good idea of how you could integrate some exception-free version gracefully, but currently it's expected that the error callback throw exceptions for anything but warnings.  Changing this is rather backwards incompatible I'm afraid.  But making the necessary changes for your own purposes should be fairly straight-forward.

**Comment by antis81** [comment]
>I believe the callback is used throughout the life of the open stream…

For the record: The lambda is exactly valid within its surrounding context. In my code this has a simliar effect as with the exception:

```c++
class StreamContext {
public:
void open() {
    a.openStream(…, [](RtAudioError::Type t, const std::string& msg) { std::cerr << msg; });
    // lambda lives to the end of the "open" method 
}

private:
    RtAudio a;
};
```

>If you need a version of RtAudio that doesn't use exceptions, I encourage you to just make the necessary modifications in your own project.

Actually I odn't need to modify the library anymore and found another solution… :)

>You can submit a PR if you have a good idea of how you could integrate some exception-free version gracefully…

Maybe I'll do that. However, concerning this topic I see no other option, than to enable/disable exceptions at compile time of the library itself. Btw. the `noexcept` keyword is a c++11 feature - nevermind that.

**Comment by radarsat1** [comment]
Sure, just be aware that it keeps a pointer to the error callback, so if it's called later after the lambda is off the stack, it may segfault.  A better approach would be to have it call a function that you provide, and have this function set error information in some global place that it knows about.  That's the best and safest thing you can do unless errorCallback is modifed to take a userData parameter.

Otherwise, it seems the only place that `throw` is called outside the error handler is in the RtAudio constructor.  So if that was removed and you replace the errorCallback with some other mechanism, I think it should be safe to disable exceptions in code calling RtAudio.  Of course it does need to be enabled while compiling RtAudio, unless you modify RtAudio.cpp.

**Comment by radarsat1** [comment]
(I should note that that is of course the same thing as passing in a lambda that makes no reference to local data...)

**Comment by zserge** [comment]
This might be also a problem for #64 because there seems to be no way to make an intermediate callback proxy function that would delegate execution to the C function.

**Comment by garyscavone** [comment]
A reconsideration and perhaps redesign of error handling is in order but the title of this issue doesn't necessarily convey that meaning. Plus, there has been a lot more discussion of this elsewhere, so I'm going to close this issue.
