### ISSUE TITLE
Mobile support? iOS/Android

### ISSUE THREAD

**Issue by speps** [thestk/rtaudio#71]
I just wanted to know if there's been any plans for supporting mobile platforms like iOS / Android. I don't mind doing the work, it doesn't seem impossible given the simplicity of RtAudio :)

The plan for iOS is to support CoreAudio directly instead of OpenAL (unless OpenAL could be useful on other platforms). For Android, there is apparently OpenSL. All of those APIs seem to be the low latency options but any other suggestions are welcome.

**Comment by garyscavone** [comment]
It would be great to have iOS / Android support in RtAudio!  Hopefully, it can be integrated into the existing API. There is some iOS support in a related project, STK, which might offer a starting point.

**Comment by speps** [comment]
I started on this, adding iOS first as it will be used right away and Android when it will be needed.

I'll send a pull request when I have the iOS one working. I went with the Audio Queues API as it works on OSX as well (it helps with debugging, and provides an additional OSX backend).

How do you feel about submitting a version that handles only playback at first and then add recording later? I don't know what's recommended here, I'm guessing other backends took some time before being feature-complete :)

**Comment by garyscavone** [comment]
It might be better to start a new branch for that until a particular implementation is complete (and can then be merged into the master branch).

**Comment by garyscavone** [comment]
Would love to see this happen but this issue seems stale.
