### ISSUE TITLE
Location of distributed headers on Linux (Unix?) 

### ISSUE THREAD

**Issue by antis81** [thestk/rtaudio#72]
At least for Debian, header files (there's only one, right?) seem to be packaged falsely and `apt install librtaudio-dev` copies to `/usr/include/RtAudio.h`. On Arch linux OTOH files are installed to `/usr/include/rtaudio/RtAudio.h`. Could you please check and fix that? If you ask me, the "rtaudio" prefix is the right thing to do. Probably headers can be symlink'ed `RtAudio.h -> rtaudio/RtAudio.h` to keep backwards compatibility, though I wouldn't advice that and rather help people to get cross-compatibile code.

**Comment by radarsat1** [comment]
~~~
$ mkdir install
$ ./autogen.sh --prefix=$PWD/install >/dev/null 2>&1 
$ make install >/dev/null 2>&1 
$ find install/ -name RtAudio.h
install/include/rtaudio/RtAudio.h
~~~

Clearly this is a Debian issue, please report it to the package maintainer.
