### ISSUE TITLE
Cannot build on windows 10 (Unknown system type for realtime support!)

### ISSUE THREAD

**Issue by onurhb** [thestk/rtaudio#75]
This is the output when I am running ./configure
I managed to make rtaudio work with visual studio for long time ago, but I can't build it with mingw. 

```
$ ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... no
checking whether make supports nested variables... no
checking that version numbers are coherent... checking for style of include used by make... none
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... none
yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking whether make supports nested variables... (cached) no
checking pkg-config... no
checking whether to compile debug version... checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... none
checking for ar... ar
checking the archiver (ar) interface... ar
checking for ar... /c/MinGW/bin/ar
checking build system type... x86_64-pc-mingw64
checking host system type... x86_64-pc-mingw64
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... c:/mingw/mingw32/bin/ld.exe
checking if the linker (c:/mingw/mingw32/bin/ld.exe) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /c/MinGW/bin/nm -B
checking the name lister (/c/MinGW/bin/nm -B) interface... BSD nm
checking whether ln -s works... no, using cp -pR
checking the maximum length of command line arguments... 8192
checking how to convert x86_64-pc-mingw64 file names to x86_64-pc-mingw64 format... func_convert_file_msys_to_w32
checking how to convert x86_64-pc-mingw64 file names to toolchain format... func_convert_file_msys_to_w32
checking for c:/mingw/mingw32/bin/ld.exe option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... file_magic ^x86 archive import|^x86 DLL
checking for dlltool... dlltool
checking how to associate runtime and link libraries... func_cygming_dll_for_implib
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /c/MinGW/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for as... as
checking for dlltool... (cached) dlltool
checking for objdump... (cached) objdump
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -DDLL_EXPORT -DPIC
checking if gcc PIC flag -DDLL_EXPORT -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (c:/mingw/mingw32/bin/ld.exe) supports shared libraries... yes
checking whether -lc should be explicitly linked in... yes
checking dynamic linker characteristics... Win32 ld.exe
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... c:/mingw/mingw32/bin/ld.exe
checking if the linker (c:/mingw/mingw32/bin/ld.exe) is GNU ld... yes
checking whether the g++ linker (c:/mingw/mingw32/bin/ld.exe) supports shared libraries... yes
checking for g++ option to produce PIC... -DDLL_EXPORT -DPIC
checking if g++ PIC flag -DDLL_EXPORT -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (c:/mingw/mingw32/bin/ld.exe) supports shared libraries... yes
checking dynamic linker characteristics... Win32 ld.exe
checking how to hardcode library paths into programs... immediate
checking for ANSI C header files... (cached) yes
checking sys/ioctl.h usability... no
checking sys/ioctl.h presence... no
checking for sys/ioctl.h... no
checking for unistd.h... (cached) yes
checking for gettimeofday... yes
checking for doxygen... no
checking for audio API... configure: error: Unknown system type for realtime support!

```

**Comment by garyscavone** [comment]
The configure.ac should be looking for *-mingw32*, which used to work.  Not sure what would have changed.

**Comment by onurmhb** [comment]
Found out that I had to uses msys shell. ./configure works now, but when I run make I get follwing error:

```
$ make
Making all in .
make[1]: Entering directory `/c/Users/Onur/Desktop/Development/rtaudio-4.1.2'
  CXX      RtAudio.lo
RtAudio.cpp:3682:25: fatal error: audioclient.h: No such file or directory
compilation terminated.
make[1]: *** [RtAudio.lo] Error 1
make[1]: Leaving directory `/c/Users/Onur/Desktop/Development/rtaudio-4.1.2'
make: *** [all-recursive] Error 1
```

**Comment by garyscavone** [comment]
It appears you are trying to compile WASAPI support.  I’m not sure that has been done in the past using mingw or not.  Perhaps you can search your file system for “audioclient.h” and then try adding a header search path to the g++ compile statement (with "-I/path/to/file”)?

**Comment by MrfksIv** [comment]
I am getting the same error when I run ./configure on Windows10. Has anyone found a workaround on this issue?

**Comment by radarsat1** [comment]
@mrfkslv Which API are you trying to build? Have you tried other APIs? Which headers are not found? Have you tried installing or setting paths for the needed headers?

**Comment by MrfksIv** [comment]
Hi,
I am using MinGW on Windows 10 and running the following commands:

`autoconf`
`./configure --disable-realtime --with-ds  --build LDFLAGS="-LC:/Program Files (x86)/Windows Kits/10/Lib/10.0.15063.0/um/x86"`

**And this is the log I get:**

checking for g++... g++

checking whether the C++ compiler works... yes<br>
checking for C++ compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for ranlib... ranlib
checking for ar... /c/cygnus/cygwin-b20/H-i586-cygwin32/bin/ar
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /c/cygnus/cygwin-b20/H-i586-cygwin32/bin/grep
checking for egrep... /c/cygnus/cygwin-b20/H-i586-cygwin32/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... no
checking for stdint.h... no
checking for unistd.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking termio.h usability... yes
checking termio.h presence... yes
checking for termio.h... yes
checking for unistd.h... (cached) yes
checking for an ANSI C-conforming const... yes
checking for size_t... yes
checking whether time.h and sys/time.h may both be included... yes
checking whether byte ordering is bigendian... no
checking for RAWWAVE_PATH argument...
checking for INCLUDE_PATH argument...
checking whether to compile realtime support... no
checking whether to build the static library... yes
checking whether to build the shared library... no
checking for cos in -lm... yes
checking whether to compile debug version... no
checking build system type... config.sub: too many arguments
Try `config.sub --help' for more information.
configure: error: /bin/sh config/config.sub LDFLAGS=-LC:/Program Files (x86)/Windows Kits/10/Lib/10.0.15063.0/um/x86 failed

**I have also tried the following both with quotes and without, and Windows path format, MinGW path format, all resulting in error: (The path below is where the libraries dsound.lib, WSoc32.Lib  and WinMM.Lib are found)** 

`./configure --disable-realtime --with-ds  --build LDFLAGS="-L/c/Users/mrfksiv/Documents/STK-try2/stk-4.6.0"`

checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for ranlib... ranlib
checking for ar... /c/cygnus/cygwin-b20/H-i586-cygwin32/bin/ar
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /c/cygnus/cygwin-b20/H-i586-cygwin32/bin/grep
checking for egrep... /c/cygnus/cygwin-b20/H-i586-cygwin32/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... no
checking for stdint.h... no
checking for unistd.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking termio.h usability... yes
checking termio.h presence... yes
checking for termio.h... yes
checking for unistd.h... (cached) yes
checking for an ANSI C-conforming const... yes
checking for size_t... yes
checking whether time.h and sys/time.h may both be included... yes
checking whether byte ordering is bigendian... no
checking for RAWWAVE_PATH argument...
checking for INCLUDE_PATH argument...
checking whether to compile realtime support... no
checking whether to build the static library... yes
checking whether to build the shared library... no
checking for cos in -lm... yes
checking whether to compile debug version... no
checking build system type... config.sub: too many arguments
Try `config.sub --help' for more information.
configure: error: /bin/sh config/config.sub LDFLAGS=-L/c/Program Files (x86)/Windows Kits/10/Lib/10.0.15063.0/um/x86 failed
/cygnus/cygwin-b20/H-i586-cygwin32/bin/sed.exe: -e expression #1, char 1: Unknown command: ``C''

I know that according to the docs "the __LITTLE_ENDIAN__ and __WINDOWS_MM__ and  __WINDOWS_DS__  preprocessor definitions are necessary for all Windows systems" however I am not exactly sure how to do this. I tried passing an extra argument to configure:

`./configure --disable-realtime --with-ds  --build LDFLAGS="-L/c/Program Files (x86)/Windows Kits/10/Lib/10.0.15063.0/um/x86" CPP=__WINDOWS_DS__ __LITTLE_ENDIAN__ __WINDOWS_MM__`

but this also resulted in an error. 

I apologise in advance as I understand that it is probably a stupid question/error from my part but I am completely new to the autoconf and configure and I believe the documentation is not straight-forward for someone not familiar with these build tools. 

Thank you for your time.

**Comment by radarsat1** [comment]
Hi, yes you're a little unused to autoconf projects I believe.  Also, I see that when you said "I am getting the same error", you meant, "I am getting a completely different error".  This current issue that you commented in is about the error `audioclient.h: No such file or directory`, which is related to WASAPI, while it seems you are attempting to use DirectSound.

1. it seems you are using cygwin, i'm not sure whether or not that is tested and supported.  (afaik no one has even tested on Windows 10 but I don't think this is specific to 10)  Personally I think I have only tested it with the MSYS environment, and it's been a long time.. in other words, "ymmv".  Any fixes you can contribute are welcome but it may be hard to help you remotely.

 2. the flag `--disable-realtime` disables audio and MIDI, is that intended? It doesn't make sense to combine it with `--with-ds`

3. `--build` is for cross-compiling afaik, i wouldn't use it here

4. `CPP` is for specifying the preprocess, not the flags.  Use `CPPFLAGS`.

Try the following:

~~~
export LDFLAGS='-L/c/Program Files (x86)/Windows Kits/10/Lib/10.0.15063.0/um/x86'
export CPPFLAGS='-I<directory containing dsound.h>'
./configure
make
~~~

Don't specify `__WINDOWS_DS__ __LITTLE_ENDIAN__ __WINDOWS_MM__`, that should be done for you by configure.

**Comment by MrfksIv** [comment]
Success at last! Thank you so much for all your help.
In the end I had to copy the .lib .h files in a different directory because "Program Files (x86)" was causing issues due to the included spaces.

**Comment by radarsat1** [comment]
Ah, very good to know.  Hopefully this thread will be helpful for someone in the future. Cheers.

**Comment by radarsat1** [comment]
Hi, I think you are not building master, can you try it?  That error message doesn't exist any more on the master branch.

**Comment by radarsat1** [comment]
Ah I see, sorry about that. Yes things need to be updated all around.  Work in progress.  For stk you can maybe try just copying RtAudio files overtop of what's included there, but yes, needs to be updated before next release. Cheers.
