### ISSUE TITLE
Wouldn't it be great to add more C++11 utilities, like std::function or std::mutex?

### ISSUE THREAD

**Issue by pocketbroadcast** [thestk/rtaudio#76]
Recently I had to do a workaround to add custom data (from the stack) to my audio callback.
I had to put it in a single structure and add it via the `void *userData` parameter in `openStream`.
I thought of using 

`using RtAudioCallback = std::function<int(void*, void*, unsigned int, double, RtAudioStreamStatus, void*>` instead of the functionptr `RtAudioCallback` which is 

```
typedef int (*RtAudioCallback)( void *outputBuffer, 
                                                  void *inputBuffer,
                                                  unsigned int nFrames,
                                                  double streamTime,
                                                  RtAudioStreamStatus status,
                                                  void *userData );
```

This would enable us to use:

```
RtAudio rtAudio;
Foo foo;
Bar bar;

auto audioCallback = [&](void*, void*, unsigned int, double, RtAudioStreamStatus, void*) 
                                    { return foo.do()+bar.do(); };


rtAudio.openStream(oParam, iParam, format, sampleRate, bufferFrames,
                                  audioCallback, nullptr, options, nullptr);
```

**Comment by radarsat1** [comment]
There are ways to do this, I've done it in the past on other projects, but it's quite hard to make backward compatible.  (It can be done...)  However, apart from making "hello world" type example look a little nicer, in any real application a typical callback will quickly get too long to put comfortably in a local lambda, so for RtAudio I'm not sure the benefits outweigh the challenges.  That said, modern C++ legitimately has some nice alternatives to using a void*.  I think this kind of change might be appropriate for a major version or fork sometime in the future, unless a reliable backwards compatible method can be found.  Remember that RtAudio is still (unfortunately) used by people with old versions of Visual Studio, etc.  Being able to rely on C++11 being available.. we are getting there, but it's still not a given, and not necessarily worth breaking working code for.

**Comment by garyscavone** [comment]
Since C++11 is now 6 years old (??), backward compatibility is probably becoming less of a concern here. That said, it seems like the default behaviour for most c++ compilers is the older standard and you generally have to specify a flag like "-c++11" to use the newer standard.

I'm closing this issue but I'm open to people proposing updates via PRs that make use of C++11.

**Comment by radarsat1** [comment]
The way to do it imho is after the next release, start a longer-term "experimental" branch for taking advantage of newer C++ features and see where it goes..
