### ISSUE TITLE
.lib file not generated with .dll using CMake and Visual Studio 2015

### ISSUE THREAD

**Issue by AndrewBelt** [thestk/rtaudio#77]
I'm building a .dll for RtAudio, so I've generated a VS2015 project with CMake and compiled the project in all build modes. The static builds work fine, but the .dll files are being generated without an accompanying .lib file. The `Release` and `RelWithDebInfo` modes build a 16KB .dll file, so I assume nothing is being included in those files. I'm not well-versed in Windows, but are the symbols/functions not being exported?

**Comment by radarsat1** [comment]
@berkus Please review.

**Comment by Boscop** [comment]
I'm running into the same problem. It generates the 16 KB rtaudio.dll, but when I try to generate a .lib file from it, it's empty (no exports). Dependency Walker also sees no exported functions. Looking through the source code I also see no mention of dllexport..

**Comment by radarsat1** [comment]
No other platform requires dllexport, so I would imagine that it probably needs to be added.  I think maybe this wasn't an issue with mingw but becomes one for Visual Studio, which wasn't previously supported. (As far as I remember.. @garyscavone may correct me..)

**Comment by garyscavone** [comment]
I stopped testing RtAudio with Visual Studio many years ago but if someone wants to submit fixes, please do!

**Comment by garyscavone** [comment]
Closing for lack of further discussion or action.
