### ISSUE TITLE
 Wrong order when calling CoUninitialize () in RtAudio.cpp

### ISSUE THREAD

**Issue by pbludov** [thestk/rtaudio#80]
`RtApiDs :: ~RtApiDs()
{
 if ( coInitialized_ ) CoUninitialize(); // balanced call.
 if ( stream_.state != STREAM_CLOSED ) closeStream();
}

`
According to documentation, CoUninitialize() must be "the last call made to the COM library". After this, the entire COM world may be broken. So, closeStream() may leak or even crash under some circumstances. I believe the correct version is

`RtApiDs :: ~RtApiDs()
{
  if ( stream_.state != STREAM_CLOSED ) closeStream();
  if ( coInitialized_ ) CoUninitialize(); // balanced call.
}

`

**Comment by radarsat1** [comment]
Sounds reasonable to me.
