### ISSUE TITLE
ALSA duplex mode mono output has unintentional passthrough

### ISSUE THREAD

**Issue by dansgithubuser** [thestk/rtaudio#82]
If I use ALSA in duplex mode and request 1 output channel, my device reports 2 as minimum number of channels, rtaudio swallows this, and I'm guessing because of some memory mismanagement, I get a passthrough from mic to speaker even when my callback only returns 0.

What does this comment mean?
https://github.com/thestk/rtaudio/blob/master/RtAudio.cpp#L7418
"Determine the number of channels for this device.  We support a possible minimum device channel number > than the value requested by the user."
The blame for the line points to this commit, which I don't know how to dissect further:
https://github.com/thestk/rtaudio/commit/6faf4336eb5952b141e1c239d194f5cd70f0a885

Anyway, in particular, what does "support" mean? Is there any test? Is what I observed actually expected? I'm happy to tromp through the code for an error -- if you think there is one.

**Comment by garyscavone** [comment]
Some audio devices have to be opened with a fixed minimum number of channels (when using the ALSA API), no matter how many channels the user actually wants to use.  For example, my RME soundcard may require that it be opened with 16 channels, even if I only want to use 2. In your case, it appears the device requires a minimum of 2 channels. But RtAudio is supposed to hide those details from the user. If you, the user, only want one channel, then that is all you should be reading or writing to/from RtAudio functions. I don't think the lines of code around line 7418 are the source of your problem, as that code has worked fine in the past. Have you tried using the test programs in the "tests/" subdirectory to debug this?

**Comment by dansgithubuser** [comment]
There's no test for this, but if I add `memset( outputBuffer, 0, *bytes );` to duplex.cpp so that inout looks like
`int inout( void *outputBuffer, void *inputBuffer, unsigned int /*nBufferFrames*/,
           double /*streamTime*/, RtAudioStreamStatus status, void *data )
{
  // Since the number of input and output channels is equal, we can do
  // a simple buffer copy operation here.
  if ( status ) std::cout << "Stream over/underflow detected." << std::endl;

  unsigned int *bytes = (unsigned int *) data;
  memcpy( outputBuffer, inputBuffer, *bytes );
  memset( outputBuffer, 0, *bytes );
  return 0;
}`
then build and invoke with `./duplex 1 44100` I get exactly what I was talking about -- unintentional passthrough.

I got a further hint, might as well mention it: seems the input goes to the right channel only, and left channel acts correctly. Maybe I should say that I do have a stereo output device, but want to send the same signal to both sides with the least overhead possible. Is it possible unused outputs are being left undefined?

What do you mean by "worked in the past"?

**Comment by dansgithubuser** [comment]
Seems that `RtApi :: convertBuffer( char *outBuffer, char *inBuffer, ConvertInfo &info )` does not fully overwrite `outBuffer` when `info.inJump` is 1 and `info.outJump` is greater than 1. When it is used here:
https://github.com/thestk/rtaudio/blob/master/RtAudio.cpp#L8003
the caller assumes that convertBuffer DOES fully overwrite `outBuffer`.

It'd be convenient for me to maintain this assumption, and have it copy the last in channel to the remaining out channels.

I can imagine that you might want to instead zero the extra out channels.

What kind of behavior do you expect when 1 output channel is requested on a device that has at least 2? Should L and R be equal, or should one be silent?

**Comment by garyscavone** [comment]
I don’t have time to look at this closely for a few days but I believe the assumption is that all buffers are initially set to zero, thus there should be no need to subsequently clear sections of a buffer that are not written to. If the user only wants 1 channel but the device needs 2 or more, then the sections of the larger buffer sent to the device that correspond to the extra channels should not be touched.

That said, since the same deviceBuffer is used for input and output (when in duplex mode), that assumption won’t work if there are are more input channels than output channels. So, in that case, the extra channels of the device buffer do need to be cleared. And that seems to be happening on lines 9714-9716.

**Comment by dansgithubuser** [comment]
I did check that condition -- seems it wasn't true. I'm under the impression `stream_.nDeviceChannels[0]` and `stream_.nDeviceChannels[1]` were both 2 (I know min channels and max channels is 2 for both in and out). Perhaps this is a detail I didn't realize is important: I ask for mono input and output, but seem to have 2 min channels for both. I can't imagine my laptop's mic is actually stereo, I think my OS is playing its own set of tricks.

**Comment by garyscavone** [comment]
No problem with RtAudio was ever verified, so I'm closing this.

**Comment by witaly-iwanow** [comment]
I don't really understand why this was closed, it's a legitimate RtAudio issue imo.
So I run duplex example with 1 48000 and get this weird sidetone even though it's definitely off (I thought it was Win 10 issue at first), same thing on macOS. I also tried doing memset(outputBuffer, 0, *bytes) and got clean mic-speaker passthrough, and at this point it was clear RtAudio was at fault, not to mention the fact PortAudio and libsoundio worked perfectly in the same scenario/hardware.
This is my perspective: I open the stream in mono mode, there's no any error indication, and then I get a callback with nFrames set to 512. How do I figure out that I actually need to output 512*2 samples? Do I get 512 or 512*2 input samples? No idea. How is that not an RtAudio issue? Proper behavior would be openStream throwing an exception or duplex example handling the scenario properly (getting the actual number of channels)

**Comment by garyscavone** [comment]
I’m not sure why this was closed. But more importantly, did you figure out how to fix it? We rely on the user community providing solutions to reported bugs, as none of us is paid to work on this project nor do we have much time to devote to it.

**Comment by witaly-iwanow** [comment]
I see. I don't see an easy and reliable fix for it, the only workaround which comes to mind is to avoid duplex at this point
