### ISSUE TITLE
Can't build pyrtaudio

### ISSUE THREAD

**Issue by luigino** [thestk/rtaudio#91]
On linux, using 4.1.2 version.

[pyrtaudio_log.txt](https://github.com/thestk/rtaudio/files/1058248/pyrtaudio_log.txt)

**Comment by radarsat1** [comment]
Ok I'm starting to understand your #90 ...  trying to build pyrtaudio configures RtAudio with all drivers enabled, including OSS.

**Comment by luigino** [comment]
Is there a switch to disable OSS?

**Comment by radarsat1** [comment]
No but I'm fixing it.  I should note that I have no idea of the status of pyrtaudio, it seems several things are a bit out of date and the code contains some printf debugging statements.
