### ISSUE TITLE
Holding instance (ALSA - device) of RtAudio

### ISSUE THREAD

**Issue by TJFOE** [thestk/rtaudio#92]
Hi,

I am playing files in a loop. The device should not be called again and again. Could anyone explain howto do this with RtAudio? In the ALSA-API it is clear to me. In RtAudio I must (?) closeStream()... To me it looks like this:

_func(...)
{
...
RtAudio dac; // constructor
dac.openStream();
dac.closeStream();
...
return;
}

Or does a loop work in any way after the constructor and before closeStream(?)

Regards
Thomas

**Comment by garyscavone** [comment]
Hi Thomas,

I’m not quite sure what you are trying to do but you might want to look at the RtAudio API documentation at:

- http://www.music.mcgill.ca/~gary/rtaudio/classRtAudio.html <http://www.music.mcgill.ca/~gary/rtaudio/classRtAudio.html>

If you are playing many files, the normal scheme would be to open the stream once, use start and stop between files, and when completely done, close the stream. The only reason you might need to close and reopen the stream is if the stream parameters (such as sample rate) need to change.

Regards,

—gary

**Comment by TJFOE** [comment]
Thank you Gary,

I know the RtAudio documentation very well :-)

Here is an example (->Answer 1) what could be done in ALSA API. 
https://stackoverflow.com/questions/4474858/alsa-opening-and-closing-pcm-on-the-fly

Here it is not necessary to close the so called "pcm". The stream parameters are i.e. not called with snd_pcm_open()  . 

Regards
Thomas

**Comment by garyscavone** [comment]
The problem was never explained clearly enough.
