### ISSUE TITLE
Error while running the examples in tests folder

### ISSUE THREAD

**Issue by PraveenkumarDonga** [thestk/rtaudio#93]
Hi!
I am trying to run the examples which are given in the tests folder but audio is not coming and no Errors are coming on the console. 
I am using these commands:
1. cd ../rtaudio/tests
2. sudo ./playraw 2 44100 rain.wav

I have played that audio file with ALSA, audio is coming. The command used is 
1. aplay -vv rain.wav

Could you please help me with this.

Thanks,
Praveen.

**Comment by PraveenkumarDonga** [comment]
hi! 
I am also getting this below Error.

![selection_004](https://user-images.githubusercontent.com/8088246/27477259-358923fe-5829-11e7-80da-09c5f11e4092.png)
Please help me with this.

-Praveen

**Comment by radarsat1** [comment]
Is there another program keeping your ALSA device open? e.g. if you have jack running..
Do you get the same error when you run playsaw?  What is the audioprobe output?

**Comment by PraveenkumarDonga** [comment]
Hi!

I am getting the same error with playsaw also.
![selection_006](https://user-images.githubusercontent.com/8088246/27583980-f1f4a4a0-5b53-11e7-90d8-bcefa69a21cc.png)

I have attached the audioprobe file in.txt format. PFA. 
[audioprobe.txt](https://github.com/thestk/rtaudio/files/1105015/audioprobe.txt)

**Comment by garyscavone** [comment]
You should run the audioprobe program to see what devices are found and what their capabilities are. Then an appropriate output device should be used when calling playsaw. If the problem remains, then there may be an issue with your ALSA configuration.
