### ISSUE TITLE
Api-Specific Stream Options

### ISSUE THREAD

**Issue by tay10r** [thestk/rtaudio#97]
I think it might be beneficial to have the ability to specify API-specific options.

In Pulse and in Jack, for example, it would be useful to be able to specific the server name. I'm sure there are options in the other APIs that might be useful too.

There are two ways of doing this (that I can think of).

#### Derived Option Class

The first way, you could make a derived class of `StreamOptions`, such as `JackStreamOptions` and `PulseStreamOptions`.

They would look like this:

```
/*! \brief Specifies stream options that are specific to the JACK API. */
struct JackStreamOptions : public StreamOptions {
  /*! \brief The name of the client that is connecting to the jack server.
     Note: this deprecates StreamOptions::streamName.
   */
  std::string clientName;
  /*! \brief The name of the server that the client is connecting to.
  std::string serverName;
};
```

The library can access the API specific options by either implementing a visitor pattern or using traditional C style casts.

Example of the visitor pattern:

```
struct AlsaStreamOptions;
struct JackStreamOptions;
struct PulseStreamOptions;
struct WasapiStreamOptions;
/* continued */

struct StreamOptionsVisitor {
  void visit(JackStreamOptions &) { }
  void visit(AlsaStreamOptions &) { }
  void visit(PulseStreamOptions &) { }
  void visit(WasapiStreamOptions &) { }
  /* continued */
};

/* example */
struct JackStreamOptions : public StreamOptions {
  void accept(StreamOptionsVisitor &streamOptionsVisitor) {
    streamOptionsVisitor.visit(*this);
  }
};
```

Example of the C style casting:

```
bool RtJackApi::probeDeviceOpen(/* parameters */, StreamOptions *options) {
  if (options->getOptionsType() == RtAudio::OPTIONS_JACK) {
    /* there's API specific options, use derived class */
    JackStreamOptions *jackOptions = (JackStreamOptions *) options;
  } else {
    /* no API specific info, use base class */
  }
}
```

#### A Key and Value Structure

Specify API specific options with a key and value structure.

The structure would look like this:

```
class ApiOptions {
  std::map<std::string,std::string> entries;
public;
  /*! \brief Sets the value of @p key. Converts @p value into a string before adding it to the table. */
  void set(const std::string &key, unsigned int value);
  /*! \brief Sets the value of @p key. A new entry is created if needed. */
  void set(const std::string &key, const std::string &value);
  /*! \brief Retrieves the value of @p key and converts it to an unsigned integer. Returns false if the key is not found. */
  bool get(const std::string &key, unsigned int *value);
  /*! \brief Retrives the value of @p. Returns false if the key is not found. */
  bool get(const std::string &key, std::string &value);
  /*! \brief Lists the keys that are already defined in the table. */
  void list(std::vector<std::string> &optionList);
};
```

A usage example:

```
ApiOptions options;
options.set("Server Name", "Some Jack Server");
options.set("Client Name", "Some Jack Client");
options.set("Input Port ID", 1);
options.set("Output Port ID", 0);
```

This can be a member of the structure `StreamOptions` or it can just replace it entirely.

Replacing it entirely is more work, but it provides a more consistent option-setting interface.

**Comment by monocasual** [comment]
@tay10r what about Jack Transport? At the moment there's no way to control it through RtAudio. Therefore in our codebase we have a customized/hacked version of RtAudio that gives us access to the `JackHandle` object (e.g. [here](https://github.com/monocasual/giada/blob/master/src/deps/rtaudio-mod/RtAudio.cpp#L1944). Do you think that the Jack Transport concept would fit the idea of API-specific options?

**Comment by tay10r** [comment]
@monocasual This feature only effects the API behavior at instantiation.

I'm not a Jack expert, but it seems like you need to control transport _after_ instantiation.

Your issue is essentially the same though, you need access to API specific behavior that's not available due to abstraction. I think perhaps that an `ApiVisitor` class may be a clean solution.

```
class JackTransportUpdater final : public RtAudio::ApiVisitor {
  unsigned int bpm;
public:
  /* ctors, dtors */
  void setBpm(unsigned int bpm) {
    this->bpm = bpm;
  }
  void visit(RtApiJack &jackApi) {
    /* update bpm */
   }
};
```

Usage:

```
RtAudio audio(RtAudio::UNIX_JACK);
/* open stream */
/* start stream */
JackTransportUpdater jackTransportUpdater;
jackTransportUpdater.setBpm(120);
audio.acceptApiVisitor(jackTransportUpdater);
/* close stream */
```

**Comment by radarsat1** [comment]
In principle it's not a bad idea but in practice how many options are we talking about here?  If it's really just port names and ID numbers, I don't see the big advantage over just using RtAudio::StreamParameters.

I do agree that giving access to a backend handle can be useful in some circumstances, as you mention, but that's easy enough with a `void*` cast, even if it's not so clean; it's a rather rare need.  To be honest I find a switch over getCurrentApi() to be much easier to read code-wise than a visitor pattern.

**Comment by tay10r** [comment]
@radarsat1 closing this. Thanks for the feedback!
